added kadane algorithm function
TheAlgorithms/C-Plus-Plus pull request #1079
Opened 2020-09-15 18:21 UTC by ayush523

2020-09-15 18:48 UTC, ayush523 commented
What is the problem with the file that I have added?Please help

2020-09-15 18:56 UTC, Panquesito7 requested changes
Please read the [Contribution Guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) and fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1079/checks?check_run_id=1119386114) warnings.

2020-09-15 19:25 UTC, Panquesito7 commented
The file does not need to be in a specific folder for this algorithm.
It can be in the `others` folder, or in its appropriate folder. 🙂

2020-09-16 04:36 UTC, ayush523 commented
Is that why the tests are failing?

On Wed, 16 Sep, 2020, 12:55 AM David Leal, <notifications@github.com> wrote:

> The file does not need to be in a specific folder for this algorithm.
> It can be in the others folder, or in its appropriate folder. 🙂
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/1079#issuecomment-692927959>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALYLVZAG6BZSYZY5T35ZKQTSF65TZANCNFSM4RNRAABQ>
> .
>

2020-09-16 09:29 UTC, ayush523 commented
I have made the changes.Please check.

2020-09-16 17:09 UTC, Panquesito7 requested changes
Looks much better, good work. 😄 👍
Now, the next thing we shall do is to add documentation.

Confused? See #962 as a reference. 🙂

2020-09-16 17:09 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +}
```suggestion
}

```

2020-09-16 17:09 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +int main() {
```suggestion

/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2020-09-16 17:16 UTC, ayush523 commented
Thanx. I did the changes which you suggested.

2020-09-16 17:23 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +    for (int i = 0; i < n.size(); i++) {
```suggestion
    for (int i : n) {
```

2020-09-16 17:23 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +    std::array<int, 5> n;
```suggestion
    std::array<int, 5> n {};
```

2020-09-16 17:42 UTC, ayush523 commented
Any more changes required?

2020-09-16 17:45 UTC, Panquesito7 commented
Yes, please add documentation like in #962.

2020-09-16 18:47 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +}
```suggestion
}

```

2020-09-16 20:15 UTC, Panquesito7 requested changes

2020-09-16 20:15 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +#include <array>
Provide more information
in the `@details` part of the block.

Confused? See #962 as a reference. 🙂
```suggestion
/**
 * @file
 * @brief Implementation of [Kadane Algorithm](https://en.wikipedia.org/wiki/Kadane%27s_algorithm)
 *
 * @details
 * <full-description here>
 *
 * @author [Ayush Singh](https://github.com/ayush523)
 */
#include <array>
```

2020-09-16 20:15 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +int maxSubArray(const std::array<int, 5> &n) {
Just the documentation template.

Provide brief information about the
function, parameters and return statement.

```suggestion
/**
 * @brief description
 * @param n description
 * @returns description
 */
int maxSubArray(const std::array<int, 5> &n) {
```

2020-09-17 18:19 UTC, Panquesito7 requested changes

2020-09-17 18:19 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> + * Algorithm
```suggestion
 * ### Algorithm
```

2020-09-17 18:44 UTC, Panquesito7 commented on kadane_algorithm/kadane.cpp
> +int maxSubArray(const std::array<int, 5> &n) {
See #962 for how to document functions.

2020-09-18 17:50 UTC, kvedala commented
Is this a repeat of #606 ?

2020-09-18 17:53 UTC, Panquesito7 commented
It seems it is, sorry, my bad!

What if in this PR we improve the current algorithm by adding
documentation and make it more a C++ program?

2020-09-18 17:54 UTC, ayush523 commented
The issue was to create kadane's algorithm.I did that on my own.I haven't copied anyone's code.

2020-09-18 17:56 UTC, ayush523 commented
@Panquesito7 -I have already added documentation which is missing in #606.

2020-09-18 18:03 UTC, kvedala commented
> The issue was to create kadane's algorithm.I did that on my own.I haven't copied anyone's code.

@ayush523 Good to hear that the algorithm and code is your own.
Ensure that:
1. the contributed code and/or the algorithm are different implementations for the same problem
2. the filename should be changed to `dynamic_programming/kadane2.cpp`. make sure no new folders are added.
3. appropriate documentation to explain the new algorithm

Thank you

2020-09-18 18:06 UTC, kvedala commented
> The issue was to create kadane's algorithm.I did that on my own.I haven't copied anyone's code.

2020-09-18 18:08 UTC, ayush523 commented
@kvedala -Sir I have done the required changes.Please check.

2020-09-18 18:08 UTC, kvedala commented
> @kvedala -Sir I have done the required changes.Please check.

@Panquesito7 is the reviewer and he will continue the reviews.

2020-09-18 18:10 UTC, kvedala commented
> It seems it is, sorry for not noticing!
> 
> What if in this PR we improve the current algorithm by adding
> documentation and make it more a C++ program?

Its ok, it is easy to miss the history :)

2020-09-18 18:13 UTC, Panquesito7 requested changes

2020-09-18 18:13 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + */
Provide a brief description about the parameters, return statement and description of the function.
```suggestion
/**
 * @brief description
 * @param n description
 * @returns description
 */
```

2020-09-18 18:29 UTC, Panquesito7 requested changes

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + * @file kadane.cpp
```suggestion
 * @file
```

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + * @brief maxSubArray function
What does this function do?
Document it in the brief description.

If wanted, you can also add further information
about the function using `@details`.

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + */
```suggestion
 */
 template <size_t N>
```

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +int maxSubArray(const std::array<int, 5> &n) {
```suggestion
int maxSubArray(const std::array<int, N> &n) {
```

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + * @brief maxSubArray function
```suggestion
 * @brief maxSubArray function
 * @tparam N number of array size
```

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +    int max_sum = maxSubArray(n);  // calling maxSubArray function
```suggestion
    int max_sum = dynamic_programming::maxSubArray<N>(n);  // calling maxSubArray function
```

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +
```suggestion
/**
 * @namespace dynamic_programming
 * @brief Dynamic Programming algorithms
 */
namespace dynamic_programming {
```

2020-09-18 18:29 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +}
```suggestion
}
}  // namespace dynamic_programming
```

2020-09-19 06:32 UTC, ayush523 commented
@Panquesito7 -I don't understand why the code is not working after the commits suggested.Please help.

2020-09-20 00:19 UTC, Panquesito7 requested changes

2020-09-20 00:19 UTC, Panquesito7 commented on .vscode/c_cpp_properties.json
> +}
Please remove this file.

2020-09-20 00:19 UTC, Panquesito7 commented on .vscode/settings.json
> +     "C_Cpp.errorSquiggles": "Disabled"
Please undo this change.

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +
```suggestion
```

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + * @param n is the array n
```suggestion
 * @param n array where numbers are saved
```

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +    std::array<int, 5> n{};  // declaring array
```suggestion
int main() {
    const int N = 5;
    std::array<int, N> n{};  // declaring array
```

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + * and returns the value of maximum sum which is stored in the variable max_sum
```suggestion
 * and returns the value of maximum sum which is stored in the variable max_sum
 * @tparam N number of array size
```

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +namespace dynamic_programming {
```suggestion
namespace dynamic_programming {
/**
 * @namespace kadane
 * @brief Functions for [Kadane Algorithm](https://en.wikipedia.org/wiki/Kadane%27s_algorithm)
 */
namespace kadane {
```

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +}  // namespace dynamic_programming
```suggestion
}  // namespace kadane
}  // namespace dynamic_programming
```

2020-09-20 00:19 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +        dynamic_programming::maxSubArray<N>(n);  // calling maxSubArray function
```suggestion
        dynamic_programming::kadane::maxSubArray<N>(n);  // calling maxSubArray function
```

2020-09-20 16:59 UTC, Panquesito7 requested changes

2020-09-20 16:59 UTC, Panquesito7 commented on .vscode/settings.json
> +  "editor.formatOnPaste": true
```suggestion
     "C_Cpp.clang_format_style": "{ BasedOnStyle: Google, UseTab: Never, IndentWidth: 4, TabWidth: 4, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: true, ColumnLimit: 80, AccessModifierOffset: -3, AlignConsecutiveMacros: true }",
     "editor.formatOnSave": true,
     "editor.formatOnType": true,
     "editor.formatOnPaste": true
```

2020-09-20 16:59 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> + * @tparam N number of array size
```suggestion
 * @brief maxSubArray function is used to calculate the maximum sum subarray
 * and returns the value of maximum sum which is stored in the variable max_sum
 * @tparam N number of array size
 * @param n array where numbers are saved
 * @returns the value of maximum subarray sum
```

2020-09-20 16:59 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +namespace kadane {
```suggestion
```

2020-09-20 16:59 UTC, Panquesito7 commented on dynamic_programming/kadane2.cpp
> +namespace dynamic_programming {
```suggestion
namespace dynamic_programming {
/**
 * @namespace kadane
 * @brief Functions for [Kadane](https://en.wikipedia.org/wiki/Kadane%27s_algorithm) algorithm.
 */
namespace kadane {
```

2020-09-20 17:16 UTC, Panquesito7 approved these changes
LGTM, good work. 👍 😄

2020-09-20 17:17 UTC, ayush523 commented
Thank you @Panquesito7

2020-09-23 18:07 UTC, kvedala commented
@Panquesito7 do you confirm the algorithm is a different implementation than the existing one? thank you

2020-09-23 18:21 UTC, Panquesito7 commented
Yes, implementation looks different. 🙂
I like this one rather than the current one:

- Has very good documentation
- Uses C++ standard-libraries/functions
- Well-structured and as per the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

Can be merged. 👍

2020-09-23 18:41 UTC, merged