Added strand sort algorithm
TheAlgorithms/C-Plus-Plus pull request #1081
Opened 2020-09-18 15:12 UTC by mertcandav

#### Description of Change
Added strand sort algorithm.

#### Checklist
- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

2020-09-18 17:30 UTC, Panquesito7 reviewed
This seems to be more like a C program, rather than a C++ program.
Would you like this algorithm to be implemented in the [C](https://github.com/TheAlgorithms/C) repository?

If you still want this in C++, we can improve
it further and make it a C++ program. 🙂

2020-09-18 17:35 UTC, mertcandav commented
Yes it can be implemented, my goal is just to contribute :)

2020-09-18 18:04 UTC, Panquesito7 requested changes
Please move this file to the `sorting` directory.

2020-09-18 18:08 UTC, mertcandav commented
Moved to ``sorting`` directory.

2020-09-18 18:15 UTC, Panquesito7 requested changes

2020-09-18 18:15 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +#include <iostream>
See #962 as a reference on how to document the first comment block.
```suggestion
/**
 * @file
 * @brief description of algorithm
 *
 * @details
 * <full-description here>
 *
 * @author [Mertcan Davulcu](https://github.com/mertcandav)
 */
#include <iostream>
```

2020-09-18 18:15 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +std::list<T> strand_sort(std::list<T> lst) {
Missing function documentation, parameter
documentation and return statement documentation.

See #962 as a reference.

2020-09-18 18:15 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +// Entry point for testing
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2020-09-18 19:17 UTC, Panquesito7 requested changes

2020-09-18 19:17 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +namespace strand {
```suggestion
/**
 * @namespace sorting
 * @brief Sorting algorithms
 */
namespace sorting {
/**
 * @namespace strand
 * @brief Functions for [Strand Sort](https://en.wikipedia.org/wiki/Strand_sort) algorithm
 */
namespace strand {
```

2020-09-18 19:17 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +} // namespace strand
```suggestion
}  // namespace strand
}  // namespace sorting
```

2020-09-18 19:17 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +    */
You can also provide further information by using
`@details` as in the first comment block. 🙂

See #962 as a reference for how to document functions.
```suggestion
    /**
    * @brief Apply sorting
    * @param lst List to be sorted
    * @returns <provide description here>
    */
```

2020-09-18 19:24 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +        // Element type of list.
```suggestion
```

2020-09-18 19:24 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +        * @brief Apply sorting
```suggestion
        * @brief Apply sorting
        * @tparam element type of list
```

2020-09-18 19:30 UTC, Panquesito7 commented on sorting/strand_sort.cpp
> +        std::list<T> strand_sort(std::list<T> lst) {
```suggestion
        /**
        * @brief Apply sorting
        * @tparam element type of list
        * @param lst List to be sorted
        * @returns Sorted list<T> instance
        */
        template <typename T>
        std::list<T> strand_sort(std::list<T> lst) {
```

2020-09-18 19:35 UTC, Panquesito7 approved these changes
LGTM, good work. 👍

2020-09-20 15:44 UTC, kvedala requested changes
well documented code 👍

2020-09-20 15:44 UTC, kvedala commented on sorting/strand_sort.cpp
> + * Strand Sort is a sorting algorithm that works in (O(n)) time if list is already sorted and works in (O(n * n)) in worst case.
```suggestion
 * Strand Sort is a sorting algorithm that works in \f$O(n)\f$ time if list is already sorted and works in \f$O(n^2)\f$ in worst case.
```

2020-09-20 15:44 UTC, kvedala commented on sorting/strand_sort.cpp
> + * + It is passed over the array to be sorted once and the ascending (sequential) numbers are taken.
```suggestion
 * It is passed over the array to be sorted once and the ascending (sequential) numbers are taken.
```
1. please remove the `### Algorithm` as it is redundant and will be properly formatted by doxygen
2. please remove the preceding `+` on the lines. If implying bullet points, then use `*` or `-`

2020-09-20 15:44 UTC, kvedala commented on sorting/strand_sort.cpp
> +#include <iostream>
duplicate line
```suggestion
```

2020-09-20 15:44 UTC, kvedala commented on sorting/strand_sort.cpp
> +/**
please add a `static void test() {}` function. as in other sorting algorithm programs. 
https://github.com/TheAlgorithms/C-Plus-Plus/blob/d4b54b8294722607f8ed1e29f2b3ff500ba787e7/sorting/merge_insertion_sort.cpp#L128

2020-09-23 18:05 UTC, kvedala commented
Awesome. Can you enable GitHub Actions using this link: https://github.com/mertcandav/C-Plus-Plus/actions
Any minor commit will trigger the actions on your branch. This will ensure any syntax corrections and additional commits are managed appropriately.

2020-09-23 18:17 UTC, mertcandav commented
I think I activated it.

2020-09-23 18:40 UTC, kvedala commented
> I think I activated it.

Please make a small commit to trigger the actions. For example, delete line# 8 in the code. It is unnecessary. 
If the actions have been enabled, we should see a commit made by the GitHub-actions to the file DIRECTORY.md.

2020-09-23 19:15 UTC, mertcandav commented
Yes, enabled.

2020-09-30 17:20 UTC, kvedala approved these changes
LGTM 👍

2020-09-30 17:21 UTC, Panquesito7 approved these changes

2020-09-30 17:21 UTC, merged