Nth fibonacci number using matrix exponentiation
TheAlgorithms/C-Plus-Plus pull request #1215
Opened 2020-10-07 13:35 UTC by villayatali123

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-10 05:25 UTC, nishant230701 requested changes
why even use 
#include <bits/stdc++.h?>
Just use 
#include <iostream>
#include <vector>

2020-10-16 12:40 UTC, kvedala requested changes
1. Please review the contribution guidelines
2. no global variables
3. if need to use variables to track, you can do either of the following:
    1. use namespaces 
    2. use structs or classes
4. update documentation of the function similar to other files, [like this](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/fibonacci_large.cpp)

2020-10-16 12:40 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + */
```suggestion
```

2020-10-16 12:40 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> +/* @details
```suggestion
 * @details
```

2020-10-16 12:40 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + * a = arr1[0][0] * arr2[0][0] + arr1[0][1] * arr2[1][0]
```suggestion
 * ```
 * a = arr1[0][0] * arr2[0][0] + arr1[0][1] * arr2[1][0]
```

2020-10-19 13:23 UTC, kvedala requested changes
I suggest read the guidelines and the checklist at least once.

2020-10-19 13:23 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + *Begin
If you can review the checklist, one of the items is about the documentation. It explains what protocol we follow: doxygen. In this protocol, all documentations will be interpreted in Markdown syntax. These successive lines, though look good in the code, will not render properly i.e., they will not be rendered as WYSIWYG. To add breaks, add a new line "\n" at the end of each line. Please review the existing codes, references, checklist.

2020-10-19 13:23 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + * '''
as suggested before, the character to mark a verbatim section is: [`&grave;`](https://www.toptal.com/designers/htmlarrows/punctuation/grave-accent/) and not [`'`](https://www.toptal.com/designers/htmlarrows/punctuation/apostrophe/)

2020-10-19 23:50 UTC, kvedala requested changes
👍

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> +int fibo(int n , int mod )
```suggestion
uint64_t fibo(uint64_t n , uint64_t mod )
```
to handle large numbers

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + * @brief Computes N^th Fibonacci number given as
Not true. This program computes the "N^th Fibonacci number in modulo M" which is a bit different.

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + * @file fibonacci_matrix_exponentiation.cpp
```suggestion
 * @file 
```

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + * This function finds nth fibonacci number.
```suggestion
 * This function finds nth fibonacci number in a given modulus.
```

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> + * @param mod  modulo number to avoid overflow
```suggestion
 * @param mod  modulo number
```
the Fibonacci series in modulus has its own applications.

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> +	std::vector<int> result(2,0);
wherever there are large unsigned integers, use `uint64_t`.

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> +    std::cout << "test case:3 passed\n";
can also add some other cases for different modulus:
Fibonacci(500, 100)
Fibonacci(500, 1000)
Fibonacci(50, 100)
Fibonacci(50, 200)

2020-10-19 23:50 UTC, kvedala commented on math/fibonacci_matrix_exponentiation.cpp
> +	std::cout<<n<<"th Fibonacci number :"<<fibo( n , mod);
```suggestion
	std::cout<<n<<"th Fibonacci number in modulo " << mod << ": "<< fibo( n , mod) << std::endl; 
```

2020-10-21 08:47 UTC, villayatali123 commented
i have made the changes please review it .

2020-10-22 15:08 UTC, villayatali123 commented
Approve it ASAP !

2020-10-24 03:50 UTC, villayatali123 commented
Approve it please ASAP !

2021-02-05 09:41 UTC, kvedala approved these changes

2021-02-05 09:42 UTC, merged