Create fenwick_tree_2D.cpp
TheAlgorithms/C-Plus-Plus pull request #1230
Opened 2020-10-08 17:43 UTC by zyrch

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-08 21:40 UTC, kvedala commented
Review existing code and standards: https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/range_queries/fenwick_tree.cpp
![image](https://user-images.githubusercontent.com/7001608/95516528-5ec5eb80-098d-11eb-8a7d-bef55d94c9df.png)

2020-10-09 10:20 UTC, zyrch commented
Changes have been made.

2020-10-12 06:18 UTC, ayaankhan98 approved these changes

2020-10-12 06:20 UTC, ayaankhan98 commented
code looks fine but documentation is not up to standard

2020-10-13 16:36 UTC, zyrch commented
changes have been made

2020-10-13 17:46 UTC, Panquesito7 requested changes
Documentation is still not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please see the [typical structure](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program, that might help. 🙂

2023-04-25 14:26 UTC, realstealthninja commented
this seems to be stale

2023-04-25 14:28 UTC, realstealthninja commented on range_queries/fenwick_tree_2d.cpp
> +#include <vector>
```suggestion
#include <iostream> /// for I/O operations
#include <cassert> /// for assert
#include <vector> /// for std::vector
```
needs documentation

2023-04-25 14:30 UTC, realstealthninja commented on range_queries/fenwick_tree_2d.cpp
> +    std::cout << "All Test Passed\n";
should be moved to a function
```cpp
void test() {};
```

2023-04-25 14:31 UTC, realstealthninja commented on range_queries/fenwick_tree_2d.cpp
> +
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2023-04-25 16:40 UTC, fhlasek commented on range_queries/fenwick_tree_2d.cpp
> +    T sum(int idx) {
might want to check if `idx <= siz`

2023-04-25 16:40 UTC, fhlasek commented on range_queries/fenwick_tree_2d.cpp
> +    void update(int idx, T delta) {
similarly, could check the bounds of `idx`

2023-04-25 16:40 UTC, fhlasek commented on range_queries/fenwick_tree_2d.cpp
> +    T query(int l, int r) {
finally, here are even more implicit assumptions on the input, `0 < l <= r <= siz` (I believe)

2023-04-25 16:40 UTC, fhlasek commented on range_queries/fenwick_tree_2d.cpp
> +    // sum of region {x1 to x} and {y1 to y}
nit: For clarity, I think it would be better to call them `x1`, `x2` and `y1`, `y2`

2024-08-29 13:35 UTC, closed without merging