Create house_robber.cpp
TheAlgorithms/C-Plus-Plus pull request #1247
Opened 2020-10-10 19:14 UTC by SumukhBhardwaj

Added House Robber problem, solved using dynamic programming

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-11 03:30 UTC, kvedala commented
Does your code conform to the standards and the checklist?
![image](https://user-images.githubusercontent.com/7001608/95669604-8d3ff400-0b50-11eb-8dfe-979a43d8189d.png)

2020-10-11 03:32 UTC, SumukhBhardwaj commented
> Does your code conform to the standards and the checklist?
> ![image](https://user-images.githubusercontent.com/7001608/95669604-8d3ff400-0b50-11eb-8dfe-979a43d8189d.png)

Yes I have added enough comments and also take care of naming conventions.

2020-10-11 03:34 UTC, kvedala commented
It does not follow the repo standards. All the details are provided in the links in the checklist. Please review and update the code accordingly. No reviews will be provided until the code is updated to the repo standards. 
Thank you for your contribution.

2020-10-11 04:08 UTC, SumukhBhardwaj commented
> It does not follow the repo standards. All the details are provided in the links in the checklist. Please review and update the code accordingly. No reviews will be provided until the code is updated to the repo standards.
> Thank you for your contribution.

Please review now, i have added test cases and solution as well.

2020-10-11 06:41 UTC, SumukhBhardwaj commented
@kvedala  please review it now. I have done all the required changes.

2020-10-16 12:33 UTC, kvedala requested changes
👍 
Good update but much needs to be done still. Please review the comments thoroughly.

2020-10-16 12:33 UTC, kvedala commented on dynamic_programming/house_robber.cpp
> +/*House Robber - Dynamic Programming
```suggestion
/**
 * @file 
 * @brief House Robber - Dynamic Programming
```
Update the documetnation block per the guidelines. A sample code is provided for your convenience. In the above comment, an example existing code was also provided as a reference.

2020-10-16 12:33 UTC, kvedala commented on dynamic_programming/house_robber.cpp
> + * @money array of numbers containing the money in the ith house
the doc blocks are not per the requested, suggested and described in the guidelines. refer to the comment above.

The "This" does not reflect in the documentation. You can review the documentation site: http://thealgorithms.github.io/C-Plus-Plus
You can split the file and function documentations. See [this file](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/dynamic_programming/kadane2.cpp) for example. Also note the use of namespaces.

2021-06-18 17:52 UTC, Swastyy commented
@SumukhBhardwaj hey! where did you find the problem statement? 
Can you please tell me how can I share my solution?
(P.S. I am new to open source and need some initial help.)

2021-07-13 00:57 UTC, closed without merging