Create wildcard_string_matching.cpp
TheAlgorithms/C-Plus-Plus pull request #1248
Opened 2020-10-10 19:20 UTC by SumukhBhardwaj

Added wildcard string matching problem, solved using dynamic programming

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-11 06:55 UTC, SumukhBhardwaj commented
@kvedala I have done all the changes please review it now.

2020-10-12 18:41 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/SumukhBhardwaj/C-Plus-Plus/actions

2020-10-12 18:41 UTC, Panquesito7 commented on dynamic_programming/wildcard_string_matching.cpp
> +static void test() {
```suggestion
/**
 * @brief Test implementations
 * @returns void
 */
static void test() {
```

2020-10-12 18:41 UTC, Panquesito7 commented on dynamic_programming/wildcard_string_matching.cpp
> + * @returns 0/1 depending upon strings can be matched or not
```suggestion
 * @param s matching string which is to be matched with pattern
 * @param p pattern string containing alphabets, '?' and '*'
 * @param pos1 the current position on string s
 * @param pos2 the current position on string p
 * @param dpTable is the memorization table, having the previously calculated result
 * @returns 0/1 depending upon strings can be matched or not
```

2020-10-12 18:41 UTC, Panquesito7 commented on dynamic_programming/wildcard_string_matching.cpp
> +/*
For how to document the first comment block, please see the [typical structure](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program.

2021-07-30 15:37 UTC, closed without merging