feat: add cycle sort algorithm
TheAlgorithms/C-Plus-Plus pull request #1252
Opened 2020-10-11 07:00 UTC by dalaoqi

#### Description of Change

Added the code for Cycle sort algorithm.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-12 18:56 UTC, Panquesito7 requested changes

2020-10-12 18:56 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> + *@author [TsungHan Ho](https://github.com/dalaoqi)
```suggestion
 * @details
 * Cycle Sort is a sorting algorithm that works in \f$O(n^2)\f$ time in best cas and works in \f$O(n^2)\f$ in worst case.
 * If a element is already at its correct  position, do nothing.
 * If a element is not at its correct position, we then need to move it to its correct position by computing the correct positions.Therefore, we should make sure the duplicate elements.
 *
 *@author [TsungHan Ho](https://github.com/dalaoqi)
```

2020-10-12 18:56 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +void swap(int *a, int *b) {
Missing function documentation.

2020-10-12 18:56 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +void cycleSort(std::vector<int> *arr) {
Function not documented.

2020-10-12 18:56 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +void test() {
All test functions must be **static**.
```suggestion
static void test() {
```

2020-10-12 18:56 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +/* Test function */
```suggestion
/**
 * @brief Test implementations
 * @returns void
 */
```

2020-10-12 18:56 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +/* Main function */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2020-10-13 18:49 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/dalaoqi/C-Plus-Plus/actions

2020-10-13 18:49 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> + * @return void
```suggestion
 * @returns void
```

2020-10-13 18:49 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> + * @return void
```suggestion
 * @returns void
```

2020-10-14 21:05 UTC, Panquesito7 requested changes

2020-10-14 21:05 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +/**
```suggestion
/**
 * @namespace sorting
 * @brief Sorting algorithms
 */
namespace sorting {
/**
 * @namespace cycle_sort
 * @brief Functions for [Cycle sort](https://en.wikipedia.org/wiki/Cycle_sort) algorithm
 */
namespace cycle_sort {
/**
```

2020-10-14 21:05 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +}
```suggestion
}
}  // namespace cycle_sort
}  // namespace sorting

```

2020-10-14 21:05 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +}
```suggestion
}

```

2020-10-14 21:05 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +    cycleSort(arr);
```suggestion
    sorting::cycle_sort::cycleSort(arr);
```

2020-10-15 19:35 UTC, Panquesito7 requested changes

2020-10-15 19:35 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +static void test() {
Test implementations use `assert` (requires the `cassert` library) to verify the code works as expected.

2020-10-16 06:10 UTC, dalaoqi commented
How do I solve this problem? Thx
![image](https://user-images.githubusercontent.com/13413575/96219323-250e6980-0fb9-11eb-9c1e-f9ee4fe1e97a.png)

2020-10-16 22:08 UTC, Panquesito7 commented
> How do I solve this problem?
> ![image](https://user-images.githubusercontent.com/13413575/96219323-250e6980-0fb9-11eb-9c1e-f9ee4fe1e97a.png)

Should be fixed now.

2020-10-16 22:16 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> + * @brief Sorting algorithm
```suggestion
 * @brief Sorting algorithms
```

2020-10-16 22:16 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +#include <vector>
```suggestion
#include <algorithm> /// for std::is_sorted
#include <cassert>   /// for assert
#include <iostream> /// for io operations
#include <vector>   /// for std::vector
```

2020-10-18 20:02 UTC, Panquesito7 approved these changes
Amazing work, I like how you've improved the code so well.
Code and documentation looks good and very refined; LGTM. 😄 👍

2020-10-19 07:08 UTC, dalaoqi commented
Thanks for the review! 😄

2020-10-19 23:23 UTC, kvedala commented on sorting/cycle_sort.cpp
> +    for (int cycle_start = 0; cycle_start <= (*arr).size() - 1; cycle_start++) {
```suggestion
    for (size_t cycle_start = 0; cycle_start <= arr->size() - 1; cycle_start++) {
```

2020-10-19 23:23 UTC, kvedala commented on sorting/cycle_sort.cpp
> +        swap(&item, &(*arr)[pos]);
```suggestion
        std::swap(item, (*arr)[pos]);
```

2020-10-19 23:23 UTC, kvedala commented on sorting/cycle_sort.cpp
> +            swap(&item, &(*arr)[pos]);
```suggestion
            std::swap(item, (*arr)[pos]);
```

2020-10-19 23:23 UTC, kvedala commented on sorting/cycle_sort.cpp
> +            for (int i = cycle_start + 1; i < (*arr).size(); i++) {
```suggestion
            for (size_t i = cycle_start + 1; i < (*arr).size(); i++) {
```

2020-10-19 23:23 UTC, kvedala commented on sorting/cycle_sort.cpp
> +void cycleSort(std::vector<T> *arr) {
a better approach might be as below. This is only a suggestion and is up to you if you want to implement.
```suggestion
std::vector<T> cycleSort(const std::vector<T> &in_arr) {
    std::vector<T> arr(in_arr); // create a copy of the input array, process it and return a new array. Thus, the input array does not get modified and no need for pointers :)
```

2020-10-21 15:07 UTC, kvedala approved these changes
👍

2020-10-21 15:07 UTC, merged