fix duplication of dijkstra.cpp in greedy_algorithms
TheAlgorithms/C-Plus-Plus pull request #1259
Opened 2020-10-12 09:34 UTC by xgupta

#### Description of Change

File dijkstra.cpp  is placed in two directory graph and greedy_algorithms which cause a problem in building with CMake.  This change makes it possible to build the dijkstra.cpp in greedy_algorithms.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-12 18:01 UTC, Panquesito7 approved these changes

2020-10-15 18:28 UTC, xgupta commented
I think we should commit the change to upstream.

2020-10-16 17:10 UTC, kvedala requested changes

2020-10-16 17:10 UTC, kvedala commented on greedy_algorithms/dijkstra_spf.cpp
> +int minDistance(std::vector<int> mdist, std::vector<bool> vset, int V) {
```suggestion
int minDistance(const std::vector<int> &mdist, const std::vector<bool> &vset) {
uint32_t V = mdist.size();
```

2020-10-16 17:10 UTC, kvedala commented on greedy_algorithms/dijkstra_spf.cpp
> +void print(std::vector<int> dist, int V) {
```suggestion
void print(const std::vector<int> &dist) {
uint32_t V = dist.size();
```

2020-10-16 17:10 UTC, kvedala commented on greedy_algorithms/dijkstra_spf.cpp
>  // Wrapper class for storing a graph
```suggestion

namespace greedy_algorithms {

namespace dijkstra {

// Wrapper class for storing a graph
```

2020-10-16 17:10 UTC, kvedala commented on greedy_algorithms/dijkstra_spf.cpp
>  int main() {
```suggestion
} // namespace dijkstra
} // namespace greedy_algorithms

// Driver function
int main() {
```

2020-10-16 17:10 UTC, kvedala commented on greedy_algorithms/dijkstra_spf.cpp
>  void Dijkstra(Graph graph, int src) {
```suggestion
void Dijkstra(const Graph &graph, int src) {
```

2020-10-16 17:10 UTC, kvedala commented on greedy_algorithms/dijkstra_spf.cpp
> +    delete[] G.edges;
This delete is incorrect. 
Please add a destructor to the Graph class that will deallocate the memory.

2020-10-16 17:10 UTC, kvedala commented
This is a good opportunity to fix some of the older incorrect code. 😄

2020-10-23 09:26 UTC, closed without merging