fix greedy_algorithms/knapsack.cpp to satisfy clang-tidy warnings
TheAlgorithms/C-Plus-Plus pull request #1261
Opened 2020-10-12 09:59 UTC by xgupta

#### Description of Change

Fx greedy_algorithms/knapsack.cpp to satisfy clang-tidy warnings.

#### Checklist

- [x] Added description of change
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-12 18:02 UTC, Panquesito7 approved these changes

2020-10-12 18:02 UTC, Panquesito7 commented on greedy_algorithms/knapsack.cpp
> +
```suggestion
```

2020-10-16 15:41 UTC, kvedala requested changes
would be great if you can add the documentation as well.
Thank you

2020-10-16 15:41 UTC, kvedala commented on greedy_algorithms/knapsack.cpp
> +int partition(std::vector<Item> arr, int low, int high) {
```suggestion
int partition(const std::vector<Item> &arr, int low, int high) {
```

2020-10-16 15:41 UTC, kvedala commented on greedy_algorithms/knapsack.cpp
> +float profitPerUnit(Item x) {
```suggestion
float profitPerUnit(const Item &x) {
```

2020-10-16 15:41 UTC, kvedala commented on greedy_algorithms/knapsack.cpp
>  struct Item {
```suggestion

namespace greedy_algorithms {

namespace knapsack {

struct Item {
```

2020-10-16 15:41 UTC, kvedala commented on greedy_algorithms/knapsack.cpp
```suggestion
} // namespace knapsack
} // namespace greedy_algorithms

using greedy_algorithms::knapsack::Item;
using greedy_algorithms::knapsack::quickSort;
```

2020-10-16 17:58 UTC, xgupta commented
/home/user/C-Plus-Plus/greedy_algorithms/knapsack.cpp:28:20: error: no viable overloaded '=' [clang-diagnostic-error]
            arr[i] = arr[j];

When we make array as constant this message is produced by clang-tidy. Because we are then want to modify its value.

2020-10-16 20:05 UTC, kvedala requested changes
some suggestions have been blindly marked "resolved" while the concerns still remain in the code.
Please re-review the above suggestion.

2020-10-16 20:05 UTC, kvedala commented on greedy_algorithms/knapsack.cpp
> + * @author [Krishna Vedala](https://github.com/kvedala)
```suggestion
```
Thank you. I only reviewed but did not make the changes. Keep your name.

2020-10-23 09:25 UTC, closed without merging