remove using namespace std;
TheAlgorithms/C-Plus-Plus pull request #1263
Opened 2020-10-12 11:46 UTC by x0rld

using namespace std is a bad pratice.

2020-10-12 12:21 UTC, xgupta commented
Use std::vector instead of VLA to pass the clang-tidy errors. 
For example replace int n[] to std::vector<int> n;

2020-10-12 12:34 UTC, x0rld commented
I will continue later

2020-10-16 13:05 UTC, kvedala requested changes
thank you for your contribution

2020-10-16 13:05 UTC, kvedala commented on operations_on_datastructures/array_left_rotation.cpp
>      getchar();
```suggestion
```

2020-10-19 13:29 UTC, kvedala commented
This folder and the code therein is not making much sense to me for this repo. @Panquesito7 @fhlasek @ayaankhan98  thoughts?

2020-10-19 21:11 UTC, fhlasek commented
@kvedala I agree with you. On top of it, the code is of such a low quality that I don't think it carries much value. Rather than trying to refactor, I'd suggest to deprecate it and let the community recreate whatever valuable algorithms there might have been following the improved guidelines and best coding practices.

2020-10-20 00:12 UTC, kvedala commented
@x0rld Thank you for your contribution. However, the admins find that this folder and the code therein is rudimentary and will need to be either removed altogether or salvaged in to one of the other folders in a more refined code. 

We more than welcome you to contribute in the latter 😄

2020-10-20 00:12 UTC, closed without merging