remove using namespace std;
TheAlgorithms/C-Plus-Plus pull request #1264
Opened 2020-10-12 13:05 UTC by x0rld

using namespace std is a bad practice

2020-10-12 17:57 UTC, Panquesito7 requested changes
Please create one PR per file.
This will make the review process much better.

2020-10-16 19:03 UTC, kvedala commented
Thank you for your initiative to fix the code. It would be better if you can fix the code and bring it to the repo's standards. the details are provided in the contributions guidelines and in the checklist above.

2020-10-19 13:30 UTC, kvedala approved these changes
LGTM

2020-10-19 21:38 UTC, Panquesito7 approved these changes

2020-10-19 21:40 UTC, merged