added rail_fence_cipher.cpp
TheAlgorithms/C-Plus-Plus pull request #1267
Opened 2020-10-12 17:27 UTC by sushmit-goyal

#### Description of Change
Added rail_fence_cipher.cpp

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-16 14:01 UTC, kvedala requested changes
👍 
good code. note the comments

2020-10-16 15:30 UTC, kvedala commented on ciphers/rail_fence_cipher.cpp
> +            std::vector<std::string> rail(num_rows);
Try for example: changing the test case "ILoveAlgorithms" to "I Love Algorithms".

2020-10-21 15:30 UTC, sushmit-goyal commented on ciphers/rail_fence_cipher.cpp
> +            std::vector<std::string> rail(num_rows);
Changed the case to "I Love Algorithms". Seems to work fine. Please have a look now

2021-02-05 10:09 UTC, kvedala commented on ciphers/rail_fence_cipher.cpp
> +/*
```suggestion
/**
```

doc-comment blocks must begin with `/**` and then with `*/`. Please update other locations as well.

2021-09-16 00:38 UTC, closed without merging