adding word break DP approach
TheAlgorithms/C-Plus-Plus pull request #1278
Opened 2020-10-14 04:54 UTC by axayjha

#### Description of Change
Adding dynamic programming approach for the famous Word Break problem which has been frequently asked in FAANG interviews.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-14 21:01 UTC, Panquesito7 requested changes
Documentation is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

2020-10-14 21:01 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +}
```suggestion
}

```

2020-10-14 21:01 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +int main() {
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2020-10-15 16:04 UTC, axayjha commented
Have made the requested changes. Added documentation and enhancements.

2020-10-15 16:04 UTC, axayjha commented on dynamic_programming/word_break.cpp
> +}
Done

2020-10-15 16:05 UTC, axayjha commented on dynamic_programming/word_break.cpp
> +int main() {
Done

2020-10-15 18:14 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/axayjha/C-Plus-Plus/actions

2020-10-15 18:14 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +/**
```suggestion
/**
 * @namespace dynamic_programming
 * @brief Dynamic programming algorithms
 */
namespace dynamic_programming {
/**
 * @namespace word_break
 * @brief Functions for Word Break algorithm
 */
namespace word_break {
/**
```

2020-10-15 18:14 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +};
```suggestion
};
}  // namespace word_break
}  // namespace dynamic_programming

```

2020-10-15 18:14 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +    cout << Solution().wordBreak(s, wordDict) << endl;
```suggestion
    cout << dynamic_programming::word_break::Solution().wordBreak(s, wordDict) << endl;
```

2020-10-15 18:58 UTC, axayjha commented
Added Github Actions to my fork

2020-10-15 19:01 UTC, axayjha commented
Have made the requested changes

2020-10-15 19:02 UTC, Panquesito7 requested changes

2020-10-15 19:05 UTC, axayjha reviewed
Code is now conforming to guidelines

2020-10-15 19:26 UTC, Panquesito7 requested changes
Good work, code looks pretty refined now. 😄 👍
Let us add some tests using `assert` to check if the code runs fine.

2020-10-15 19:26 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> + * @brief [Word Break Problem] (https://leetcode.com/problems/word-break/)
```suggestion
 * @brief [Word Break Problem](https://leetcode.com/problems/word-break/)
```

2020-10-15 19:26 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> + * @brief Functions for Word Break algorithm
```suggestion
 * @brief Functions for [Word Break](https://leetcode.com/problems/word-break/) problem
```

2020-10-15 19:26 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> + * @returns `false` otherwise
```suggestion
 * @returns `false` if str is not present in strSet
```

2020-10-15 19:26 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +#include <vector>
```suggestion
#include <vector>
#include <cassert>
```

2020-10-15 19:26 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +
```suggestion

/**
 * @brief Test implementations
 * @returns void
 */
static void test() {
    // the complete string
    const std::string s = "applepenapple";
    // the dictionary to be used
    const std::vector<std::string> wordDict = {"apple", "pen"};

    assert(dynamic_programming::word_break::wordBreak(s, wordDict));

    // should return true, as applepenapple can be segmented as apple + pen +
    // apple
    std::cout << dynamic_programming::word_break::wordBreak(s, wordDict)
              << std::endl;
    std::cout << "Test implementation passed!\n";
 }
```

2020-10-15 19:26 UTC, Panquesito7 commented on dynamic_programming/word_break.cpp
> +              << std::endl;
```suggestion
    test(); // run the tests
    return 0;
```

2020-10-15 19:40 UTC, Panquesito7 approved these changes
Amazing work, I like how you've improved the code so well.
Code and documentation looks good and very refined; LGTM. 😄 👍

2020-10-15 19:45 UTC, axayjha commented
Thanks man, got to learn a lot in the process. Cheers

2020-10-16 17:17 UTC, kvedala approved these changes
👍 Well written and documented code

2020-10-16 17:22 UTC, kvedala commented on dynamic_programming/word_break.cpp
> +    // the complete string
```suggestion

   test(); // call the test function :)

    // the complete string
```

2020-10-16 19:54 UTC, merged

2020-10-17 04:06 UTC, axayjha commented
@kvedala @Panquesito7 
Hey chief, would you be kind enough to please label this PR as 'hacktoberfest-accepted'?

2020-10-17 04:25 UTC, Panquesito7 commented
> label this PR as 'hacktoberfest-accepted'?

This repository has the `hacktoberfest` topic, so, once your PR is
merged, it counts toward completing the Hacktoberfest challenge. 🙂

2020-10-17 04:34 UTC, axayjha commented
Yes, I noticed after commenting. 😜  Thanks. 😄