adding graph_coloring.cpp
TheAlgorithms/C-Plus-Plus pull request #1301
Opened 2020-10-16 10:59 UTC by sharyudongre

Signed-off-by: sharyu <sharyudongre@gmail.com>

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-16 11:35 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +
add namespace

2020-10-16 11:35 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +	~Graph()	 { delete [] adj; }
if the destructor is not used, remove it

2020-10-16 11:36 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +		result[u] = -1;  // no color is assigned to u
put it inside braces

2020-10-16 11:36 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +		available[color] = false;
curly braces

2020-10-16 11:36 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +		for (color = 0; color < V; color++)
write int inside for loop and use braces

2020-10-16 11:36 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +				break;
curly braces

2020-10-16 11:37 UTC, ridhishjain commented on graph/NP_complete_graph_coloring.cpp
> +}
curly braces

2020-10-16 11:40 UTC, ridhishjain requested changes
please change these things

2020-10-16 21:58 UTC, Panquesito7 commented
Isn't this a duplicate of [`backtracking/graph_coloring.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/backtracking/graph_coloring.cpp)?

2020-10-22 04:20 UTC, sharyudongre commented
> Isn't this a duplicate of [`backtracking/graph_coloring.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/backtracking/graph_coloring.cpp)?

this is by using greedy algorithm.

2021-09-16 00:38 UTC, closed without merging