Create power_of_two.cpp
TheAlgorithms/C-Plus-Plus pull request #1315
Opened 2020-10-17 12:35 UTC by neha-hasija17

This Pull Request is for HacktoberFest 2020

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-18 19:26 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/neha-hasija17/C-Plus-Plus/actions

2020-10-18 19:26 UTC, Panquesito7 commented on math/power_of_two.cpp
> +/** Driver Code */
```suggestion
```

2020-10-18 19:26 UTC, Panquesito7 commented on math/power_of_two.cpp
> +    int n;
```suggestion
    int n = 0;
```

2020-10-18 19:26 UTC, Panquesito7 commented on math/power_of_two.cpp
> + * @file power_of_two.cpp
```suggestion
 * @file
```

2020-10-18 19:26 UTC, Panquesito7 commented on math/power_of_two.cpp
> +
```suggestion
```

2020-10-18 19:26 UTC, Panquesito7 commented on math/power_of_two.cpp
> + * Function to test above algorithm
Missing parameter documentation.
```suggestion
 * @brief Function to test above algorithm
 * @param n description
 * @returns void
```

2020-10-18 19:50 UTC, Panquesito7 requested changes

2020-10-18 19:50 UTC, Panquesito7 commented on math/power_of_two.cpp
> +#include <iostream>
```suggestion
#include <iostream>  /// for std::cout
```

2020-10-18 19:50 UTC, Panquesito7 commented on math/power_of_two.cpp
> +/**
```suggestion

/**
 * @namespace math
 * @brief Math algorithms
 */
namespace math {
/**
```

2020-10-18 19:50 UTC, Panquesito7 commented on math/power_of_two.cpp
> +}
```suggestion
}
}  // namespace math
```

2020-10-18 19:50 UTC, Panquesito7 commented on math/power_of_two.cpp
> +    ///function call with @param n
```suggestion
    ///  function call with @param n
```

2020-10-18 19:50 UTC, Panquesito7 commented on math/power_of_two.cpp
> +    ///n stores the input from the user
```suggestion
    /// n stores the input from the user
```

2020-10-18 19:50 UTC, Panquesito7 commented on math/power_of_two.cpp
> +    power_of_two(n);
Please add self-test cases, to ensure the algorithm works as excepted.

2020-10-21 18:12 UTC, neha-hasija17 commented
@Panquesito7 please review this as well.

2020-10-21 19:04 UTC, Panquesito7 requested changes

2020-10-21 19:04 UTC, Panquesito7 commented on math/power_of_two.cpp
> +/**
```suggestion

/**
 * @namespace math
 * @brief Mathematical algorithms
 */
namespace math {
/**
```

2020-10-21 19:04 UTC, Panquesito7 commented on math/power_of_two.cpp
> +}
```suggestion
}
}  // namespace math

```

2020-10-21 19:22 UTC, Panquesito7 requested changes

2020-10-21 19:22 UTC, Panquesito7 commented on math/power_of_two.cpp
> +    power_of_two(n);
```suggestion
    math::power_of_two(n);
```

2020-10-22 18:06 UTC, Panquesito7 approved these changes
LGTM, good work! 😄 👍

2020-10-22 18:10 UTC, neha-hasija17 commented
@Panquesito7 sir, it would be kind of you please merge it.

2020-10-22 18:31 UTC, Panquesito7 commented
> please merge it

Will do until @kvedala reviews the PR. 🙂

2021-02-05 09:41 UTC, kvedala requested changes
the contribution looks good.
However, please undo the changes to the file `pancake_sort.cpp`; then this can be merged

2021-02-12 02:55 UTC, Panquesito7 commented
> changes to the file `pancake_sort.cpp`

It seems those changes were made by the CI (https://github.com/TheAlgorithms/C-Plus-Plus/pull/1315/commits/caf2ecc54e0abc07f479d5eeb390f0614f9484eb) automatically.

2021-02-12 04:43 UTC, kvedala commented
> > changes to the file `pancake_sort.cpp`
> 
> It seems those changes were made by the CI ([caf2ecc](https://github.com/TheAlgorithms/C-Plus-Plus/commit/caf2ecc54e0abc07f479d5eeb390f0614f9484eb)) automatically.

ah, ok

2021-02-12 04:43 UTC, kvedala approved these changes

2021-02-12 04:44 UTC, merged