Create magic_number.cpp
TheAlgorithms/C-Plus-Plus pull request #1318
Opened 2020-10-17 14:01 UTC by neha-hasija17

This Pull Request is for HacktoberFest 2020

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-18 19:43 UTC, Panquesito7 requested changes
👍 Well-written and documented code.
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/neha-hasija17/C-Plus-Plus/actions

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> +void tests() {
```suggestion
static void tests() {
```

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> + * @file magic_number.cpp
```suggestion
 * @file
```

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> + * A number is said to be a magic number, if the sum of its digits are calculated
```suggestion
 *
 * @details
 * A number is said to be a magic number, if the sum of its digits are calculated 
```

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> + * @detail This is a shortcut method to verify Magic Number.
```suggestion
 *
 * This is a shortcut method to verify Magic Number. 
```

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> +
```suggestion
```

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> +/**
```suggestion
/**
 * @namespace math
 * @brief Math algorithms
 */
namespace math {
/**
```

2020-10-18 19:43 UTC, Panquesito7 commented on math/magic_number.cpp
> +}
```suggestion
}
}  // namespace math
```

2020-10-18 20:25 UTC, neha-hasija17 commented
> 👍 Well-written and documented code.
> Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/neha-hasija17/C-Plus-Plus/actions

thankyou sir. please review this.

2020-10-20 06:06 UTC, neha-hasija17 commented
@Panquesito7 please review this. this Pull request is for hacktober fest 2020

2020-10-20 21:31 UTC, Panquesito7 requested changes
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1318/checks?check_run_id=1272084106) warnings.

2020-10-20 21:31 UTC, Panquesito7 commented on math/magic_number.cpp
> +#include <iostream>
```suggestion
#include <cassert>  /// for assert
#include <iostream> /// for io operations
```

2020-10-20 21:31 UTC, Panquesito7 commented on math/magic_number.cpp
> +/** Test function
```suggestion
/**
 * @brief Test function
```

2020-10-20 21:31 UTC, Panquesito7 commented on math/magic_number.cpp
> +    tests();
```suggestion
    tests(); // execute the tests
```

2020-10-20 21:31 UTC, Panquesito7 commented on math/magic_number.cpp
> +/** Main function
```suggestion
/**
 * @brief Main function
```

2020-10-20 21:31 UTC, Panquesito7 commented on math/magic_number.cpp
> + * not. A number is said to be a magic number, if the sum of its digits are
```suggestion
 * not.
 *
 * @details
 * A number is said to be a magic number, if the sum of its digits are
```

2020-10-20 21:31 UTC, Panquesito7 commented on math/magic_number.cpp
> + * sum will be 1, thus verifying that it is a magic number.
```suggestion
 * sum will be 1, thus verifying that it is a magic number.
 *
```

2020-10-20 21:33 UTC, Panquesito7 commented on math/magic_number.cpp
> +}
Not resolved yet (same as above; this is **necessary**).

2020-10-21 05:23 UTC, neha-hasija17 commented
@Panquesito7 why the basic tests are failing? I don't understand this, kindly make the necessary changes so it works well like before.

2020-10-21 16:47 UTC, Panquesito7 commented on math/magic_number.cpp
> +/**
Not resolved yet.

2020-10-21 18:05 UTC, Panquesito7 requested changes

2020-10-21 18:05 UTC, Panquesito7 commented on math/magic_number.cpp
> +    assert(magic_number(60) == false);
```suggestion
    assert(math::magic_number(60) == false);
```

2020-10-21 18:05 UTC, Panquesito7 commented on math/magic_number.cpp
> +    assert(magic_number(730) == true);
```suggestion
    assert(math::magic_number(730) == true);
```

2020-10-21 18:05 UTC, Panquesito7 commented on math/magic_number.cpp
> +    assert(magic_number(0) == false);
```suggestion
    assert(math::magic_number(0) == false);
```

2020-10-21 18:05 UTC, Panquesito7 commented on math/magic_number.cpp
> +    assert(magic_number(479001600) == false);
```suggestion
    assert(math::magic_number(479001600) == false);
```

2020-10-21 18:05 UTC, Panquesito7 commented on math/magic_number.cpp
> +    assert(magic_number(-35) == false);
```suggestion
    assert(math::magic_number(-35) == false);
```

2020-10-23 05:42 UTC, neha-hasija17 commented
@Panquesito7 please have a look

2020-10-23 18:51 UTC, Panquesito7 commented on math/magic_number.cpp
> +/** Main function
```suggestion
/**
 * @brief Main function
```

2020-10-24 05:19 UTC, neha-hasija17 commented
@Panquesito7 Kindly review this.

2020-10-25 19:46 UTC, Panquesito7 commented on math/magic_number.cpp
> +bool magic_number(int n) {
```suggestion
bool magic_number(const uint64_t &n) {
```

2020-10-25 19:46 UTC, Panquesito7 commented on math/magic_number.cpp
> +    int result = n % 9;
```suggestion
    uint64_t result = n % 9;
```

2020-10-27 02:41 UTC, Panquesito7 approved these changes
Neat, code looks pretty well; LGTM. 😄 👍

2020-10-27 17:42 UTC, ayaankhan98 approved these changes
LGTM! 
Thanks for your contribution

2020-10-27 17:42 UTC, merged

2020-10-27 18:01 UTC, Panquesito7 commented
@ayaankhan98 Please use squash-merge. Thank you.