feat: Added Morse Code
TheAlgorithms/C-Plus-Plus pull request #1322
Opened 2020-10-18 08:45 UTC by imdeep2905

#### Description of Change

Added Morse Code as ```ciphers/morse_code.cpp```.

#### Checklist

- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [X] Added tests and example, test must pass
- [X] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

2020-10-18 17:52 UTC, Panquesito7 requested changes
👍 Well written and documented code.

2020-10-18 17:52 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> +void test() {
```suggestion
static void test() {
```

2020-10-18 17:52 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> + * Function to test above algorithm
```suggestion
 * @brief Function to test above algorithm
 * @returns void
```

2020-10-18 17:52 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> +/** Driver Code */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2020-10-18 18:50 UTC, Panquesito7 approved these changes
Amazing work, I like how you've made the code. 😄 👍
Code and documentation is pretty good and refined; LGTM. 🙂

2020-10-18 18:50 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> + * @return morse representation string of character
```suggestion
 * @returns morse representation string of character
```

2020-10-18 18:50 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> + * @return corresponding character
```suggestion
 * @returns corresponding character
```

2020-10-18 18:50 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> + * @return new encrypted text
```suggestion
 * @returns new encrypted text
```

2020-10-18 18:50 UTC, Panquesito7 commented on ciphers/morse_code.cpp
> + * @return new decrypted text
```suggestion
 * @returns new decrypted text
```

2020-10-18 18:58 UTC, imdeep2905 commented
Hey, Any idea why LGTM failed ?
Shows error:
```This pull request can't be analyzed because the requested commit is no longer present in the repository```

2020-10-18 19:11 UTC, Panquesito7 commented
> Hey, Any idea why LGTM failed ?
> Shows error:
> `This pull request can't be analyzed because the requested commit is no longer present in the repository`

When GitHub Actions force-pushed, LGTM couldn't check
the commits (as after every force-push, sometimes commits disappear).

I re-ran the checks, it shall work properly now. 🙂

2020-10-19 21:09 UTC, kvedala approved these changes
👍  Well done

2020-10-19 21:25 UTC, merged