Added cycle_sort.cpp
TheAlgorithms/C-Plus-Plus pull request #1332
Opened 2020-10-18 20:24 UTC by VasuSehgal123

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

2020-10-18 20:29 UTC, Panquesito7 commented
Duplicate of #1252.

2020-10-18 20:30 UTC, Panquesito7 commented
You may want to change the filename to `cycle_sort2.cpp`, as the PR #1252 implements the same algorithm. 🙂

2020-10-18 20:45 UTC, VasuSehgal123 commented
@Panquesito7 Changed  filename from `cycle_sort.cpp` to `cycle_sort2.cpp`

2020-10-18 21:18 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/VasuSehgal123/C-Plus-Plus/actions

2020-10-18 21:18 UTC, Panquesito7 commented on sorting/cycle_sort2.cpp
> + * @see more on [Cycle sort] (https://en.wikipedia.org/wiki/Cycle_sort)
```suggestion
 * @see more on [Cycle sort](https://en.wikipedia.org/wiki/Cycle_sort)
```

2020-10-18 21:18 UTC, Panquesito7 commented on sorting/cycle_sort2.cpp
> + void test() {
```suggestion
 static void test() {
```

2020-10-18 21:18 UTC, Panquesito7 commented on sorting/cycle_sort2.cpp
> +}
```suggestion
}

```

2020-10-18 23:52 UTC, Panquesito7 commented on sorting/cycle_sort2.cpp
> +
```suggestion
```

2020-10-19 21:47 UTC, Panquesito7 commented on sorting/cycle_sort2.cpp
> +    return 0;
```suggestion
   return 0;
```

2020-10-19 21:47 UTC, Panquesito7 commented on sorting/cycle_sort2.cpp
> +   test();
```suggestion
   test();  // execute the tests
```

2020-10-20 21:38 UTC, Panquesito7 approved these changes
Nice work; I like how you've made the code. 😄 👍
Code and documentation is pretty good and refined; LGTM.

2020-10-24 17:34 UTC, VasuSehgal123 commented
Hi @Panquesito7! Directory.md is showing merge conflict after #1252 got merged. Can you do something about it?

2020-10-25 19:39 UTC, Panquesito7 commented
> Can you do something about it?

Merge conflict should be resolved now. 🙂

2021-02-05 09:42 UTC, merged