fix/test/docs: update variable sizes, add namespace and tests
TheAlgorithms/C-Plus-Plus pull request #1335
Opened 2020-10-19 08:24 UTC by sauravUppoor

#### Description of Change

Fixes:

- Added namespace `graph`
- Generalised variable data types from `int` to `size_t`
- Added `addEdge()` function for uniformity with other graph algorithms.

Tests:

- Added 3 test cases.

Docs:

- Added documentation throughout the code.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-19 21:59 UTC, Panquesito7 requested changes
👍 Well done.

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +void tests() {
```suggestion
static void tests() {
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +} /// namespace graph
```suggestion
}  // namespace depth_first_search
}  // namespace graph
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +namespace graph {
```suggestion
/**
 * @namespace graph
 * @brief Graph algorithms
 */
namespace graph {
/**
 * @namespace depth_first_search
 * @brief Functions for [Depth First Search](https://en.wikipedia.org/wiki/Depth-first_search) algorithm
 */
namespace depth_first_search {
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +    tests();
```suggestion
    tests();  // execute the tests
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	graph::addEdge(&g1, 3, 1);
```suggestion
	graph::depth_first_search::addEdge(&g1, 1, 2);
	graph::depth_first_search::addEdge(&g1, 2, 3);
	graph::depth_first_search::addEdge(&g1, 3, 1);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	assert(graph::dfs(g1, start_pos - 1) == expected1);
```suggestion
	assert(graph::depth_first_search::dfs(g1, start_pos - 1) == expected1);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	graph::addEdge(&g2, 4, 1);
```suggestion
	graph::depth_first_search::addEdge(&g2, 1, 2);
	graph::depth_first_search::addEdge(&g2, 1, 3);
	graph::depth_first_search::addEdge(&g2, 2, 4);
	graph::depth_first_search::addEdge(&g2, 4, 1);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	assert(graph::dfs(g2, start_pos - 1) == expected2);
```suggestion
	assert(graph::depth_first_search::dfs(g2, start_pos - 1) == expected2);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	graph::addEdge(&g3, 4, 1);
```suggestion
	graph::depth_first_search::addEdge(&g3, 1, 2);
	graph::depth_first_search::addEdge(&g3, 1, 3);
	graph::depth_first_search::addEdge(&g3, 2, 4);
	graph::depth_first_search::addEdge(&g3, 4, 1);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	assert(graph::dfs(g3, start_pos - 1) == expected3);
```suggestion
	assert(graph::depth_first_search::dfs(g3, start_pos - 1) == expected3);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +		graph::addEdge(&adj, u, v);
```suggestion
		graph::depth_first_search::addEdge(&adj, u, v);
```

2020-10-19 21:59 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +	traversal = graph::dfs(adj, start_pos);
```suggestion
	traversal = graph::depth_first_search::dfs(adj, start_pos);
```

2020-10-20 04:14 UTC, sauravUppoor commented
@Panquesito7 Thanks a lot for going through the code. I have committed the suggested changes. 😄

2020-10-20 21:42 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +#include <limits>
Add a brief description of what the header/library add (see the examples below).
```suggestion
#include <iostream>  /// for io operations
#include <list>     ///
#include <stack>    ///
#include <vector>  /// for std::vector
#include <cassert>  /// for assert
#include <limits>   ///
```

2020-10-21 07:49 UTC, sauravUppoor commented
@Panquesito7 I have added a short description for the header files.

2020-10-21 16:33 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> +#include <limits> /// header for limits of integral types
```suggestion
#include <iostream> /// for IO operations
#include <stack>    /// header for std::stack
#include <vector>   /// header for std::vector
#include <cassert>  /// header for preprocessor macro assert() 
#include <limits>   /// header for limits of integral types
```

2020-10-21 16:33 UTC, Panquesito7 commented on graph/depth_first_search_with_stack.cpp
> + * Self-test implementation
```suggestion
 * Self-test implementations
```

2020-10-21 17:08 UTC, Panquesito7 approved these changes
Amazing work, I like how you've improved the code so well.
Code and documentation looks good and very refined; LGTM. 😄 👍

2020-10-21 19:05 UTC, ayaankhan98 approved these changes
LGTM

2021-02-05 10:07 UTC, merged