Add Gram Schmidt Orthogonalisation
TheAlgorithms/C-Plus-Plus pull request #1339
Opened 2020-10-19 12:29 UTC by Akanksha-Gupta920

#### Description of Change

Added code for Gram Schmidt Orthogonalisation.

2020-10-19 12:42 UTC, Akanksha-Gupta920 commented
The code takes vectors in Rn and gives the vectors in orthogonal to each other.

2020-10-19 12:44 UTC, Akanksha-Gupta920 commented
Gram Schmidt Process for Orthogonalising vectors in Rn

2020-10-19 21:36 UTC, Panquesito7 requested changes
Documentation is not up to the [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html).
Please read them **carefully** and **follow them**.

2020-10-20 10:40 UTC, Akanksha-Gupta920 commented
Can you elaborate on documentation? Have done the changes multiple times but didn't get what should be done.

2020-10-20 15:06 UTC, Akanksha-Gupta920 commented
Kindly elaborate on documentation. Have done changes multiple times but not getting what's the problem.

2020-10-20 18:46 UTC, xgupta commented
@Akanksha-Gupta920  See the typical structure of the program https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program to get an idea of what is missing. 

You have to write @file, @breif, @ detail, @param, @tparam, @return, etc in form of Doxygen comments.

2020-10-21 05:44 UTC, Akanksha-Gupta920 reviewed
Have done the recommended changes.

2020-10-21 16:28 UTC, Panquesito7 requested changes

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> + * @file   Created by akanksha gupta on 02/10/20.
```suggestion
 * @file
```

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> + * @param y
Missing parameter brief description.

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> + * @param c
Same here as above.

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
>   * Main Function
```suggestion
 * @brief Main Function
 * @returns 0 on exit
```

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
```suggestion
```

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  test(); //perform self tests
```suggestion
  test(); // perform self tests
```

2020-10-21 16:28 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> + *@returns dot_product
This seems to be incorrect.

2020-10-21 23:37 UTC, Akanksha-Gupta920 commented
Have done the recommended changes. 

Need to use vectors (in math) stored in array multiple times, first called in gram_schimdt function, then in projection function and finally in dot_product function and later also used in display function, which necessitates the use of call by reference. Using call by address makes it difficult to use those arrays, complicating the program

2020-10-21 23:40 UTC, Panquesito7 requested changes
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/runs/1289692520) warnings.

2020-10-21 23:45 UTC, Akanksha-Gupta920 commented
Warnings are related to the parameters I have passed. If I pass the parameters without & checks are passed but in the program, the change in the output is not reflected. Kindly guide what should I do.

2020-10-21 23:58 UTC, Panquesito7 requested changes

2020-10-21 23:58 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> + *@returns sum
```suggestion
 * @returns sum
```

2020-10-21 23:58 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +double dot_product(std::array<double, 10> x, std::array<double, 10> y, int c) {
```suggestion
double dot_product(const std::array<double, 10>& x, const std::array<double, 10>& y, int c) {
```

2020-10-21 23:58 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +void projection(std::array<double, 10> x, std::array<double, 10> y,
```suggestion
void projection(const std::array<double, 10>& x, std::array<double, 10> y,
```

2020-10-21 23:58 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +void display(int r, int c, std::array<std::array<double, 10>, 20> B) {
```suggestion
void display(const int& r, const int& c, const std::array<std::array<double, 10>, 20>& B) {
```

2020-10-21 23:58 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +void gram_schmidt(int r, int c, std::array<std::array<double, 10>, 20> A,
```suggestion
void gram_schmidt(int r, const int& c, const std::array<std::array<double, 10>, 20>& A,
```

2020-10-22 00:11 UTC, Akanksha-Gupta920 commented
The requested changes have been done. Still, the changes in array B are not reflected.

2020-10-22 00:45 UTC, Akanksha-Gupta920 commented
After doing the requested suggestions, changes in array B still not reflected. In array, B orthogonalized vectors are stored. So the dot product of any two vectors should be zero. But in B it showing whatever was in array A. Kindly guide about this.

2020-10-22 01:14 UTC, Panquesito7 requested changes

2020-10-22 01:14 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      A;  ///a 2-D array for storing all vectors
```suggestion
      A{};  ///a 2-D array for storing all vectors
```

2020-10-22 01:14 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      std::array<double, 10> all_projection;  ///array to store projections
```suggestion
      std::array<double, 10> all_projection{};  ///array to store projections
```

2020-10-22 01:14 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +        std::array<double, 10> temp; ///to store previous projected array
```suggestion
        std::array<double, 10> temp{}; ///to store previous projected array
```

2020-10-22 01:14 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +       double dot1;
```suggestion
       double dot1 = 0;
```

2020-10-22 01:14 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  double dot2;
```suggestion
  double dot2 = 0;
```

2020-10-22 01:29 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Akanksha-Gupta920/C-Plus-Plus/actions

2020-10-22 01:40 UTC, Panquesito7 commented
Good work. Now, to trigger the GitHub Actions, make a small commit.
Next, we shall see a commit by GitHub Actions updating `DIRECTORY.md`. 🙂

2020-10-22 17:21 UTC, Akanksha-Gupta920 commented
What further should be done? 


> Good work. Now, to trigger the GitHub Actions, make a small commit.
> Next, we shall see a commit by GitHub Actions updating `DIRECTORY.md`. 🙂

2020-10-22 18:08 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +#include <array>
Add a brief description of what `cmath` is added (see the other examples).
```suggestion
#include <iostream>  /// for io operations
#include <cassert>  /// for assert
#include <cmath>   ///
#include <array>  /// for std::array
```

2020-10-22 19:45 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +#include <array>    /// for std::array
```suggestion
#include <iostream>    /// for io operations
#include <cassert>     /// for assert
#include <cmath>       /// for fabs
#include <array>       /// for std::array
```

2020-10-22 19:49 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +#include <cassert>     /// for assert
```suggestion
#include <cassert>      /// for assert
```

2020-10-22 19:49 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +
```suggestion
```

2020-10-22 19:55 UTC, Akanksha-Gupta920 commented
If all the required changes are done. Can it be merged now?

2020-10-22 20:00 UTC, Panquesito7 requested changes

2020-10-22 20:13 UTC, Akanksha-Gupta920 commented on linear_algebra/gram_schmidt.cpp
> +/**
Can you elaborate on this?

2020-10-22 20:19 UTC, Akanksha-Gupta920 commented on linear_algebra/gram_schmidt.cpp
> +/**
Since now PR run is failing. Don't know where is the problem occurring

2020-10-22 21:00 UTC, Akanksha-Gupta920 commented
Have done the recommended changes but now the PR is failing. Kindly guide.

2020-10-22 21:09 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> + * @brief [Gram Schmidt Orthogonalisation Process] (https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)
```suggestion
 * @brief [Gram Schmidt Orthogonalisation Process](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)
```

2020-10-22 21:09 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      dot = fabs(dot_product(B[i], B[j], c));
```suggestion
      dot = fabs(linear_algebra::gram_schmidtdot_product(B[i], B[j], c));
```

2020-10-22 21:17 UTC, Panquesito7 requested changes

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +        double factor; ///to store the factor by which the previous array will change
```suggestion
        double factor = 0; ///to store the factor by which the previous array will change 
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +         temp[i] = B[l - 1][i] * factor;  ///projected array created
```suggestion
        for (int i = 0; i < c; i++) {
            temp[i] = B[l - 1][i] * factor;  ///projected array created
        }
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  gram_schmidt(3, 4, a1, b1);
```suggestion
  linear_algebra::gram_schmidt::gram_schmidt(3, 4, a1, b1);
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  gram_schmidt(2, 2, a2, b2);
```suggestion
  linear_algebra::gram_schmidt::gram_schmidt(2, 2, a2, b2);
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      dot2 = fabs(dot_product(b2[i], b2[j], 2));
```suggestion
      linear_algebra::gram_schmidt::dot2 = fabs(dot_product(b2[i], b2[j], 2));
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  gram_schmidt(2, 3, a3, b3);
```suggestion
  linear_algebra::gram_schmidt::gram_schmidt(2, 3, a3, b3);
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      dot3 = fabs(dot_product(b3[i], b3[j], 3));
```suggestion
      dot3 = fabs(linear_algebra::gram_schmidt::dot_product(b3[i], b3[j], 3));
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      dot = fabs(linear_algebra::gram_schmidtdot_product(B[i], B[j], c));
```suggestion
      dot = fabs(linear_algebra::gram_schmidt::dot_product(B[i], B[j], c));
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  gram_schmidt(r, c, A, B);
```suggestion
  linear_algebra::gram_schimdt::gram_schmidt(r, c, A, B);
```

2020-10-22 21:17 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +      dot1 = fabs(dot_product(b1[i], b1[j], 4));
```suggestion
      dot1 = fabs(linear_algebra::gram_schmidt::dot_product(b1[i], b1[j], 4));
```

2020-10-22 21:20 UTC, Panquesito7 requested changes

2020-10-22 21:20 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  int r, c;
```suggestion
  int r = 0, c = 0;
```

2020-10-22 21:20 UTC, Panquesito7 commented on linear_algebra/gram_schmidt.cpp
> +  linear_algebra::gram_schmidt(r, c, A, B);
```suggestion
  linear_algebra::gram_schmidt::gram_schmidt(r, c, A, B);
```

2020-10-22 21:26 UTC, Panquesito7 approved these changes
Awesome work, code and documentation looks pretty well. 😄 👍

2020-10-23 19:34 UTC, Akanksha-Gupta920 commented
Kindly review it.

2020-10-23 19:43 UTC, Panquesito7 commented
> Kindly review it.

Please be patient. It may take a day or more for @kvedala to review it.
Until he has free time, he shall have received a notification. He will review this when he can.

2020-10-23 20:01 UTC, Akanksha-Gupta920 commented
> > Kindly review it.
> 
> Please be patient. It may take a day or more for @kvedala to review it.
> Until he has free time, he shall have received a notification. He will review this when he can.

Sure, thank you! :)

2020-10-26 19:34 UTC, Akanksha-Gupta920 commented
A gentle reminder to review it.

2020-10-27 18:00 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> + * Keep repeating hte above process until all the vectors in the given input array are exhausted.
```suggestion
 * Keep repeating the above process until all the vectors in the given input array are exhausted. 
```

2020-10-27 18:03 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> + * @brief [Gram Schmidt Orthogonalisation Process] (https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)
```suggestion
 * @brief [Gram Schmidt Orthogonalisation Process](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)
```

2020-10-27 18:03 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> + * @brief Functions for [Gram Schmidt Orthogonalisation Process] (https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)
```suggestion
 * @brief Functions for [Gram Schmidt Orthogonalisation Process](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)
```

2020-10-27 18:09 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +    std::cout << std::endl;
```suggestion
    std::cout << '\n';
```

2020-10-27 18:10 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +    std::cout << std::endl;
It does not seems reasonable to flush buffer here, so it's good to not to use `std::endl`;
hope this makes sense

2020-10-27 18:10 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +        << c << " vectors are orthogonalised" << std::endl;
```suggestion
        << c << " vectors are orthogonalised\n";
```

2020-10-27 18:12 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +  for (int i = 0; i < c; i++) {
```suggestion
  for (int i = 0; i < c; ++i) {
```

2020-10-27 18:13 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +  for (int i = 0; i < r; i++) {
```suggestion
  for (int i = 0; i < r; ++i) {
```

2020-10-27 18:13 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +    for (int j = 0; j < c; j++) {
```suggestion
    for (int j = 0; j < c; ++j) {
```

2020-10-27 18:13 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +      for (int i = 0; i < c; i++) {
```suggestion
      for (int i = 0; i < c; ++i) {
```

2020-10-27 18:13 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +        for(int i = 0; i < c; i++)
```suggestion
        for(int i = 0; i < c; ++i)
```

2020-10-27 18:14 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +        for (int j = 0; j < c; j++) {
```suggestion
        for (int j = 0; j < c; ++j) {
```

2020-10-27 18:14 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +      for (int i = 0; i < c; i++) {
```suggestion
      for (int i = 0; i < c; ++i) {
```

2020-10-27 18:15 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +  for (int i = 0; i < r; i++) {
```suggestion
  for (int i = 0; i < r; ++i) {
```

2020-10-27 18:16 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +    for (int j = 0; j < c; j++) {
```suggestion
    for (int j = 0; j < c; ++j) {
```

2020-10-27 18:16 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +  for (int i = 0; i < r - 1; i++) {
```suggestion
  for (int i = 0; i < r - 1; ++i) {
```

2020-10-27 18:16 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +    for (int j = i + 1; j < r; j++) {
```suggestion
    for (int j = i + 1; j < r; ++j) {
```

2020-10-27 18:18 UTC, ayaankhan98 commented on linear_algebra/gram_schmidt.cpp
> +  if (flag == 0) std::cout << "Vectors are linearly dependent " << std::endl;
```suggestion
  if (flag == 0) std::cout << "Vectors are linearly dependent\n";
```

2020-10-27 18:48 UTC, Akanksha-Gupta920 reviewed
Suggested Changes have been made.

2020-10-29 13:02 UTC, Akanksha-Gupta920 commented
Kindly review it.

2020-10-30 18:13 UTC, Akanksha-Gupta920 commented
@ayaankhan98 Kindly review it.

2020-10-30 18:15 UTC, Akanksha-Gupta920 commented
> @ayaankhan98 Kindly review it.

If everything is fine. Kindly merge this.

2020-10-31 06:37 UTC, ayaankhan98 approved these changes
LGTM! Thanks for your contribution.

2020-10-31 06:37 UTC, merged

2020-10-31 07:13 UTC, Akanksha-Gupta920 commented
Thank you!