fix: Issue in list_array.cpp resolved
TheAlgorithms/C-Plus-Plus pull request #1342
Opened 2020-10-19 17:51 UTC by sagarpandyansit

#### Issue that resolved
https://github.com/TheAlgorithms/C-Plus-Plus/issues/1338
#### Description of Change
- Before there is no code written in the list of operations to exit from the infinite while loop.
- I added the exit code in the list.
- I added appropriate comment for the list.

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-19 21:27 UTC, Panquesito7 requested changes
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1342/checks?check_run_id=1276731205) warnings.

2020-10-20 21:24 UTC, Panquesito7 requested changes

2020-10-20 21:24 UTC, Panquesito7 commented on data_structures/list_array.cpp
> +}
```suggestion
}

```

2020-10-21 15:59 UTC, Panquesito7 reviewed
We can take the opportunity to add proper documentation and refined code. 🙂
Confused? See the [typical structure](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program or see #962.

2020-10-21 16:53 UTC, sagarpandyansit commented
@Panquesito7 Actually, this branch got some issues, that's why I had made another branch and started work on the refinement of code already.
Can you please merge this pull request? I will make another pull request with the documentation and refined code shortly. Thanks.

2020-10-21 17:03 UTC, Panquesito7 approved these changes
LGTM; good work. 😄👍

2020-10-22 17:40 UTC, merged