Added LRU Cache Data Structure
TheAlgorithms/C-Plus-Plus pull request #1356
Opened 2020-10-20 20:48 UTC by proRamLOGO

#### Description 
Code for LRU Cache Data Structure has been added to the data structures folder. LRU Cache has been implemented using a circular doubly linked list.
#### Checklist

- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

2020-10-20 21:27 UTC, Panquesito7 requested changes
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/runs/1283307334) warnings.

2020-10-20 21:27 UTC, Panquesito7 commented on data_structures/LRUCache.cpp
> + * math equations, etc
```suggestion
```

2020-10-20 21:27 UTC, Panquesito7 commented on data_structures/LRUCache.cpp
> + * @see
```suggestion
```

2020-10-20 21:27 UTC, Panquesito7 commented on data_structures/LRUCache.cpp
> +#include <cassert>
```suggestion
#include <iostream>  /// for io operations
#include <unordered_map> // For hashmap
#include <cassert>  /// for assert
```

2020-10-21 08:19 UTC, proRamLOGO reviewed
If key requested is not present in LRU Cache function get will return -1.

2020-10-21 08:34 UTC, proRamLOGO commented
It is workin fine now. Moderator pls check

2020-10-22 08:46 UTC, proRamLOGO commented
@Panquesito7 my code is working fine on ubuntu and macOS but not on windows-latest. Pls tell what should I do now ?

2020-10-22 16:37 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/proRamLOGO/C-Plus-Plus/actions

2020-10-22 16:37 UTC, Panquesito7 commented on data_structures/LRUCache.cpp
> +#include <cassert>  /// for assert
```suggestion
#include <iostream>      /// for io operations
#include <unordered_map> /// for hashmap
#include <cassert>       /// for assert
```

2020-10-22 18:23 UTC, proRamLOGO commented
> Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/proRamLOGO/C-Plus-Plus/actions

Done ENABLED

2020-10-22 18:32 UTC, Panquesito7 commented
Good work. Now, to trigger the GitHub Actions, make a small commit.
Next, we shall see a commit made by GitHub Actions updating `DIRECTORY.md`. 🙂

2020-10-22 19:33 UTC, Panquesito7 requested changes
Good work on updating the code. 👍
Please change the file name to `lru_cache.cpp`.

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> + * @brief Implementation of LRU Cache Data Structure
```suggestion
 * @brief Implementation of [LRU Cache Data](https://www.geeksforgeeks.org/lru-cache-implementation/) Structure
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> + * Class node
```suggestion
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> + * Class node to build up and implement doubly circular linked lists
```suggestion
 * @brief Class node to build up and implement doubly circular linked lists
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> +/**
```suggestion
/**
 * @namespace data_structures
 * @brief Algorithms with data structures
 */
namespace data_structures {
/**
 * @namespace lru_cache
 * @brief Functions for [Least Recently Used Cache](https://www.geeksforgeeks.org/lru-cache-implementation/) implementation
 */
namespace lru_cache {
/**
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> +};
```suggestion
};
}  // namespace lru_cache
}  // namespace data_structures
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> +    LRUCache lru(2); ///< Created a new LRUCache instace of physical size 2.
```suggestion
    data_structures::lru_cache::LRUCache lru(2); ///< Created a new LRUCache instace of physical size 2.
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> +    * @param val : Value
What do these parameters do? Document it here (in the code).

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> +    * @param key : value for this key is to be returned.
```suggestion
    * @param key value for this key is to be returned.
```

2020-10-22 19:33 UTC, Panquesito7 commented on data_structures/lrucache.cpp
> +    * @param value : Value for the respective key to be stored.
```suggestion
    * @param key the key to be added or updated.
    * @param value value for the respective key to be stored.
```

2020-10-22 19:50 UTC, Panquesito7 reviewed
Please change the file name to `lru_cache.cpp`.

2020-10-23 19:11 UTC, proRamLOGO commented
> Good work on updating the code. 👍
> Please change the file name to `lru_cache.cpp`.

Done

2020-10-23 19:16 UTC, Panquesito7 requested changes
Good work. 👍

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> + * Class node to build up and implement doubly circular linked lists
```suggestion
 * @brief Class node to build up and implement doubly circular linked lists
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> + * Class node
```suggestion
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    node(int key, int val) {
```suggestion
    node(uint64_t key, uint64_t val) {
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    int val;  ///< Variable to contain value of {value} associated with {key}
```suggestion
    uint64_t key = 0;  ///< Variable to contain value of {key}
    uint64_t val = 0;  ///< Variable to contain value of {value} associated with {key}
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +     * @returns NOTHING
```suggestion
     * @returns nothing
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    explicit LRUCache(int capacity) {
```suggestion
    explicit LRUCache(const uint64_t& capacity) {
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +     * @returns NOTHING
This function **does** return something.
Please document it well, make it understandable.

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    int get(int key) {
```suggestion
    uint64_t get(uint64_t key) {
```

2020-10-23 19:16 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    void put(int key, int value) {
```suggestion
    void put(uint64_t key, const uint64_t& value) {
```

2020-10-23 22:20 UTC, Panquesito7 requested changes

2020-10-23 22:20 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    node(int key, int val) {
```suggestion
    node(uint64_t key, uint64_t val) {
```

2020-10-23 22:20 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    explicit LRUCache(int capacity) {
```suggestion
    explicit LRUCache(const uint64_t& capacity) {
```

2020-10-23 22:20 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    int get(int key) {
```suggestion
    int get(uint64_t key) {
```

2020-10-24 10:54 UTC, proRamLOGO commented
Up-to-date

2020-10-25 15:40 UTC, proRamLOGO commented
@Panquesito7 please review.

2020-10-25 17:46 UTC, Panquesito7 requested changes

2020-10-25 17:46 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    int get(uint64_t key) {
```suggestion
    uint64_t get(uint64_t key) {
```

2020-10-25 18:54 UTC, Panquesito7 commented
https://github.com/TheAlgorithms/C-Plus-Plus/pull/1356#discussion_r511094070

2020-10-26 05:28 UTC, proRamLOGO commented
> [#1356 (comment)](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1356#discussion_r511094070)

Done

2020-10-26 19:28 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    std::unordered_map<int, node *> addr;
```suggestion
    std::unordered_map<uint64_t, node *> addr;
```

2020-10-26 19:28 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    uint64_t get(uint64_t key) {
```suggestion
    uint64_t get(const uint64_t& key) {
```

2020-10-26 19:28 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    void put(uint64_t key, const uint64_t &value) {
```suggestion
    void put(const uint64_t& key, const uint64_t &value) {
```

2020-10-26 19:28 UTC, Panquesito7 commented on data_structures/lru_cache.cpp
> +    node(uint64_t key, uint64_t val) {
```suggestion
    node(const uint64_t& key, const uint64_t& val) {
```

2020-10-27 19:11 UTC, Panquesito7 reviewed
👍 Please add self-tests to ensure the algorithm works as excepted.

2020-10-27 19:58 UTC, proRamLOGO commented
> 👍 Please add self-tests to ensure the algorithm works as excepted.

Already added.

2020-10-27 20:00 UTC, Panquesito7 commented
See the [typical structure](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program for how to add self-test cases.

2020-10-29 19:00 UTC, closed without merging