feat: add sum_of_binomial_coefficients
TheAlgorithms/C-Plus-Plus pull request #1363
Opened 2020-10-21 08:35 UTC by muskan0719

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-21 16:12 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/muskan0719/C-Plus-Plus/actions

2020-10-21 16:12 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +#include<cassert>  /// for assert
```suggestion
#include <iostream> /// for std::cin and std::cout
#include <cassert>  /// for assert

```

2020-10-21 16:12 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +	return 0;
```suggestion
    return 0;
```

2020-10-21 16:12 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +/**
```suggestion
/**
 * @namespace math
 * @brief Mathematical algorithms
 */
namespace math {
/** 
```

2020-10-21 16:12 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +}
```suggestion
}
}  // namespace math
```

2020-10-21 16:12 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +	return (1 << n);
```suggestion
    // Calculating 2^n  
    return (1 << n); 
```

2020-10-21 16:52 UTC, Panquesito7 requested changes

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> + * @author muskan0719 [https://github.com/muskan0719]
```suggestion
 * @author [muskan0719](https://github.com/muskan0719)
```

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +/**
```suggestion
/**
 * @namespace math
 * @brief Mathematical algorithms
 */
namespace math {
/**
```

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +    int test_case_1 = binomialCoeffSum(2);
```suggestion
    int test_case_1 = math::binomialCoeffSum(2);

```

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +    int test_case_2 = binomialCoeffSum(3);
```suggestion
    int test_case_2 =  math::binomialCoeffSum(3);

```

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +    int test_case_3 = binomialCoeffSum(4);
```suggestion
    int test_case_3 =  math::binomialCoeffSum(4);

```

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +    int test_case_4 = binomialCoeffSum(5);
```suggestion
    int test_case_4 =  math::binomialCoeffSum(5);

```

2020-10-21 16:52 UTC, Panquesito7 commented on math/sum_of_binomial_coefficient.cpp
> +    int test_case_5 = binomialCoeffSum(7);
```suggestion
    int test_case_5 =  math::binomialCoeffSum(7);

```

2020-10-21 19:02 UTC, Panquesito7 approved these changes
Nice work; LGTM. 😄 👍

2020-10-27 20:46 UTC, muskan0719 commented
@kvedala please review this.

2020-10-28 00:58 UTC, ayaankhan98 commented on math/sum_of_binomial_coefficient.cpp
> +	int binomialCoeffSum(int n)
```suggestion
	uint64_t binomialCoeffSum(uint64_t n) 
```
as `n >= 0` always

2020-10-28 08:53 UTC, ayaankhan98 approved these changes
LGTM! Thanks for your contribution @muskan0719

2020-10-28 08:53 UTC, merged