[DOCS][TEST] Documentation and test in the list_array.cpp
TheAlgorithms/C-Plus-Plus pull request #1375
Opened 2020-10-22 12:06 UTC by sagarpandyansit

#### Issue that resolved
https://github.com/TheAlgorithms/C-Plus-Plus/issues/1373

#### Description of Change
- Documentation added.
- Wrote the test cases for all the methods with edge cases.
- Fixed the bugs in various methods.
- Refined the code.
- Efficiency improved.

#### Checklist

- [x] Added description of change
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-22 17:45 UTC, Panquesito7 requested changes
Please resolve the [merge conflicts](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1375/conflicts).

2020-10-23 19:01 UTC, Panquesito7 requested changes
Well-done, nice work. 👍

2020-10-23 19:01 UTC, Panquesito7 commented on data_structures/list_array.cpp
> +    test();
```suggestion
    test();  // execute the tests
```

2020-10-23 19:02 UTC, Panquesito7 commented on data_structures/list_array.cpp
> +#include <cassert>
```suggestion
#include <iostream>   /// for io operations
#include <array>      /// for std::array
#include <cassert>   /// for assert
```

2020-10-24 04:51 UTC, sagarpandyansit commented on data_structures/list_array.cpp
> +    int BinarySearch(const std::array<int, 50>& dataArr, int first, int last, int val) {
@Panquesito7, Thanks for valuable suggestions but, the value should not be unsigned as the array(data) might contain negative values.

2020-10-25 23:31 UTC, Panquesito7 requested changes

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
> +#include <cassert> // for assert
```suggestion
#include <iostream> /// for io operations
#include <array>   /// for std::array
#include <cassert> /// for assert
```

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
> +    int BinarySearch(const std::array<int, 50>& dataArr, const uint64_t& first, const uint64_t& last, const int& val) {
Consider using `uint64_t` rather than `int` (same in other parts of the code).

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
>   * @file list_array.cpp
```suggestion
 * @file
```

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
> + * @brief Implementation of list_array
Provide a Wikipedia link in Markdown format (if available/possible).
If there's no Wikipedia link, add another web source for algorithm explanation. 🙂

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
> +/**
```suggestion
/**
 * @namespace data_structures
 * @brief Algorithms with data structures
 */
namespace data_structures {
/**
 * @namespace list_array
 * @brief Functions for List Array algorithm
 */
namespace list_array {
/**
```

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
>  };
```suggestion
};
}  // namespace list_array
}  // namespace data_structures

```

2020-10-25 23:31 UTC, Panquesito7 commented on data_structures/list_array.cpp
>      list L;
```suggestion
    data_structures::list_array::list L;
```

2020-10-26 18:52 UTC, Panquesito7 commented on data_structures/list_array.cpp
> + * @brief Functions for List Array algorithm
```suggestion
 * @brief Functions for [Dynamic Array](https://en.wikipedia.org/wiki/Dynamic_array) algorithm
```

2020-10-28 21:11 UTC, Panquesito7 approved these changes
Awesome work, I like how you've improved the code so well.
Code and documentation looks good and very refined; LGTM. 😄 👍

2021-02-05 09:47 UTC, kvedala approved these changes
👍

2021-02-05 10:05 UTC, merged