feat: Added bit manipulation algorithms.
TheAlgorithms/C-Plus-Plus pull request #1376
Opened 2020-10-22 18:41 UTC by ravibitsgoa

#### Description of Change
Added bit manipulation algorithms: hamming distance, power of 2, swapping numbers using xor.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

2020-10-22 19:41 UTC, Panquesito7 requested changes
It is recommended to make one PR per file.
This will make the review process much more faster.

2020-10-23 15:02 UTC, ravibitsgoa commented
> It is recommended to make one PR per file.
> This will make the review process much more faster.

Done.

2020-10-23 18:03 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/ravibitsgoa/C-Plus-Plus/actions

2020-10-23 18:03 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +}
```suggestion
}

```

2020-10-23 18:03 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +int main() {
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2020-10-23 18:03 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +unsigned int bitCount(unsigned int value) {
It's better to use `uint64_t`, it's securer and better than `int` (check other parts of the code).

2020-10-23 18:03 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +unsigned int bitCount(unsigned int value) {
Missing function documentation (this is **necessary** and **required**).
See the [typical structure](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program for more information. 🙂

2020-10-23 18:03 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +unsigned int hamming_distance(int a, int b) {
Missing function documentation.

2020-10-25 23:19 UTC, Panquesito7 requested changes

2020-10-25 23:19 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +#include <iostream>  /// for io operations
```suggestion
#include <cassert>   /// for assert
#include <iostream>  /// for io operations
```

2020-10-25 23:19 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +/**
```suggestion
/**
 * @namespace bit_manipulation
 * @brief Bit Manipulation algorithms
 */
namespace bit_manipulation {
/**
```

2020-10-25 23:19 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +uint64_t hamming_distance(uint64_t a, uint64_t b) { return bitCount(a ^ b); }
```suggestion
uint64_t hamming_distance(uint64_t a, uint64_t b) { return bitCount(a ^ b); }
}  // namespace bit_manipulation
```

2020-10-25 23:19 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +    assert(hamming_distance(11, 0) == 3);
```suggestion
    assert(bit_manipulation::hamming_distance(11, 2) == 2);
    assert(bit_manipulation::hamming_distance(2, 0) == 1);
    assert(bit_manipulation::hamming_distance(11, 0) == 3);
```

2020-10-25 23:19 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +    test();
```suggestion
    test();  // execute the tests
```

2020-10-25 23:19 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +              << hamming_distance(a, b) << std::endl;
```suggestion
              << bit_manipulation::hamming_distance(a, b) << std::endl;
```

2020-10-26 03:22 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> + * @file hamming_distance.cpp
```suggestion
 * @file
```

2020-10-27 05:00 UTC, Panquesito7 approved these changes
Good work, thank you for your contribution! 😄 👍

2020-10-28 11:31 UTC, ravibitsgoa commented
Hi @ayaankhan98 can you please review this PR and merge if found proper?

2020-10-28 17:06 UTC, ayaankhan98 reviewed
@ravibitsgoa we can have more generalized version of this algorithm, to consider strings also.

2020-10-28 17:10 UTC, ravibitsgoa commented
> @ravibitsgoa we can have more generalized version of this algorithm, to consider strings also.

Yes, I can add a method for strings too. But the same method cannot accommodate strings right?

2020-10-28 17:26 UTC, ayaankhan98 commented
> > @ravibitsgoa we can have more generalized version of this algorithm, to consider strings also.
> 
> Yes, I can add a method for strings too. But the same method cannot accommodate strings right?
> Also, by strings, you mean hamming_distance("1111", "1101") == 1 right?

That's great, please do the implementation for strings too; A quick thought i have is you can use template specilization to achieve this for both strings and integers;
And yes you are right hamming distance for the above proposed strings is 1.

2020-10-28 20:50 UTC, Panquesito7 requested changes

2020-10-28 20:50 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +namespace bit_manipulation {
```suggestion
namespace bit_manipulation {
/**
 * @namespace hamming_distance
 * @brief Functions for [Hamming
 * distance](https://en.wikipedia.org/wiki/Hamming_distance) implementation
 */
namespace hamming_distance {
```

2020-10-28 20:50 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +
```suggestion
}  // namespace hamming_distance
```

2020-10-28 20:50 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +    assert(bit_manipulation::hamming_distance(11, 0) == 3);
```suggestion
    assert(bit_manipulation::hamming_distance::hamming_distance(11, 2) == 2);
    assert(bit_manipulation::hamming_distance::hamming_distance(2, 0) == 1);
    assert(bit_manipulation::hamming_distance::hamming_distance(11, 0) == 3);
```

2020-10-28 20:50 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +    assert(bit_manipulation::hamming_distance("0000", "1111") == 4);
```suggestion
    assert(bit_manipulation::hamming_distance::hamming_distance("1101", "1111") == 1);
    assert(bit_manipulation::hamming_distance::hamming_distance("1111", "1111") == 0);
    assert(bit_manipulation::hamming_distance::hamming_distance("0000", "1111") == 4);
```

2020-10-28 20:50 UTC, Panquesito7 commented on bit_manipulation/hamming_distance.cpp
> +              << bit_manipulation::hamming_distance(a, b) << std::endl;
```suggestion
              << bit_manipulation::hamming_distance::hamming_distance(a, b) << std::endl;
```

2020-10-29 09:19 UTC, ayaankhan98 commented
> > > @ravibitsgoa we can have more generalized version of this algorithm, to consider strings also.
> > 
> > 
> > Yes, I can add a method for strings too. But the same method cannot accommodate strings right?
> > Also, by strings, you mean hamming_distance("1111", "1101") == 1 right?
> 
> That's great, please do the implementation for strings too; A quick thought i have is you can use template specilization to achieve this for both strings and integers;
> And yes you are right hamming distance for the above proposed strings is 1.

This time i am mentioning this more explicitly by strings i mean all possible strings not just only binary strings.
consider alphabetical strings too.
```"cathy", "kathy" -> 1```

2020-10-31 08:46 UTC, ravibitsgoa commented
> > > > @ravibitsgoa we can have more generalized version of this algorithm, to consider strings also.
> > > 
> > > 
> > > Yes, I can add a method for strings too. But the same method cannot accommodate strings right?
> > > Also, by strings, you mean hamming_distance("1111", "1101") == 1 right?
> > 
> > 
> > That's great, please do the implementation for strings too; A quick thought i have is you can use template specilization to achieve this for both strings and integers;
> > And yes you are right hamming distance for the above proposed strings is 1.
> 
> This time i am mentioning this more explicitly by strings i mean all possible strings not just only binary strings.
> consider alphabetical strings too.
> `"cathy", "kathy" -> 1`

Done.

2020-11-02 00:10 UTC, Panquesito7 approved these changes

2021-02-17 02:38 UTC, ayaankhan98 approved these changes

2021-02-17 02:38 UTC, merged