largest_power
TheAlgorithms/C-Plus-Plus pull request #1406
Opened 2020-10-28 14:57 UTC by uday6670

#### Adding a code

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-30 22:15 UTC, Panquesito7 requested changes
👍 Well done!

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +
```suggestion
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	return 0;
```suggestion
    test(); // execute the tests
    return 0;
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	 */
```suggestion
	/** 
	 * @brief Function to calculate largest power
	 * @param n number
         * @param p prime number
	 * @returns largest power
	 */ 
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +    int largestPower(int n, int p)
```suggestion
    uint64_t largestPower(uint32_t n, const uint16_t& p)  
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> + * Function for testing largestPower function.
```suggestion
 * @brief Function for testing largestPower function.
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	int test_case_1 = math::largestPower(5,2);
```suggestion
	uint8_t test_case_1 = math::largestPower(5,2);
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	int test_case_2 = math::largestPower(10,3);
```suggestion
	uint16_t test_case_2 = math::largestPower(10,3);
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	int test_case_3 = math::largestPower(25,5);
```suggestion
	uint32_t test_case_3 = math::largestPower(25,5);
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	int test_case_4 = math::largestPower(27,2);
```suggestion
	uint32_t test_case_4 = math::largestPower(27,2);
```

2020-10-30 22:15 UTC, Panquesito7 commented on math/largest_power.cpp
> +	int test_case_5 = math::largestPower(7,3);
```suggestion
	uint16_t test_case_5 = math::largestPower(7,3);
```

2020-10-30 22:15 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/uday6670/C-Plus-Plus/actions

2020-10-31 04:07 UTC, uday6670 commented
@Panquesito7 and @kvedala  Please review

2020-11-01 20:24 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/uday6670/C-Plus-Plus/actions

2020-11-04 08:05 UTC, uday6670 commented
I am enabled Github action.

2020-11-04 08:06 UTC, uday6670 commented
Please review @ayaankhan98

2020-11-05 02:09 UTC, Panquesito7 reviewed
Good work. Now, to trigger the GitHub Actions, make a small commit (e.g.: add a new line after line 9).
If GitHub Actions is enabled, we'll see a commit by GitHub Actions updating `DIRECTORY.md`. 🙂

2020-11-05 19:05 UTC, Panquesito7 approved these changes
Great work. Thank you for your contribution! 🎉 👍

2020-11-25 09:18 UTC, kvedala approved these changes

2020-11-25 09:18 UTC, merged