added C++ code to calculate nCr modulo p
TheAlgorithms/C-Plus-Plus pull request #1409
Opened 2020-10-29 06:43 UTC by Sreshth01

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
C++ code to calculate nCr modulo p where p is a prime number

2020-10-30 01:04 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Sreshth01/C-Plus-Plus/actions

2020-10-30 01:05 UTC, Panquesito7 commented
Please fix the [LGTM](https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/rev/pr-21d684f1bbfa9d2f9985037ff56166cb6b7babea) errors.

2020-10-30 04:42 UTC, Sreshth01 commented
Ok

On Fri 30 Oct, 2020, 6:35 AM David Leal, <notifications@github.com> wrote:

> Please fix the LGTM
> <https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/rev/pr-21d684f1bbfa9d2f9985037ff56166cb6b7babea>
> errors.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/1409#issuecomment-719108987>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMTXSMSBV5NHT7D7LYELPOTSNIGNLANCNFSM4TDJ4WVA>
> .
>

2020-10-30 05:12 UTC, Sreshth01 commented
Done with the required changes, please review it.
Thanks

2020-10-30 22:26 UTC, Panquesito7 requested changes

2020-10-30 22:26 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +#include <vector>
```suggestion
#include <iostream>  /// for io operations
#include <vector>   /// for std::vector
```

2020-10-30 22:26 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +/** function to find inverse modulo of given number */
Missing parameters and return statement documentation.

2020-10-30 22:26 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +int64_t nCr(int64_t n, int64_t r, int64_t p) {
Missing function documentation.

2020-10-30 22:26 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +/** Main function */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2020-10-30 22:26 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +}
```suggestion
}

```

2020-10-30 22:26 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +    int n = 0, r = 0, p = 0;
```suggestion
    uint16_t n = 0, r = 0, p = 0;
```

2020-11-01 21:51 UTC, Panquesito7 requested changes

2020-11-01 21:51 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +std::vector<int64_t> factorial;  // Store pre-computed factorials
```suggestion
std::vector<int64_t> factorial;  ///< Store pre-computed factorials
```

2020-11-01 21:51 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +int64_t inverse(int64_t i, int64_t m) {
Missing parameters and return statement documentation.

2020-11-01 21:51 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +int64_t nCr(int64_t n, int64_t r, int64_t p) {
Same here as above.

2020-11-02 17:53 UTC, Sreshth01 commented
@Panquesito7 can you please explain what do you mean by "parameters and return statement documentation". I have tried explaining about them with function documentation.

2020-11-02 18:41 UTC, Panquesito7 commented
> what do you mean by "parameters and return statement documentation"

Parameters should be documented using `@param`.
Say the function name is `printSolution`, and it has 1 parameter.

The way to document the function above should be like this:

```c++
      /**
       * @brief Utility function to print array
       * @param arr array where numbers are stored
       * @returns void
       */
       void printSolution(const std::array<32, uint32_t>& arr) {}
```

If you have any other doubts, please tell me and I'll help you. 🙂

2020-11-03 21:03 UTC, Panquesito7 requested changes

2020-11-03 21:03 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +}
```suggestion
}
}  // namespace math

```

2020-11-03 21:03 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +    int64_t answer = nCr(n, r, p);
```suggestion
    int64_t answer = math::nCr(n, r, p);
```

2020-11-03 21:03 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> +    std::cout << answer;
```suggestion
    std::cout << answer << "\n";
```

2020-11-03 21:03 UTC, Panquesito7 commented on math/ncr_mod_p.cpp
> + * answer modulo p
```suggestion
 * answer modulo p
 *
 * @author [Sreshth01](https://github.com/Sreshth01)
```

2021-07-21 16:42 UTC, closed without merging