Create Bidirectional Dijkstra Algorithm
TheAlgorithms/C-Plus-Plus pull request #1410
Opened 2020-10-29 15:27 UTC by Marinovsky

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-10-29 22:36 UTC, Panquesito7 requested changes
👍 Good code.

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +void tests() {
```suggestion
static void tests() {
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +/** Function to test the Algorithm */
```suggestion
/**
 * @brief Function to test the Algorithm
 * @returns 0 on exit
 */
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +/** Main function */
```suggestion
/** 
 * @brief Main function
 * @returns 0 on exit
 */
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +
```suggestion
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +#include <math.h>
```suggestion
#include <cmath>
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +namespace graph {
```suggestion
namespace graph {
/**
 * @namespace bidirectional_dijkstra
 * @brief Functions for [Bidirectional Dijkstra Shortest Path]
 * (https://www.coursera.org/learn/algorithms-on-graphs/lecture/7ml18/bidirectional-dijkstra) algorithm
 */
namespace bidirectional_dijkstra {
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +}  // namespace graph
```suggestion
}  // namespace bidirectional_dijkstra
}  // namespace graph
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    graph::addEdge(&adj1_1, &adj1_2, 1, 3, 5);
```suggestion
    graph::bidirectional_dijkstra::addEdge(&adj1_1, &adj1_2, 1, 2, 1);
    graph::bidirectional_dijkstra::addEdge(&adj1_1, &adj1_2, 4, 1, 2);
    graph::bidirectional_dijkstra::addEdge(&adj1_1, &adj1_2, 2, 3, 2);
    graph::bidirectional_dijkstra::addEdge(&adj1_1, &adj1_2, 1, 3, 5);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    assert(graph::Bidijkstra(&adj1_1, &adj1_2, s - 1, t - 1) == 3);
```suggestion
    assert(graph::bidirectional_dijkstra::Bidijkstra(&adj1_1, &adj1_2, s - 1, t - 1) == 3);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    assert(graph::Bidijkstra(&adj1_1, &adj1_2, s - 1, t - 1) == 5);
```suggestion
    assert(graph::bidirectional_dijkstra::Bidijkstra(&adj1_1, &adj1_2, s - 1, t - 1) == 5);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    graph::addEdge(&adj2_1, &adj2_2, 3, 4, 4);
```suggestion
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 1, 2, 4);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 1, 3, 2);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 2, 3, 2);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 3, 2, 1);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 2, 4, 2);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 3, 5, 4);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 5, 4, 1);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 2, 5, 3);
    graph::bidirectional_dijkstra::addEdge(&adj2_1, &adj2_2, 3, 4, 4);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    assert(graph::Bidijkstra(&adj2_1, &adj2_2, s - 1, t - 1) == 6);
```suggestion
    assert(graph::bidirectional_dijkstra::Bidijkstra(&adj2_1, &adj2_2, s - 1, t - 1) == 6);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +        graph::addEdge(&adj1, &adj2, u, v, w);
```suggestion
        graph::bidirectional_dijkstra::addEdge(&adj1, &adj2, u, v, w);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    int dist = graph::Bidijkstra(&adj1, &adj2, s - 1, t - 1);
```suggestion
    int dist = graph::bidirectional_dijkstra::Bidijkstra(&adj1, &adj2, s - 1, t - 1);
```

2020-10-29 22:36 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +#include <vector>
Add a brief description of what the library/header adds (see the example below).

        #include <assert>     /// for assert
        #include <iostream>  /// for io operations

2020-10-30 00:38 UTC, Marinovsky commented
Hey, I was trying to commit the changes you mentioned but I don't know why some checks were not successful, and I this is my first pull request, so can I close this pull request apply the changes mentioned, and make a new pull request?

2020-10-30 01:02 UTC, Panquesito7 commented
No, it's OK to implement the same changes in the same PR for easier reviewing. 🙂
I'll check the continuous integration errors. Seems to be something I messed up. 😄

2020-10-30 01:16 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    for (int i = 0; i < workset_.size(); i++) {
```suggestion
    for (int i : workset_) {
```

2020-10-30 01:16 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +int Shortest_Path_Distance(std::vector<int> workset_,
```suggestion
int Shortest_Path_Distance(const std::vector<int> &workset_,
```

2020-10-30 01:16 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +        visited[currentNode] = 1;
```suggestion
        visited[currentNode] = true;
```

2020-10-30 01:16 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +        visited[currentNode] = 1;
```suggestion
        visited[currentNode] = true;
```

2020-10-30 01:16 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +/** Function to test the Algorithm */
```suggestion
/**
 * @brief Function to test the
 * provided algorithm above
 * @returns void
 */
```

2020-10-30 04:03 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +#include <vector>
Add a brief description of what the header/library adds (see the example below).
```suggestion
#include <cmath>          /// for
#include <cassert>        /// for assert
#include <cstdio>         /// for
#include <iostream>       /// for io operations
#include <limits>         /// for
#include <set>            /// for
#include <unordered_map>  /// for
#include <queue>          /// for
#include <utility>        /// for
#include <vector>         /// for std::vector
```

2020-10-30 20:36 UTC, Marinovsky commented
I think it is already done

2020-10-30 23:30 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +void addEdge(std::vector<std::vector<std::pair<int, int>>> *adj1,
Consider using `uint64_t` or `int64_t`, or their appropriate size ([reference](https://en.cppreference.com/w/cpp/types/integer)). Check other parts of the code.

2020-11-01 19:06 UTC, Panquesito7 reviewed
Did a quick test on Gitpod, and there seems to be an error with your program.
After printing the result, it keeps there forever, unless you type something and enter.

![Gitpod quick-test](https://user-images.githubusercontent.com/51391473/97811854-d7456280-1c42-11eb-9fcc-34bedc5d118c.png)

After typing the vertices and edges:

![Gitpod quick-test](https://user-images.githubusercontent.com/51391473/97811866-f9d77b80-1c42-11eb-976d-d12067c33955.png)


Could you please fix the algorithm to run properly?

2020-11-01 23:31 UTC, Marinovsky commented
> Did a quick test on Gitpod, and there seems to be an error with your program.
> After printing the result, it keeps there forever, unless you type something and enter.
> 
> ![Gitpod quick-test](https://user-images.githubusercontent.com/51391473/97811854-d7456280-1c42-11eb-9fcc-34bedc5d118c.png)
> 
> After typing something the vertices and edges:
> 
> ![Gitpod quick-test](https://user-images.githubusercontent.com/51391473/97811866-f9d77b80-1c42-11eb-976d-d12067c33955.png)
> 
> Could you please fix the algorithm to run properly?

Yeah, I think it is not a problem, after executing the test cases the user can enter a test case so they first enter the number of vertices and edges and then the graph by the number of edges lines in which there are three numbers v, u, and w, representing an edge between the node v and u with weight w. I will describe that in the commentaries.

2020-11-02 00:01 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> + *@brief This function returns the shortest distance from the source
```suggestion
 * @brief This function returns the shortest distance from the source
```

2020-11-02 00:34 UTC, Panquesito7 commented on graph/bidirectional_dijkstra.cpp
> +    tests();
```suggestion
    tests();  // running predefined tests
```

2020-11-02 01:37 UTC, Panquesito7 approved these changes
Neat work! Code looks refined and well-documented! 😄 👍

2020-11-20 12:22 UTC, Marinovsky commented
Excuse me, Shall I make another modification to the code?

2020-11-20 18:58 UTC, ayaankhan98 approved these changes
Thanks for your contribution @Marinovsky, LGTM!

2020-11-20 18:58 UTC, merged