Added Modular Exponentiation
TheAlgorithms/C-Plus-Plus pull request #1411
Opened 2020-10-29 19:07 UTC by proRamLOGO

#### Description of Change
Added Modular Exponentiation iterative and recursive.
Added bitwise operations to speed up the processing of program.

#### Checklist

- [x ] Added description of change
- [x ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x ] Added tests and example, test must pass
- [x ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x ] I acknowledge that all my contributions will be made under the project's license.

Notes: Added 2 functions with relevant descriptions and tests.

2020-10-29 19:57 UTC, Panquesito7 requested changes
Is this PR about adding Modular Exponentiation, or about improving `math/binary_exponent.cpp`?

2020-10-29 19:57 UTC, Panquesito7 commented on math/binary_exponent.cpp
> +uint64_t binModExpo(uint64_t a, uint64_t b, uint64_t m) {
Function documentation is not up to the [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html).

2020-10-29 19:57 UTC, Panquesito7 commented on math/binary_exponent.cpp
> +uint64_t binModExpo_alt(uint64_t a, uint64_t b, uint64_t m) {
Same here as above.

2020-10-29 19:57 UTC, Panquesito7 commented on math/binary_exponent.cpp
>  /// Main function
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2020-10-29 19:57 UTC, Panquesito7 commented on math/binary_exponent.cpp
> +        std::cout << "Result of a^b%m Iterative : " << binModExpo_alt(a,b,m) << std::endl;
```suggestion
        std::cout << "Result of a^b%m Iterative : " << binModExpo_alt(a,b,m) << std::endl;

        return 0;
```

2020-10-30 13:48 UTC, proRamLOGO commented
> Is this PR about adding Modular Exponentiation, or about improving `math/binary_exponent.cpp`?

Adding Modular Exponentiation

2021-07-21 09:42 UTC, closed without merging