Balanced_braces
TheAlgorithms/C-Plus-Plus pull request #1431
Opened 2020-11-23 12:55 UTC by rbhattad

program to check whether braces are balanced are not using stack

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-11-23 16:49 UTC, Panquesito7 requested changes
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

2020-11-24 18:13 UTC, rbhattad commented
this is my first contribution  please give more info. for enhancement and documentation i have added proper comments

2020-11-24 19:57 UTC, Panquesito7 reviewed
See #962 for how to make your code refined and well-documented.
Or, see the [typical structure](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program for more information. 🙂

2021-02-01 08:12 UTC, AnupKumarPanwar commented on data_structures/Balanced_Bracket
> +//	checknumber();
Are these comments here for some purpose?

2021-07-21 13:42 UTC, closed without merging