feat: add dynamic_programming/subset_sum.cpp  (subset sum problem)
TheAlgorithms/C-Plus-Plus pull request #1434
Opened 2020-12-12 19:26 UTC by Vinay-Garg

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2020-12-23 01:34 UTC, Panquesito7 requested changes
👍 Well done!

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +#include <vector>
```suggestion
#include <array>       /// for std::array
#include <cassert>    /// for assert
#include <iostream>   /// for io operations
#include <vector>     /// for std::vector
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @brief bottom up implementation of subset sum problem
```suggestion
* @brief Bottom up implementation of [Subset Sum Problem](https://en.wikipedia.org/wiki/Subset_sum_problem)
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +bool subset_sum(const std::array<int, n> &set, const int sum) {
```suggestion
bool subset_sum(const std::array<int, n> &set, const int& sum) {
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @brief top down implementation of subset sum problem
```suggestion
 * @brief Top down implementation of [Subset Sum Problem](https://en.wikipedia.org/wiki/Subset_sum_problem)
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +bool subset_sum(const std::array<int, n> &set, const int sum) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)).

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @param T template-type to use any kind of value
```suggestion
 * @tparam T template-type to use any kind of value
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @param sum 	: subset sum value
```suggestion
 * @tparam n size of the set array
 * @param set an array of numbers in set of size<=n
 * @param sum subset sum value
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +
```suggestion
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @param sum 	: subset sum value
```suggestion
 * @param set an array of numbers in set of size<=n
 * @param n size of the set array
 * @param sum subset sum value
```

2020-12-23 01:34 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +    test();  // call the test function :)
Adding `return 0;` at the end is a good programming practice. 🙂
```suggestion
    test();  // run self-test implementations
    return 0;
```

2021-01-30 06:58 UTC, Vinay-Garg reviewed
Thanks for the suggestions.

2021-01-31 02:08 UTC, Panquesito7 reviewed
Good work! 👍

2021-01-31 02:08 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +bool subset_sum(const std::array<int, n> &set, const int& sum) {
Consider using `uint64_t`, `uint32_t`, `uint16_t` or `uint8_t` for non-negative values. For negative values, use `int64_t` or their appropriate size. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)).

2021-07-21 12:42 UTC, closed without merging