Added persistent segment tree with lazy propagation
TheAlgorithms/C-Plus-Plus pull request #1445
Opened 2021-01-27 16:16 UTC by MSedra

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-01-27 18:13 UTC, Panquesito7 requested changes
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

2021-01-27 19:10 UTC, MSedra commented
> Code is not up to the [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
> Please read them **carefully** and **follow them**.

I have read the standards and tried to follow them as much as i could. Can you please elaborate which standard/s am i not following? Is using normal pointers not allowed?

2021-01-27 19:29 UTC, Panquesito7 reviewed
Let's start: first, we need to fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1445/checks?check_run_id=1778864629) warnings. 🙂

2021-01-27 20:38 UTC, MSedra commented
> Let's start: first, we need to fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1445/checks?check_run_id=1778864629) warnings. 🙂

Why do i get warnings when using normal pointers?

2021-01-27 22:11 UTC, MSedra commented
> Let's start: first, we need to fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1445/checks?check_run_id=1778864629) warnings. 🙂

Done. What's next?

2021-01-31 01:35 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/MSedra/C-Plus-Plus/actions

2021-01-31 20:14 UTC, Panquesito7 requested changes

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> + * @brief [Persistent segment tree with range updates (lazy propagation)](https://en.wikipedia.org/wiki/Persistent_data_structure - https://www.geeksforgeeks.org/lazy-propagation-in-segment-tree/)
This is Markdown, and it won't work properly if you add two links like you did. Please choose one.

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +#include <memory> /// to manage dynamic memory
```suggestion
#include <iostream>  /// for IO operations
#include <vector>    /// for std::vector
#include <memory>    /// to manage dynamic memory
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    void lazy(int i, int j, std::shared_ptr<Node> const &curr) {
As these two variables are not being modified, consider making them a `const` and pass them by reference.
```suggestion
    void lazy(const int& i, const int& j, std::shared_ptr<Node> const &curr) {
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    std::shared_ptr<Node> construct(int i, int j) {
```suggestion
    std::shared_ptr<Node> construct(const int& i, const int& j) {
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    std::shared_ptr<Node> update(int i, int j, int l, int r, int value, std::shared_ptr<Node> const &curr) {
```suggestion
    std::shared_ptr<Node> update(const int& i, const int& j, const int& l, const int& r, const int& value, std::shared_ptr<Node> const &curr) {
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    int64_t query(int i, int j, int l, int r, std::shared_ptr<Node> const &curr) {
```suggestion
    int64_t query(const int& i, const int& j, const int& l, const int& r, std::shared_ptr<Node> const &curr) {
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +void test() {
```suggestion
/**
 * @brief Test implementations
 * @returns void
 */
static void test() {
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +int main() {
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +}
```suggestion
}

```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +/// Range query here is range sum ,but the code can be modified to make different queries like range max or min
```suggestion
/**
 * @namespace range_queries
 * @brief Range queries algorithms
 */
namespace range_queries {
/**
 * @brief Range query here is range sum, but the code can be
 modified to make different queries like range max or min.
 */
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +};
```suggestion
};
}  // namespace range_queries
```

2021-01-31 20:14 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    perSegTree tree;
```suggestion
    range_queries::perSegTree tree;
```

2021-02-01 01:13 UTC, Panquesito7 reviewed
👍 Nice work! Well done.
Would you please consider editing the filename to make it shorter?
Also consider using `uint64_t` (for non-negative values), `int64_t` (for negative values) or their appropriate size in all the code.

Thank you. 🙂

2021-02-01 01:13 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> + * propagation)](https://en.wikipedia.org/wiki/Persistent_data_structure)
```suggestion
 * propagation)](https://en.wikipedia.org/wiki/Persistent_data_structure)

```

2021-02-01 01:13 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    int n;  /// number of elements/leaf nodes in the segment tree
We **always** got to initialize all variables, at least with `0`.
```suggestion
    int n = 0;  /// number of elements/leaf nodes in the segment tree
```

2021-02-01 01:13 UTC, Panquesito7 commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> +    std::vector<int> vec;  /// values of the leaf nodes that the segment tree
```suggestion
    std::vector<int> vec{};  /// values of the leaf nodes that the segment tree
```

2021-02-01 11:14 UTC, MSedra commented on range_queries/persistent_segment_tree_with_lazy_propagation.cpp
> + * propagation)](https://en.wikipedia.org/wiki/Persistent_data_structure)
Done. 

Thank you so much.

2021-02-04 14:40 UTC, MSedra commented
@Panquesito7 Can you please rereview?

2021-02-07 02:24 UTC, MSedra commented
@ayaankhan98 can you please review the last changes?

2021-02-07 13:06 UTC, ayaankhan98 approved these changes

2021-02-08 17:18 UTC, Panquesito7 approved these changes
Great work, looks amazing! LGTM; thanks for your contribution! 👍 🎉

2021-02-08 17:19 UTC, merged

2021-02-09 15:41 UTC, MSedra commented
> Great work, looks amazing! LGTM; thanks for your contribution! 👍 🎉

Thank you so much for your help