feat: add program to calculate binomial coefficients
TheAlgorithms/C-Plus-Plus pull request #1448
Opened 2021-02-04 15:24 UTC by astronmax

#### Description of Change

I have added a program to calculate binomial coefficients to the math module.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1448"><img src="https://gitpod.io/api/apps/github/pbs/github.com/astronmax/C-Plus-Plus.git/8996a57138d0cdccd7edd47d67a444d292249239.svg" /></a>

2021-02-05 12:59 UTC, ayaankhan98 commented on math/binomial.cpp
> + * @author astron
you can provide link to your github profile, if you wish.
Doxygen supports Markdown, you can use markdown like
`[Name](link to profile)`

2021-02-05 13:01 UTC, ayaankhan98 reviewed
rest of the code looks good to me.

2021-02-06 14:43 UTC, astronmax commented
@ayaankhan98 Thanks, I made changes.

2021-02-06 14:55 UTC, ayaankhan98 approved these changes

2021-02-12 02:50 UTC, Panquesito7 requested changes
👍 Well done!
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/astronmax/C-Plus-Plus/actions

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +#include <cstdlib>
Add a brief description of what the library adds (see the example below).
```c++
#include <iostream>  /// for IO operations
#include <assert>   /// for assert
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +void binomial_test() {
```suggestion
static void binomial_test() {
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> + */
```suggestion
/**
 * @brief Test implementations
 * @returns void
 */
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> + * Main function
```suggestion
 * @brief Main function
 * @returns 0 on exit
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +    printf("%zd\n", binomial(n, k));
```suggestion
    printf("%zd\n", binomial(n, k));
    return 0;
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> + * @brief Program to calculate binomial coefficients.
Provide a Wikipedia link (if available/possible) in Markdown format.
If there's no Wikipedia link, add another web source for algorithm explanation. 🙂

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +/**
```suggestion
/**
 * @namespace math
 * @brief Mathematical algorithms
 */
namespace math {
/**
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +}
```suggestion
}
}  // namespace math
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(binomial(1, 1) == 1);
```suggestion
    assert(math::binomial(1, 1) == 1);
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(binomial(57, 57) == 1);
```suggestion
    assert(math::binomial(57, 57) == 1);
```

2021-02-12 02:50 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(binomial(62, 31) == 465428353255261088);
```suggestion
    assert(math::binomial(6, 3) == 20);
    assert(math::binomial(10, 5) == 252);
    assert(math::binomial(20, 10) == 184756);
    assert(math::binomial(30, 15) == 155117520);
    assert(math::binomial(40, 20) == 137846528820);
    assert(math::binomial(50, 25) == 126410606437752);
    assert(math::binomial(60, 30) == 118264581564861424);
    assert(math::binomial(62, 31) == 465428353255261088);
```

2021-02-13 20:15 UTC, astronmax commented
@Panquesito7, thanks for review, i made changes.

2021-02-14 02:23 UTC, Panquesito7 requested changes
Looks much better, excellent work! 👍
Almost there, just a few more suggestions.

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +namespace math {
```suggestion
namespace math {
/**
 * @namespace binomial
 * @brief Functions for [Binomial
 * coefficients](https://en.wikipedia.org/wiki/Binomial_coefficient) implementation.
 */
namespace binomial {
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +}  // namespace math
```suggestion
}  // namespace binomial
}  // namespace math
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(1, 1) == 1);
```suggestion
    assert(math::binomial::binomial(1, 1) == 1);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(57, 57) == 1);
```suggestion
    assert(math::binomial::binomial(57, 57) == 1);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(6, 3) == 20);
```suggestion
    assert(math::binomial::binomial(6, 3) == 20);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(10, 5) == 252);
```suggestion
    assert(math::binomial::binomial(10, 5) == 252);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(20, 10) == 184756);
```suggestion
    assert(math::binomial::binomial(20, 10) == 184756);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(30, 15) == 155117520);
```suggestion
    assert(math::binomial::binomial(30, 15) == 155117520);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    assert(math::binomial(62, 31) == 465428353255261088);
```suggestion
    assert(math::binomial::binomial(40, 20) == 137846528820);
    assert(math::binomial::binomial(50, 25) == 126410606437752);
    assert(math::binomial::binomial(60, 30) == 118264581564861424);
    assert(math::binomial::binomial(62, 31) == 465428353255261088);
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +static void binomial_test() {
```suggestion
static void tests() {
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +
```suggestion
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> + */
```suggestion
/**
 * @brief Main function
 * @param argc commandline argument count (ignored)
 * @param argv commandline array of arguments (ignored)
 * @returns 0 on exit
 */
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    binomial_test();
```suggestion
    tests();  // run self-test implementations
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +    printf("%zd\n", math::binomial(n, k));
As a C++ program, we use `std::cout` here, not C-style functions.
Please consider using C++-style functions as much as possible.
```suggestion
    printf("%zd\n", math::binomial::binomial(n, k));
```

2021-02-14 02:23 UTC, Panquesito7 commented on math/binomial.cpp
> +        printf("Usage ./binomial {n} {k}\n");
Same here, use `std::cout` instead.

2021-02-14 09:55 UTC, astronmax commented
@Panquesito7, OK, Done. I decided to change the name of the file and the function, since, in my opinion, calling math::binomial::calculate() will look more logical than math::binomial::binomial().

2021-02-14 19:17 UTC, Panquesito7 approved these changes
Amazing work, I like how you've made the code. 😄 👍
Code and documentation are pretty good and refined; LGTM. 🎉

2021-02-22 19:21 UTC, ayaankhan98 approved these changes
@astronmax Thanks for your contribution

2021-02-22 19:21 UTC, merged