Adding dp_bitmasking example in dynamic_programming.
TheAlgorithms/C-Plus-Plus pull request #1475
Opened 2021-04-09 21:34 UTC by faizan2700

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-04-09 21:38 UTC, Panquesito7 requested changes
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1475/checks?check_run_id=2309561860) warnings.

2021-04-09 21:58 UTC, Panquesito7 requested changes
The [checks](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1475/checks?check_run_id=2309670413) are still failing. Please fix them.

2021-04-09 22:18 UTC, faizan2700 commented
Suggestions for improvement are appreciated. Thank you for reviewing.

2021-04-10 00:16 UTC, Panquesito7 requested changes
👍 Good work!
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/faizan2700/C-Plus-Plus/actions

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> +    //Max score is in the mask 2**(1<<2*N) - 1, which shows all elements are added.
```suggestion
    // Max score is in the mask 2**(1<<2*N) - 1, which shows all elements are added.
```

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> +} //namespace dynamic_programming
```suggestion
}  // namespace dp_bitmask
}  // namespace dynamic_programming
```

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> +    // Test 1
```suggestion
    // 1st test
```

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> +    // Test 2
```suggestion
    // 2nd test
```

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> +
```suggestion
```

2021-04-10 00:16 UTC, Panquesito7 commented on dynamic_programming/dp_bitmasking.cpp
> + * @brief Function to test above algorithm
```suggestion
 * @brief Self-test implementations
```

2021-04-10 07:41 UTC, faizan2700 commented
DP - Bitmasking example

Problem : Given an Integer N, and an Array of Integer A of size 2*N. 
Select N pairs from this array such that each element is present in 
exactly one pair, And the following score is maximized.

score = summation(gcd(x_i, y_i) * i) for i 1 to n.

Solution :
See that score depends upon the selection of pairs and order of pairs.
consider the subset of the array which contains 2*n elements and n pairs.
this subset is denoted by binary number where j-th bit is 1 if that element 
is included and 0 if that element is excluded (0101 -> first and third included, 
second and fourth excluded). using this we can find the maximum value we can
get for selection of n+1 pairs, if n-pairs are selected from this pair and one pair 
is made from unselected elements. of course the subset which contains n+1 pairs, 
will be updated by all different subsets of n-pairs and hence will contain the optimal 
value. we can start from mask 0 which shows no pair is selected and keep updating like
this till the mask which shows all elements are selected 1111...(2*N times) that is 
2^(2*N) - 1, this mask will contain the answer. so finally we can write dp transition as


dp[subset of n+1 pairs] = max( dp[subset of size n-pairs] and adding gcd(new_pair from 
unselected elements) )

2021-04-10 07:42 UTC, faizan2700 commented
Please tell me if this explanation is good. I will add this in bottom of the code file, if allowed.

2021-04-10 08:12 UTC, closed without merging