New code
TheAlgorithms/C-Plus-Plus pull request #1479
Opened 2021-04-10 17:53 UTC by AshishYUO

#### Description of Change

Feat: Implementation of [Elliptic Curve Diffie Hellman Key Exchange](https://cryptobook.nakov.com/asymmetric-key-ciphers/ecdh-key-exchange).
Type: Ciphers.
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
There are three files associated with the given topic.

2021-04-11 05:15 UTC, Panquesito7 requested changes
👍 Great work!
Please fix [`windows-latest`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1479/checks?check_run_id=2314004958) warnings. Mostly, the errors/warnings are displayed at the bottom.

2021-04-12 02:05 UTC, Panquesito7 requested changes

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +#include "uint256_t.hpp"
Add a one-line description of what the library/header is for (see the example below).
```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +    // Tests 1: Operations test
```suggestion
    // 1st test: Operations test
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +    // Tests 2: Operations test
```suggestion
    // 2nd test: Operations test
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +    // Tests 1: Operations test
```suggestion
    // 1st test: Operations test
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +    // Tests 2: Operations test
```suggestion
    // 2nd test: Operations test
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +    test();             // running predefined tests
```suggestion
    test();             // running self-test implementations
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/elliptic_curve_key_exchange.cpp
> +    uint256_t_tests();  // running predefined 256-bit unsigned integer tests.
```suggestion
    uint128_t_tests();  // running predefined 128-bit unsigned integer tests
    uint256_t_tests();  // running predefined 256-bit unsigned integer tests
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/uint128_t.hpp
> + * @file uint128_t.hpp
```suggestion
 * @file
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/uint128_t.hpp
> +#include <utility>
Add a one-line description of what the library/header is for (see the example below).
```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/uint128_t.hpp
> + * @details 128-bit numbers.
```suggestion
 * @brief 128-bit numbers.
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/uint256_t.hpp
> + * @file uint256_t.hpp
```suggestion
 * @file
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/uint256_t.hpp
> +#include "uint128_t.hpp"
Add a one-line description of what the library/header is for (see the example below).
```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2021-04-12 02:05 UTC, Panquesito7 commented on ciphers/uint256_t.hpp
> + * @details 256-bit number class.
```suggestion
 * @brief 256-bit number class
```

2021-04-12 22:06 UTC, Panquesito7 commented on ciphers/uint256_t.hpp
> +    explicit uint256_t(T low) : s(low), f(0) {}
Add a one-line description of what these variables do or are for.

2021-04-13 17:09 UTC, Panquesito7 approved these changes
Awesome work! I like how you've improved and made the code so well. 😄
Code and documentation are pretty well-made. Thank you for your contribution! 👍 🎉

2021-04-13 17:21 UTC, Panquesito7 approved these changes

2021-04-14 05:33 UTC, ayaankhan98 approved these changes

2021-04-14 05:34 UTC, merged