feat: Adding subset sum in dynamic programming
TheAlgorithms/C-Plus-Plus pull request #1480
Opened 2021-04-11 00:58 UTC by faizan2700

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-04-11 01:23 UTC, faizan2700 commented
test are shown complete in github workflow of my fork. someone pls check why it is taking so much time here.

2021-04-11 16:14 UTC, faizan2700 commented
update : latex format added wherever possible in documentation comments

2021-04-15 22:32 UTC, Panquesito7 requested changes
👍 Good work.

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * (https://www.geeksforgeeks.org/subset-sum-problem-dp-25)
```suggestion
 * @brief [Subset Sum DP](https://www.geeksforgeeks.org/subset-sum-problem-dp-25) Implementation
```

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +#include <array>     /// for creating std::array
```suggestion
#include <array>     /// for `std::array`
```

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +#include <vector>    /// for using std::vector
```suggestion
#include <vector>    /// for `std::vector`
```

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +#include <cassert>   /// for using assert in test function
```suggestion
#include <cassert>   /// for `assert`
```

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @brief [Subset Sum DP] Implementation
```suggestion
 * @brief Functions for [Subset Sum DP](https://www.geeksforgeeks.org/subset-sum-problem-dp-25) Implementation
```

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @param $V$ subset sum to be obtained.
Why the `$`?

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> + * @brief Self-test implementation
```suggestion
 * @brief Self-test implementations
```

2021-04-15 22:32 UTC, Panquesito7 commented on dynamic_programming/subset_sum.cpp
> +    test();  // run self-test implementation
```suggestion
    test();  // run self-test implementations
```

2021-09-15 00:36 UTC, closed without merging