Cycle_Sort_Algo
TheAlgorithms/C-Plus-Plus pull request #1511
Opened 2021-06-20 15:20 UTC by Swastyy

Added more test cases and changed the cyclesort function where it is swapping the value in item and array element at pos position without checking if the pos is same as cycle_start.

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-06-20 15:30 UTC, Swastyy commented
@Panquesito7 Good evening! Can You please check this once?

2021-06-20 22:19 UTC, Panquesito7 requested changes

2021-06-20 22:19 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +#include <vector>    /// for std::vector
```suggestion
#include <algorithm>  /// for std::is_sorted, std::swap
#include <cassert>    /// for assert
#include <iostream>   /// for io operations
#include <vector>     /// for std::vector
```

2021-06-20 22:19 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +namespace cycle_sort {
```suggestion
namespace cycle_sort {
```

2021-06-20 22:19 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +        else{
```suggestion
        else {
```

2021-06-20 22:19 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +            else{
```suggestion
            else {
```

2021-06-20 22:19 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +} // namespace sorting
```suggestion
}  // namespace cycle_sort
}  // namespace sorting
```

2021-06-20 22:19 UTC, Panquesito7 commented on sorting/cycle_sort.cpp
> +    std::vector<int> arr1  = sorting::cycle_sort::cycleSort(array1);
```suggestion
    std::vector<int> arr1 = sorting::cycle_sort::cycleSort(array1);
```

2021-06-21 03:20 UTC, Swastyy commented
@Panquesito7 Thank you so much for pointing out. I have done the changes.

(P.S. I was very excited for my first contribution; I forgot to check the neatness of code)

2021-06-22 12:52 UTC, Swastyy commented
> @Panquesito7 Thank you so much for pointing out. I have done the changes.

@Panquesito7 Hey! Did you see it after I committed the changes?

2021-06-22 19:28 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

2021-06-23 00:57 UTC, Swastyy commented
> Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

Done!!

2021-06-24 12:17 UTC, Swastyy commented
> Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

@Panquesito7 I have enabled the github actions!!

2021-06-25 06:54 UTC, Swastyy commented
> Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

Hey what else improvements are remaining in this file? @Panquesito7 Is this PR visible to you?

2021-06-26 09:02 UTC, Swastyy commented
@Panquesito7 Hey, please have some time to look into this PR. And l have enabled the github actions.

2021-06-26 09:25 UTC, Swastyy commented
@Panquesito7 Hey, please take some time to look into this. And I have enabled github actions.

P.S. The forked repo from which I created this PR got deleted accidentally then I forked it again. Can you please let me know if this will cause a problem, we will cancel this one and I will create a new PR for cycle sort.

2021-06-29 18:15 UTC, closed without merging