Create count_of_set_bits.cpp
TheAlgorithms/C-Plus-Plus pull request #1515
Opened 2021-06-27 16:05 UTC by Swastyy

#### Description of Change Code to count set bits in binary representation of a given number.

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-06-29 17:52 UTC, Swastyy commented
@Panquesito7 Have a look into this PR 😄

2021-07-01 13:03 UTC, Swastyy commented
@fhlasek Please have a look in this PR also. 😃

2021-07-02 03:32 UTC, fhlasek approved these changes
Well written, well tested, well documented. Thanks!

2021-07-06 22:33 UTC, Panquesito7 requested changes
👍 Good work!

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @brief Program to Count set bits in an integer
```suggestion
 * @brief Implementation to [count sets bits](https://www.geeksforgeeks.org/count-set-bits-in-an-integer/) in an integer.
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @brief bit set counting algorithm
```suggestion
 * @brief Bit manipulation algorithms
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @brief Functions for counting set bits in binary representation of a number
```suggestion
 * @brief Functions for the [count sets bits](https://www.geeksforgeeks.org/count-set-bits-in-an-integer/) implementation
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +
```suggestion
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    test();  // execute the test
```suggestion
    test();  // run self-test implementations
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @brief Test implementations
```suggestion
 * @brief Self-test implementations
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @returns count , the number set bit in binary representation of n
```suggestion
 * @returns the count of the number set bit in the binary representation of `n`
```

2021-07-06 22:33 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @details
```suggestion
 * @details
 * We are given an integer number. Let’s say, number. The task is to first calculate the
 * binary digit of a number and then calculate the total set bits of a number.
 *
 * Set bits in a binary number is represented by 1. Whenever we calculate the binary number of an integer value
 * it is formed as the combination of 0’s and 1’s. So digit 1 is known as a set bit in computer terms.
```

2021-07-06 22:35 UTC, Panquesito7 commented
Sorry for taking long in reviewing this PR (including other PRs). There have been many PRs recently (plus other important stuff I have to work on). 😅

2021-07-09 01:03 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @details
If you're not going to add this, please add a detailed description of the algorithm. I'm not trying to be rude, by the way. :)

2021-07-09 01:05 UTC, Panquesito7 requested changes
Almost there! 😄

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @namespace bitCount
```suggestion
 * @namespace count_of_set_bits
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +namespace bitCount {
```suggestion
namespace count_of_set_bits {
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +}  // namespace bitCount
```suggestion
}  // namespace count_of_set_bits
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @brief Test implementations
```suggestion
 * @brief Self-test implementations
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    assert(bit_manipulation::bitCount::countSetBits(4) == 1);
```suggestion
    assert(bit_manipulation::count_of_set_bits::countSetBits(4) == 1);
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    assert(bit_manipulation::bitCount::countSetBits(6) == 2);
```suggestion
    assert(bit_manipulation::count_of_set_bits::countSetBits(6) == 2);
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    assert(bit_manipulation::bitCount::countSetBits(13) == 3);
```suggestion
    assert(bit_manipulation::count_of_set_bits::countSetBits(13) == 3);
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    assert(bit_manipulation::bitCount::countSetBits(9) == 2);
```suggestion
    assert(bit_manipulation::count_of_set_bits::countSetBits(9) == 2);
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    assert(bit_manipulation::bitCount::countSetBits(15) == 4);
```suggestion
    assert(bit_manipulation::count_of_set_bits::countSetBits(15) == 4);
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    assert(bit_manipulation::bitCount::countSetBits(25) == 3);
```suggestion
    assert(bit_manipulation::count_of_set_bits::countSetBits(25) == 3);
```

2021-07-09 01:05 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> +    std::cout << "All test cases passed" << std::endl;
```suggestion
    std::cout << "All test cases successfully passed!" << std::endl;
```

2021-07-09 01:50 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @author [Swastika Gupta](https://github.com/swastyy)
```suggestion
 * @author [Swastika Gupta](https://github.com/Swastyy)
```

2021-07-09 01:50 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * O(log n) Space complexity :- O(1)
```suggestion
 * 1’s. So digit 1 is known as a set bit in computer terms.
 * Time Complexity: O(log n)
 * Space complexity: O(1)
```

2021-07-09 02:06 UTC, Panquesito7 requested changes

2021-07-09 02:06 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits.cpp
> + * @brief Test implementations
```suggestion
 * @brief Self-test implementations
```

2021-07-09 02:13 UTC, Panquesito7 approved these changes
Great work, @Swastyy! Thank you for your contribution! 👍 🎉

2021-07-09 09:43 UTC, ayaankhan98 approved these changes

2021-07-09 09:43 UTC, merged