Create wave_sort.cpp
TheAlgorithms/C-Plus-Plus pull request #1525
Opened 2021-07-04 11:49 UTC by Swastyy

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-07-15 01:58 UTC, Panquesito7 requested changes
Good work! 👍

2021-07-15 01:58 UTC, Panquesito7 commented on sorting/wave_sort.cpp
> + * @brief Implementation of [Wave sort] algorithm
Provide a Wikipedia link in Markdown format (if available/possible).
If there's no Wikipedia link, add another web source for algorithm explanation.

2021-07-15 01:58 UTC, Panquesito7 commented on sorting/wave_sort.cpp
> + * @brief The main function implements waveSort
```suggestion
 * @brief The main function implements that implements the Wave Sort algorithm
```

2021-07-15 01:58 UTC, Panquesito7 commented on sorting/wave_sort.cpp
> + * @brief Test implementations
```suggestion
 * @brief Self-test implementations
```

2021-07-15 01:58 UTC, Panquesito7 commented on sorting/wave_sort.cpp
> +    test();  // execute the test
```suggestion
    test();  // run self-test implementations
```

2021-07-15 20:01 UTC, Panquesito7 requested changes
It's just to accept these suggestions, and you're done! 😄

2021-07-15 20:09 UTC, Panquesito7 approved these changes
LGTM. Great work, @Swastyy! Thank you for your contribution! 👍 🎉

2021-07-15 20:15 UTC, ayaankhan98 approved these changes

2021-07-16 03:39 UTC, mishraabhinn approved these changes

2021-07-16 18:41 UTC, merged