feat: Add the `floyd_cycle_detection_algo.cpp` file/algorithm
TheAlgorithms/C-Plus-Plus pull request #1535
Opened 2021-07-18 09:15 UTC by Swastyy

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-07-18 09:17 UTC, Swastyy commented
@Panquesito7 Check if this will work for #1529

2021-07-19 11:45 UTC, mishraabhinn reviewed
Why there are multiple files again? One file one pr.

2021-07-19 12:00 UTC, Swastyy commented
> Why there are multiple files again? One file one pr.

They aren't mine (iterative_tree_traversal.cpp, graph_coloring.cpp and random_pivot_quick_sort.cpp).

2021-07-19 12:09 UTC, mishraabhinn commented
> > Why there are multiple files again? One file one pr.
> 
> They aren't mine (iterative_tree_traversal.cpp, graph_coloring.cpp and random_pivot_quick_sort.cpp).
How this is even possible. 
![Screenshot 2021-07-19 at 17 38 29](https://user-images.githubusercontent.com/49574460/126157624-453ebf87-da9b-43a5-80ef-8d40803f472e.png)

2021-07-19 12:14 UTC, Swastyy commented
Okay There are some conflicts between master branch of my forked repo and the real one. I will fork it again but @mishraabhinn merge this last PR #1527 from old fork

2021-07-19 12:29 UTC, mishraabhinn commented
> Okay There are some conflicts between master branch of my forked repo and the real one. I will fork it again but @mishraabhinn merge this last PR #1527 from old fork

There are also 5 files. I don't understand. 
[Branch can stay updated with master ](https://gist.github.com/whoisryosuke/36b3b41e738394170b9a7c230665e6b9)
[For making forked repo updated](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork)

2021-07-19 12:31 UTC, mishraabhinn commented
> > Okay There are some conflicts between master branch of my forked repo and the real one. I will fork it again but @mishraabhinn merge this last PR #1527 from old fork
> 
> There are also 5 files. I don't understand.
> [Branch can stay updated with master ](https://gist.github.com/whoisryosuke/36b3b41e738394170b9a7c230665e6b9)
> [For making forked repo updated](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork)

I think this is happening because you create branches from previous branch. I advice you that when you create a new branch go to master update master then create a new branch.

2021-07-19 12:33 UTC, Swastyy commented
> > > Okay There are some conflicts between master branch of my forked repo and the real one. I will fork it again but @mishraabhinn merge this last PR #1527 from old fork
> > 
> > 
> > There are also 5 files. I don't understand.
> > [Branch can stay updated with master ](https://gist.github.com/whoisryosuke/36b3b41e738394170b9a7c230665e6b9)
> > [For making forked repo updated](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork)
> 
> I think this is happening because you create branches from previous branch. I advice you that when you create a new branch go to master update master then create a new branch.

Ha I think so

2021-07-19 12:34 UTC, Swastyy commented
> > Okay There are some conflicts between master branch of my forked repo and the real one. I will fork it again but @mishraabhinn merge this last PR #1527 from old fork
> 
> There are also 5 files. I don't understand.
> [Branch can stay updated with master ](https://gist.github.com/whoisryosuke/36b3b41e738394170b9a7c230665e6b9)
> [For making forked repo updated](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork)

Master branch is anyways the default branch of forked repo but if I can update a particular branch from original repo that will be great. Thanks for the links. 👍🏻

2021-07-19 18:49 UTC, Panquesito7 commented
All other files are changed automatically by the workflow, so even if you undo those changes, they'll come back. @mishraabhinn.

2021-07-19 18:51 UTC, Panquesito7 requested changes
Great work! 😄:+1:

2021-07-19 18:51 UTC, Panquesito7 commented on search/floyd_cycle_detection_algo.cpp
> +#include <vector>    /// for std::vector
```suggestion
#include <vector>    /// for std::vector

```

2021-07-19 18:51 UTC, Panquesito7 commented on search/floyd_cycle_detection_algo.cpp
> + * @details Given an array of integers containing 'n + 1' integers, where each
```suggestion
 * @details
 * Given an array of integers containing 'n + 1' integers, where each
```

2021-07-19 18:51 UTC, Panquesito7 commented on search/floyd_cycle_detection_algo.cpp
> +    // Test 1
```suggestion
    // 1st test
```

2021-07-19 18:51 UTC, Panquesito7 commented on search/floyd_cycle_detection_algo.cpp
> +    // Test 2
```suggestion
    // 2nd test
```

2021-07-19 18:51 UTC, Panquesito7 commented on search/floyd_cycle_detection_algo.cpp
> +    // Test 3
```suggestion
    // 3rd test
```

2021-07-19 19:17 UTC, mishraabhinn commented
> All other files are changed automatically by the workflow, so even if you undo those changes, they'll come back. @mishraabhinn.
> 
> 

I don’t get this. How automatically?

2021-07-19 20:11 UTC, Panquesito7 commented
> > All other files are changed automatically by the workflow, so even if you undo those changes, they'll come back. @mishraabhinn.
> 
> I don’t get this. How automatically?

https://github.com/TheAlgorithms/C-Plus-Plus/pull/1535/commits/b8dd0a6aaeb56ce7f9c8372146bde518c9ef7376
https://github.com/TheAlgorithms/C-Plus-Plus/pull/1535/commits/927ff99ef062f391c60036dee516caca5004800f
https://github.com/TheAlgorithms/C-Plus-Plus/pull/1535/commits/ddaba3b77092202cc831726870d33add736872ba
https://github.com/TheAlgorithms/C-Plus-Plus/pull/1535/commits/f011de038b86530c28987f4d443d57a45ccdba7d
https://github.com/TheAlgorithms/C-Plus-Plus/pull/1535/commits/2c4cb52b4288bb34cf3abd8bb0c8909d4ae1e5f2

2021-07-20 03:52 UTC, Panquesito7 reviewed
Almost there! 😄

2021-07-20 03:52 UTC, Panquesito7 commented on search/floyd_cycle_detection_algo.cpp
> +    // Test 3
```suggestion
    // 3rd test
```

2021-07-20 17:15 UTC, Panquesito7 approved these changes
LGTM. Thank you for your contribution! 😄🎉

2021-07-21 19:07 UTC, closed without merging