feat: Add `count_of_trailing_ciphers_in_factorial_n`
TheAlgorithms/C-Plus-Plus pull request #1543
Opened 2021-07-21 08:44 UTC by Swastyy

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-07-21 19:45 UTC, Panquesito7 requested changes
Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + * @brief Test implementations
```suggestion
 * @brief Self-test implementations
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + * @brief Program to count number of ciphers in `n!`(https://www.tutorialspoint.com/count-trailing-zeros-in-factorial-of-a-number-in-cplusplus).
```suggestion
 * @brief [Count the number of ciphers](https://www.tutorialspoint.com/count-trailing-zeros-in-factorial-of-a-number-in-cplusplus) in `n!` implementation
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + * the zeroes at the end of factorial of that number.
```suggestion
 * Given an integer number as input. The goal is to find the number of trailing zeroes in the factorial calculated for
 * that number. A factorial of a number N is a product of all numbers in the range [1, N].

 * We know that we get a trailing zero only if the number is multiple of 10 or has a factor pair (2,5). In all factorials of
 * any number greater than 5, we have many 2s more than 5s in the prime factorization of that number. Dividing a
 * number by powers of 5 will give us the count of 5s in its factors. So, the number of 5s will tell us the number of trailing zeroes.
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + * @brief Program to count number of ciphers in `n!`(https://www.tutorialspoint.com/count-trailing-zeros-in-factorial-of-a-number-in-cplusplus).
```suggestion
 * @brief Functions for the [Count the number of ciphers](https://www.tutorialspoint.com/count-trailing-zeros-in-factorial-of-a-number-in-cplusplus) in `n!` implementation
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +namespace numberOfCiphersInFactorialN {
```suggestion
namespace count_of_trailing_ciphers_in_factorial_n {
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +
```suggestion
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +}  // namespace numberOfCiphersInFactorialN
```suggestion
}  // namespace count_of_trailing_ciphers_in_factorial_n
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    assert(bit_manipulation::numberOfCiphersInFactorialN::numberOfCiphersInFactorialN(395) == 97);
```suggestion
    assert(bit_manipulation::count_of_trailing_ciphers_in_factorial_n::numberOfCiphersInFactorialN(395) == 97);
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    // Test 1
```suggestion
    // 1st test
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    // Test 2
```suggestion
    // 2nd test
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    assert(bit_manipulation::numberOfCiphersInFactorialN::numberOfCiphersInFactorialN(977) == 242);
```suggestion
    assert(bit_manipulation::count_of_trailing_ciphers_in_factorial_n::numberOfCiphersInFactorialN(977) == 242);
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    // Test 3
```suggestion
    // 3rd test
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    assert(bit_manipulation::numberOfCiphersInFactorialN::numberOfCiphersInFactorialN(871) == 215);
```suggestion
    assert(bit_manipulation::count_of_trailing_ciphers_in_factorial_n::numberOfCiphersInFactorialN(871) == 215);
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    // Test 4
```suggestion
    // 4th test
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    // Test 5
```suggestion
    // 5th test
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    assert(bit_manipulation::numberOfCiphersInFactorialN::numberOfCiphersInFactorialN(239) == 57);
```suggestion
    assert(bit_manipulation::count_of_trailing_ciphers_in_factorial_n::numberOfCiphersInFactorialN(239) == 57);
```

2021-07-21 19:45 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> +    assert(bit_manipulation::numberOfCiphersInFactorialN::numberOfCiphersInFactorialN(0) == 0);
```suggestion
    assert(bit_manipulation::count_of_trailing_ciphers_in_factorial_n::numberOfCiphersInFactorialN(0) == 0);
```

2021-07-25 17:50 UTC, Panquesito7 reviewed
Almost there! 😄

2021-07-25 17:50 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + in `n!` implementation
```suggestion
 * @brief [Count the number of 
 * ciphers](https://www.tutorialspoint.com/count-trailing-zeros-in-factorial-of-a-number-in-cplusplus) in `n!` implementation
```

2021-07-25 17:50 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + number of 5s will tell us the number of trailing zeroes.
```suggestion
 * We know that we get a trailing zero only if the number is multiple of 10 or has a factor pair (2,5). In all factorials of
 * any number greater than 5, we have many 2s more than 5s in the prime factorization of that number. Dividing a
 * number by powers of 5 will give us the count of 5s in its factors. So, the number of 5s will tell us the number of trailing zeroes.
```

2021-07-25 17:50 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + * @param n, Number for which `n!` ciphers are returned
```suggestion
 * @param n number for which `n!` ciphers are returned
```

2021-07-25 17:50 UTC, Panquesito7 commented on bit_manipulation/count_of_trailing_ciphers_in_factorial_n.cpp
> + * @brief Function to count the number of trailing ciphers.
```suggestion
 * @brief Function to count the number of the trailing ciphers
```

2021-07-25 18:31 UTC, Panquesito7 approved these changes
LGTM. Great work, @Swastyy; thank you! 😄🎉

2021-07-25 18:56 UTC, mishraabhinn requested changes
![Screenshot 2021-07-26 at 00 25 19](https://user-images.githubusercontent.com/49574460/126910160-d66d9632-f648-458f-b2c7-5c680235ce02.png)
I till now don't get how the files getting deleted and changed. If you merge them @Panquesito7 this will affect repo. Github action will change files when you have made changes in that files than only.

2021-07-25 20:19 UTC, Panquesito7 commented
> GitHub action will change files when you have made changes in that files then only

It doesn't always do that. It sometimes edits other files as they are not to our standards, and the CI wants to fix it. @ayaankhan98, any ideas of what we should do? Thanks.

2021-07-29 12:36 UTC, Swastyy commented
> ![Screenshot 2021-07-26 at 00 25 19](https://user-images.githubusercontent.com/49574460/126910160-d66d9632-f648-458f-b2c7-5c680235ce02.png)
> I till now don't get how the files getting deleted and changed. If you merge them @Panquesito7 this will affect repo. Github action will change files when you have made changes in that files than only.

Now they aren't here. 😕

2021-07-29 12:44 UTC, mishraabhinn commented
> > ![Screenshot 2021-07-26 at 00 25 19](https://user-images.githubusercontent.com/49574460/126910160-d66d9632-f648-458f-b2c7-5c680235ce02.png)
> > I till now don't get how the files getting deleted and changed. If you merge them @Panquesito7 this will affect repo. Github action will change files when you have made changes in that files than only.
> 
> Now they aren't here. 😕

And, how you fixed that?

2021-07-29 12:46 UTC, mishraabhinn commented
> > > ![Screenshot 2021-07-26 at 00 25 19](https://user-images.githubusercontent.com/49574460/126910160-d66d9632-f648-458f-b2c7-5c680235ce02.png)
> > > I till now don't get how the files getting deleted and changed. If you merge them @Panquesito7 this will affect repo. Github action will change files when you have made changes in that files than only.
> > 
> > 
> > Now they aren't here. 😕
> 
> And, how you fixed that?

You removed that files from your branch na. thats why that deleted icon was coming and now you copied these same file and pasted at the exact location na?:monocle_face:

2021-07-29 12:49 UTC, Swastyy commented
> > You removed that files from your branch na. thats why that deleted icon was coming and now you copied these same file and pasted at the exact location na?🧐

Nai nai 😂

2021-07-29 12:50 UTC, Swastyy commented
> And, how you fixed that?
I was just trying to fix this https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind
![image](https://user-images.githubusercontent.com/64654203/127494857-dc9e1c34-1ae7-4f8d-9408-6cdbcbc45019.png)
You did something ryt?

2021-07-29 13:01 UTC, mishraabhinn commented
> > And, how you fixed that?
> > I was just trying to fix this https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind
> > ![image](https://user-images.githubusercontent.com/64654203/127494857-dc9e1c34-1ae7-4f8d-9408-6cdbcbc45019.png)
> > You did something ryt?

Why check_prime.cpp is there? Something majorly wrong in your way of doing commit. You are not pulling changes, i guess.

2021-07-29 13:04 UTC, Swastyy commented
> Why check_prime.cpp is there?
Idk 😕 
> Something majorly wrong in your way of doing commit. You are not pulling changes, i guess.
I usually click on fetch and merge button since I use gitpod here is it required to pull from gitpod's command line too?

2021-07-29 13:10 UTC, mishraabhinn commented
> > Why check_prime.cpp is there?
> > Idk 😕
> > Something majorly wrong in your way of doing commit. You are not pulling changes, i guess.
> > I usually click on fetch and merge button since I use gitpod here is it required to pull from gitpod's command line too?

Lets approve this up.  As changes are made by github action bot and they seems to be correct and valid. Nice work @Swastyy :partying_face: . You can try using vs / terminal

2021-07-29 13:11 UTC, mishraabhinn approved these changes

2021-07-29 16:39 UTC, Panquesito7 approved these changes

2021-07-29 16:41 UTC, merged