feat: Add `n_bonacci.cpp` in math section
TheAlgorithms/C-Plus-Plus pull request #1544
Opened 2021-07-21 08:57 UTC by Swastyy

#### Description of Change Created n _ bonacci series upto given m number of terms.

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-07-21 20:33 UTC, Panquesito7 requested changes
Good work! 👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

2021-07-21 20:33 UTC, Panquesito7 commented on math/n_bonacci.cpp
> + * @author [Swastika Gupta](https://github.com/swastyy)
```suggestion
 * @author [Swastika Gupta](https://github.com/Swastyy)
```

2021-07-21 20:33 UTC, Panquesito7 commented on math/n_bonacci.cpp
> + * @brief Finds the N-Bonacci series for the `n` parameter value and `m` parameter terms.
```suggestion
 * @brief Finds the N-Bonacci series for the `n` parameter value and `m` parameter terms
```

2021-07-21 20:33 UTC, Panquesito7 commented on math/n_bonacci.cpp
> +std::vector<int> N_bonacci(int n, unsigned int m) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). 🙂

2021-07-21 20:33 UTC, Panquesito7 commented on math/n_bonacci.cpp
> +}
```suggestion
}

```

2021-07-22 18:26 UTC, Panquesito7 requested changes

2021-07-22 18:26 UTC, Panquesito7 commented on math/n_bonacci.cpp
> + */
```suggestion
 */

```

2021-07-25 18:14 UTC, Panquesito7 approved these changes
LGTM. Great work, @Swastyy; thank you! 😄👍🎉

2021-07-29 12:34 UTC, Swastyy commented
@mishraabhinn See this PR has only my file. Check this out.

2021-07-29 16:37 UTC, Panquesito7 reviewed
If nobody has any objections, I'll merge this PR later today.

2021-07-29 16:48 UTC, mishraabhinn approved these changes

2021-07-29 17:29 UTC, merged