Karatsuba algorithm
TheAlgorithms/C-Plus-Plus pull request #1550
Opened 2021-07-30 12:00 UTC by Swastyy

#### Description of Change Karatsuba algorithm for fast multiplication
Fixes issue #1507 

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-07-30 17:30 UTC, Panquesito7 requested changes
Please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/pull/1550/checks?check_run_id=3201622943) warnings.

2021-08-01 14:06 UTC, Panquesito7 requested changes
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Swastyy/C-Plus-Plus/actions

2021-08-05 17:11 UTC, Panquesito7 commented on divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
> +#include <cstring>   /// for string
What's the difference between these two? Why not only use one?

2021-08-05 18:14 UTC, Panquesito7 commented on divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
> +        result = '1' + result;  // adding 1 incase of overflow
```suggestion
    if (carry) {
        result = '1' + result;  // adding 1 incase of overflow
    }
```

2021-08-05 18:14 UTC, Panquesito7 commented on divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
> +    std::cout << "Test 1... ";
```suggestion
    std::cout << "1st test... ";
```

2021-08-05 18:14 UTC, Panquesito7 commented on divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
> +    std::cout << "Test 2... ";
```suggestion
    std::cout << "2nd test... ";
```

2021-08-05 18:14 UTC, Panquesito7 commented on divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
> +    std::cout << "Test 3... ";
```suggestion
    std::cout << "3rd test... ";
```

2021-08-05 18:25 UTC, Panquesito7 approved these changes
LGTM. Thank you for your contribution! 😄👍🎉

2021-08-09 12:24 UTC, ayaankhan98 approved these changes

2021-08-09 12:59 UTC, mishraabhinn approved these changes

2021-08-09 13:00 UTC, merged