Create selection_sort_recursive.cpp
TheAlgorithms/C-Plus-Plus pull request #1578
Opened 2021-08-29 20:10 UTC by Tushar-K24

#### Created selection_sort_recursive.cpp

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-09-01 16:22 UTC, Panquesito7 requested changes
Woah, amazing work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Tushar-K24/C-Plus-Plus/actions

2021-09-01 16:22 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +}
```suggestion
}

```

2021-09-01 16:22 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    test(); // execute the test
```suggestion
    test();  // run self-test implementations
```

2021-09-01 16:22 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> + * C++ program to sort an array using a recursive selection sort algorithm
Please provide more details about the algorithm itself, how does it work, etc.. You can take the description of Wikipedia but adjust it to match our standards. 🙂

2021-09-02 22:41 UTC, Panquesito7 requested changes

2021-09-02 22:41 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> + * solves recursively for the remaining unsorted list.
```suggestion
```

2021-09-02 22:41 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> + * C++ program to sort an array using a recursive selection sort algorithm
```suggestion
 * The selection sort algorithm divides the input list into two parts: a sorted sublist of items which is built up from 
 * left to right at the front (left) of the list, and a sublist of the remaining unsorted items that occupy the rest 
 * of the list. Initially, the sorted sublist is empty, and the unsorted sublist is the entire input list. The algorithm 
 * proceeds by finding the smallest (or largest, depending on the sorting order) element in the unsorted sublist, 
 * exchanging (swapping) it with the leftmost unsorted element (putting it in sorted order), and moving the sublist 
 * boundaries one element to the right.
 * 
 * ### Implementation
 * FindMinIndex
 * This function finds the minimum element of the array(list) recursively by simply comparing the minimum element of
 * array reduced size by 1 and compares it to the last element of the array to find the minimum of the whole array. 
 * 
 * SelectionSortRecursive
 * Just like selection sort, it divides the list into two parts (i.e.: sorted and unsorted) and finds the minimum of the
 * unsorted array. By calling the `FindMinIndex` function, it swaps the minimum element with the first element of the list, and then
 * solves recursively for the remaining unsorted list.
```

2021-09-03 17:45 UTC, Panquesito7 requested changes

2021-09-03 17:45 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +
```suggestion
```

2021-09-03 17:45 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +namespace find_min_index {
```suggestion
namespace selection_sort_recursive {
```

2021-09-03 17:45 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +}  // namespace find_min_index
```suggestion
```

2021-09-03 17:45 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +namespace selection_sort_recursive {
```suggestion
```

2021-09-03 18:46 UTC, Panquesito7 requested changes
Almost there! 😄

2021-09-03 18:46 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +namespace selection_sort_recursive {
```suggestion
```

2021-09-03 18:46 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +}  // namespace find_min_index
```suggestion
```

2021-09-03 20:30 UTC, Panquesito7 reviewed
Almost there! 😄

2021-09-03 20:30 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    std::cout << "Test 1... ";
```suggestion
    std::cout << "1st test... ";
```

2021-09-03 20:30 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    std::cout << "Test 2... ";
```suggestion
    std::cout << "2nd test... ";
```

2021-09-03 20:30 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    std::cout << "Test 3... ";
```suggestion
    std::cout << "3rd test... ";
```

2021-09-03 20:30 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    std::cout << "Test 4... ";
```suggestion
    std::cout << "4th test... ";
```

2021-09-04 17:10 UTC, G3N3R4LE4RL submitted a review, later dismissed

2021-09-05 16:08 UTC, Panquesito7 reviewed
Almost there! 😄

2021-09-05 16:08 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    std::cout << "Test 3... ";
```suggestion
    std::cout << "3rd test... ";
```

2021-09-05 16:08 UTC, Panquesito7 commented on sorting/selection_sort_recursive.cpp
> +    std::cout << "Test 4... ";
```suggestion
    std::cout << "4th test... ";
```

2021-09-05 16:58 UTC, Panquesito7 approved these changes
Awesome work, @Tushar-K24! It's been great for your first contribution here! Thank you for your contribution! 😄👍🎉

2021-09-05 17:12 UTC, ayaankhan98 commented on sorting/selection_sort_recursive.cpp
> +uint64_t findMinIndex(std::vector<T> &in_arr, uint64_t current_position = 0) {
```suggestion
uint64_t findMinIndex(const std::vector<T> &in_arr, uint64_t current_position = 0) {
```

2021-09-05 17:41 UTC, ayaankhan98 approved these changes
LGTM :+1:

2021-09-05 17:45 UTC, mishraabhinn approved these changes

2021-09-05 17:50 UTC, merged

2021-09-05 17:52 UTC, Panquesito7 commented
@ayaankhan98, next time, please wait until all the requested reviewers review this PR. 🙂

2021-09-05 17:53 UTC, ayaankhan98 commented
> @ayaankhan98, next time, please wait until all the requested reviewers review this PR.

Ahh! no problem with that, I was just going with 2 reviewer policy.

2021-09-05 17:55 UTC, Panquesito7 commented
> > @ayaankhan98, next time, please wait until all the requested reviewers review this PR.
> 
> Ahh! no problem with that, I was just going with 2 reviewer policy. By the way we had 3 approved reviews on this PR.

Yeah. It is because a friend of mine will start helping with reviewing PRs now. Thanks anyways. 🙂