Create c++_code_fixes
TheAlgorithms/C-Plus-Plus pull request #1584
Opened 2021-09-04 06:32 UTC by Bhagyanekraje

In this file I have written a c++ code to find the reverse of a string without using functions.

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-09-04 20:21 UTC, mishraabhinn requested changes
[Refer](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)
@Bhagyanekraje

2021-09-04 20:22 UTC, mishraabhinn requested changes

2021-09-04 20:22 UTC, mishraabhinn commented on search/linear_search.cpp
> +void main() {
Why?

2021-09-05 07:18 UTC, mishraabhinn commented
@Bhagyanekraje Please do check the relevant checkbox, and please do refer to the contribution guidelines before commiting. For any question you can ask here or  do message your doubts on [Gitter](https://gitter.im/TheAlgorithms) Thanks.  
![Screenshot 2021-09-05 at 12 44 59](https://user-images.githubusercontent.com/49574460/132118761-3439c35c-d47f-4059-a0dd-86f27e1990e0.png)

2021-09-05 08:57 UTC, Bhagyanekraje reviewed
> @Bhagyanekraje Please do check the relevant checkbox, and please do refer to the contribution guidelines before commiting. For any question you can ask here or do message your doubts on [Gitter](https://gitter.im/TheAlgorithms) Thanks.
> ![Screenshot 2021-09-05 at 12 44 59](https://user-images.githubusercontent.com/49574460/132118761-3439c35c-d47f-4059-a0dd-86f27e1990e0.png)

ok sir

2021-09-13 17:23 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. Let us know if you need any help in our [**Discord server**](https://discord.gg/c7MnfGFGa6).

2021-10-30 00:05 UTC, closed without merging