Add Travelling Salesman Problem(Naive Approach)
TheAlgorithms/C-Plus-Plus pull request #1590
Opened 2021-09-04 21:10 UTC by Mayank17M

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-09-05 05:17 UTC, ayaankhan98 requested changes
Hey, Thanks for your contribution. We request you to follow [contribution guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

2021-09-05 11:02 UTC, Mayank17M commented
Made some changes. 
@ayaankhan98 Please check if it is appropriate now. Thanks!

2021-09-05 11:04 UTC, ayaankhan98 commented on graph/travelling_salesman_problem.cpp
> +// This is the naive approach to solve this problem.
use doxygen documentation guidelines.

2021-09-05 11:05 UTC, ayaankhan98 commented on graph/travelling_salesman_problem.cpp
> +// https://en.wikipedia.org/wiki/Travelling_salesman_problem
you can use markdown format to reference links

2021-09-05 11:05 UTC, ayaankhan98 commented on graph/travelling_salesman_problem.cpp
> +using namespace std;
It's not a good practice to use `using namespace std;`

2021-09-05 11:06 UTC, ayaankhan98 commented on graph/travelling_salesman_problem.cpp
> +}
Tests are missing.

2021-09-05 11:06 UTC, ayaankhan98 requested changes
Please follow [contribution guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

Thanks.

2021-09-05 11:08 UTC, ayaankhan98 commented on graph/travelling_salesman_problem.cpp
> +int TravellingSalesmanProblem(vector<vector<int>> cities, int src, int V) {
use reference to pass large structures like vectors or 2-D vectors.

2021-09-05 11:08 UTC, ayaankhan98 commented on graph/travelling_salesman_problem.cpp
> +int TravellingSalesmanProblem(vector<vector<int>> cities, int src, int V) {
or const references as per the need.

2021-09-05 17:52 UTC, Panquesito7 requested changes
Thanks for reviewing, @ayaankhan98! 😄
@Mayank17M, in case you are confused or don't know what to do, you can check the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program). I hope that helps. Let us know if you need any more help. 🙂

2021-09-05 20:08 UTC, Mayank17M commented
Thankyou @Panquesito7 , I'll make the necessary changes.
Thanks! :)

2021-09-07 19:32 UTC, Panquesito7 requested changes
Great work! 😄👍

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> + * TSP can be modelled as an undirected weighted graph, such that cities are the
```suggestion
 * TSP can be modeled as an undirected weighted graph, such that cities are the
```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +#include <limits.h>
Please use `limits` or `climits` instead.

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +#include <vector>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +
```suggestion
```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +void tests() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
static void tests() {
```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +}
```suggestion
}

```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +/** Main function */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    tests();
```suggestion
    tests();  // run self-test implementations
```

2021-09-07 19:32 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    int min_path = INT_MAX;
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). 🙂

2021-09-09 07:04 UTC, Mayank17M commented
I think all the requested changes have been covered. 
Please review @Panquesito7

2021-09-10 01:41 UTC, Panquesito7 requested changes
Almost there! Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Mayank17M/C-Plus-Plus/actions

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> + * (https://en.wikipedia.org/wiki/Travelling_salesman_problem)
```suggestion
 * (https://en.wikipedia.org/wiki/Travelling_salesman_problem) implementation
```

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +
```suggestion
#include <limits>  /// for limits of integral types
```

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +
```suggestion
```

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +        int curr_weight = 0;
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). **Let me know if you need any help with that**.

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    std::cout << "Test 1 Passed..." << std::endl;
```suggestion
    std::cout << "1st test passed..." << std::endl;
```

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    std::cout << "Test 2 Passed..." << std::endl;
```suggestion
    std::cout << "2nd test passed..." << std::endl;
```

2021-09-10 01:41 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    std::cout << "Test 3 Passed..." << std::endl;
```suggestion
    std::cout << "3rd test passed..." << std::endl;
```

2021-09-10 18:40 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    std::cout << graph::TravellingSalesmanProblem(&cities, 0, V);
```suggestion
    std::cout << graph::TravellingSalesmanProblem(&cities, 0, V) << std::endl;
```

2021-09-10 21:38 UTC, Panquesito7 requested changes
This is all that needs to be addressed, and your PR will be merged! 🎉

2021-09-10 21:38 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +#include <vector>           /// header for std::vector
```suggestion
#include <vector>           /// for std::vector
```

2021-09-10 21:38 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +
```suggestion
```

2021-09-10 21:38 UTC, Panquesito7 commented on graph/travelling_salesman_problem.cpp
> +    for (int i = 0; i < V; i++) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). **Let me know if you need any help**. 🙂

2021-09-11 08:02 UTC, Mayank17M commented
Addressed all the requested changes. Please review. Thanks!

2021-09-12 16:09 UTC, Panquesito7 approved these changes
Awesome work, @Mayank17M! It's been great for your first contribution here! We hope you keep contributing! 😄👍🎉

2021-09-12 16:20 UTC, amino19 commented
@Panquesito7: Here's the output, goes in:

![image](https://user-images.githubusercontent.com/75872316/132995133-479f5aac-7334-4d9b-b528-e71de471fcf1.png)

Is it shows correct?

2021-09-12 16:27 UTC, Panquesito7 commented
> @Panquesito7: Here's the output, goes in:
> 
> ![image](https://user-images.githubusercontent.com/75872316/132995133-479f5aac-7334-4d9b-b528-e71de471fcf1.png)
> 
> Is it shows correct?

That looks correct for me. @Mayank17M, does that look correct?

2021-09-12 16:58 UTC, Mayank17M commented
Yep, that's correct :)

2021-09-12 17:07 UTC, amino19 approved these changes
@Mayank17M: LGTM! :partying_face:

2021-09-12 17:18 UTC, Panquesito7 commented
Thanks for reviewing @amino19! 😄

2021-09-12 17:19 UTC, merged