feat. Add SHA-1 hashing algorithm
TheAlgorithms/C-Plus-Plus pull request #1609
Opened 2021-09-19 20:59 UTC by tGautot

#### Description of Change
Added my own implementation of the SHA-1 Algorithm/Protocol to the hashing directory

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

2021-09-19 21:49 UTC, Panquesito7 requested changes

2021-09-19 21:49 UTC, Panquesito7 commented on hashing/sha1.cpp
> +}
Missing an endline.

2021-09-24 16:40 UTC, Panquesito7 approved these changes
Awesome work @tGautot! 🚀 Thank you for your contribution! 😄👍🎉

2021-09-24 17:33 UTC, amino19 approved these changes
@tGautot: Looks good! : )

2021-09-24 19:59 UTC, merged