Update linear_search.cpp
TheAlgorithms/C-Plus-Plus pull request #1641
Opened 2021-10-02 12:36 UTC by ritikaa17

Update readability of code

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-01-01 15:14 UTC, Qannaf approved these changes

2022-01-19 20:52 UTC, arunabh-cloud reviewed
Hi,
May I suggest some improvements to this code? 
Thanks.

2022-01-19 21:05 UTC, arunabh-cloud commented on search/linear_search.cpp
>      std::cout << "\nEnter the Array of " << size << " numbers : ";
There should be a check for the user entering a negative number or a very large number as "size" of the array of numbers.

2022-01-20 14:24 UTC, Panquesito7 submitted a review, later dismissed
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-20 18:21 UTC, mishraabhinn requested changes
Can you provide the test cases also @ritikaa17. Thanks

2022-01-20 21:36 UTC, mishraabhinn approved these changes

2022-01-27 15:06 UTC, merged