feat: Fast method for set bit calculation
TheAlgorithms/C-Plus-Plus pull request #1670
Opened 2021-10-05 04:55 UTC by Rishikesh-kumar-7258

#### Description of Change
Added a fast method for set bit calculation.

Contributors guide: https://github.com/TheAlgorithms/C-Plus-Plus/CONTRIBUTING.md

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, the test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-10-06 07:05 UTC, Rishikesh-kumar-7258 commented
why is this code not getting accepted?
can you tell me so I could change that...

2021-10-17 03:58 UTC, Rishikesh-kumar-7258 commented
I tried to follow the template according to that file.
since both the files address the same problem, there wasn't much to change.
I changed the algorithm and other things neccessary.

2021-10-31 01:32 UTC, Panquesito7 reviewed
> I tried to follow the template according to that file. since both the files address the same problem, there wasn't much to change. I changed the algorithm and other things neccessary.

What if we rename this file to `count_of_set_bits2.cpp`?

2021-10-31 05:24 UTC, Rishikesh-kumar-7258 commented
No problem. New name is fine.

2021-11-01 00:42 UTC, Panquesito7 commented
> No problem. New name is fine.

Feel free to change it, then. 🙂

2021-11-05 17:54 UTC, Panquesito7 requested changes
Can you rename the file to `count_of_set_bits_fast2.cpp`, please?

2021-11-06 04:23 UTC, Rishikesh-kumar-7258 commented
I have changed the name.  Please check it once.

On Fri, 5 Nov 2021 at 23:25, David Leal ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Can you rename the file to count_of_set_bits_fast2.cpp, please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/1670#pullrequestreview-799182433>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRTPOELGHEL27LUPFF6JP3UKQK7VANCNFSM5FK3TKFQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-07 02:37 UTC, Panquesito7 commented on bit_manipulation/count_of_set_bits_fast2.cpp
> +std::uint64_t countSetBits(int n) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). *Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6).** 😃

2022-01-10 00:07 UTC, closed without merging