feat: Sieve of eratosthenes
TheAlgorithms/C-Plus-Plus pull request #1730
Opened 2021-10-12 21:00 UTC by thechubbypanda

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1730"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-11-04 02:50 UTC, Panquesito7 reviewed
Almost there! 😄

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +void test() {
```suggestion
static void test() {
```

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +/**
```suggestion
/**
 * @namespace math
 * @brief Mathematical algorithms
 */
namespace math {
/**
```

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +}
```suggestion
}
}  // namespace math
```

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +    test();
```suggestion
    test();  // run self-test implementations
```

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +    sieve(&primes);
```suggestion
    math::sieve(&primes);
```

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +    sieve(&primes);
```suggestion
    math::sieve(&primes);
```

2021-11-04 02:50 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +        print_primes(primes);
```suggestion
        math::print_primes(primes);
```

2021-11-04 16:15 UTC, Panquesito7 commented on math/eratosthenes.cpp
> +    assert(primes[9] == false);
```suggestion
    assert(primes[9] == false);

    std::cout << "All tests have successfully passed!\n";
```

2021-11-04 16:34 UTC, Panquesito7 submitted a review, later dismissed
Awesome work! You've done amazing work, and it's been your
first contribution here! We hope you keep contributing! 😄👍🎉

After this PR is merged, you can ask for the
contributor role in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 🚀

2021-11-04 19:12 UTC, ayaankhan98 requested changes
```
test.cpp: In function ‘void math::sieve(std::vector<bool>*)’:
test.cpp:38:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<bool>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   38 |     for (int n = 2; n < vec->size(); n++) {
      |                     ~~^~~~~~~~~~~~~
test.cpp:39:46: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<bool>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   39 |         for (int multiple = n << 1; multiple < vec->size(); multiple += n) {
      |                                     ~~~~~~~~~^~~~~~~~~~~~~
test.cpp: In function ‘void math::print_primes(const std::vector<bool>&)’:
test.cpp:51:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<bool>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   51 |     for (int i = 0; i < primes.size(); i++) {
      |                     ~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

shell returned 1
```

2021-11-07 21:32 UTC, Panquesito7 approved these changes
Awesome work! You've done amazing work, and it's been your
first contribution here! We hope you keep contributing! 😄👍🎉

After this PR is merged, you can ask for the
contributor role in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 🚀

2021-11-07 21:33 UTC, Panquesito7 commented
Could you please review again, @ayaankhan98? Thanks. 😄

2022-04-09 09:10 UTC, thechubbypanda commented
@Panquesito7 What's the deal with this?

2022-04-09 09:37 UTC, mishraabhinn approved these changes

2023-06-16 08:03 UTC, realstealthninja commented
should we close this?

2023-06-16 21:21 UTC, Panquesito7 commented
Yep, already done in #2442.

2023-06-16 21:21 UTC, closed without merging