feat: Created composite Simpson's numerical integration method
TheAlgorithms/C-Plus-Plus pull request #1773
Opened 2021-10-20 12:38 UTC by ggkogkou

#### Description of Change
Created the composite Simpson's numerical method for integrals approximation (wiki: https://en.wikipedia.org/wiki/Simpson%27s_rule#Composite_Simpson's_rule). 

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Numerical method for integral evaluation implementation

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-10-31 16:18 UTC, ayaankhan98 requested changes
Thanks for your contribution. Please fix the issue below.
```
test.cpp: In function ‘void test(int, double, double, double, bool)’:
test.cpp:96:87: error: ‘f’ was not declared in this scope; did you mean ‘numerical_methods::simpson_method::f’?
   96 |     double result_f = numerical_methods::simpson_method::evaluate_by_simpson(N, h, a, f);
      |                                                                                       ^
      |                                                                                       numerical_methods::simpson_method::f
test.cpp:68:8: note: ‘numerical_methods::simpson_method::f’ declared here
   68 | double f(double x){
      |        ^
test.cpp:100:87: error: ‘g’ was not declared in this scope; did you mean ‘numerical_methods::simpson_method::g’?
  100 |     double result_g = numerical_methods::simpson_method::evaluate_by_simpson(N, h, a, g);
      |                                                                                       ^
      |                                                                                       numerical_methods::simpson_method::g
test.cpp:72:8: note: ‘numerical_methods::simpson_method::g’ declared here
   72 | double g(double x){
      |        ^
test.cpp:104:87: error: ‘k’ was not declared in this scope; did you mean ‘numerical_methods::simpson_method::k’?
  104 |     double result_k = numerical_methods::simpson_method::evaluate_by_simpson(N, h, a, k);
      |                                                                                       ^
      |                                                                                       numerical_methods::simpson_method::k
test.cpp:76:8: note: ‘numerical_methods::simpson_method::k’ declared here
   76 | double k(double x){
      |        ^
test.cpp:108:87: error: ‘l’ was not declared in this scope; did you mean ‘numerical_methods::simpson_method::l’?
  108 |     double result_l = numerical_methods::simpson_method::evaluate_by_simpson(N, h, a, l);
      |                                                                                       ^
      |                                                                                       numerical_methods::simpson_method::l
test.cpp:80:8: note: ‘numerical_methods::simpson_method::l’ declared here
   80 | double l(double x){
      |        ^

shell returned 1
```

2021-10-31 16:22 UTC, Panquesito7 reviewed
Everything else is looking great! 🚀 Just fix the errors mentioned by @ayaankhan98 above, please. Let us know if you need any help! 🙂

2021-10-31 16:22 UTC, Panquesito7 commented on numerical_methods/composite_simpson_rule.cpp
> +double numerical_methods::simpson_method::evaluate_by_simpson(int N, double h, double a, std::function<double (double)> func){
Missing function documentation.

2021-10-31 16:22 UTC, Panquesito7 commented on numerical_methods/composite_simpson_rule.cpp
> +    test(N, h, a, b, used_argv_parameters); /// run self-test implementations
```suggestion
    test(N, h, a, b, used_argv_parameters);  // run self-test implementations
```

2021-10-31 16:45 UTC, ggkogkou commented
Done

2021-11-01 02:11 UTC, Panquesito7 approved these changes
LGTM 🚀 Please review, @ayaankhan98. Thanks. 🙂

2021-11-03 11:23 UTC, ayaankhan98 approved these changes
:+1:

2021-11-03 18:22 UTC, merged