feat: binary exponentiation
TheAlgorithms/C-Plus-Plus pull request #1805
Opened 2021-10-28 16:14 UTC by jay-tux

#### Description of Change
Added binary exponentiation algorithm

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: added binary exponentiation

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-10-30 01:33 UTC, Panquesito7 commented on divide_and_conquer/binary_exponentiation.cpp
> +#include <cassert>  /// for assert
```suggestion
#include <iostream> /// for IO operations
#include <cassert>  /// for assert
```

2021-10-30 01:33 UTC, Panquesito7 commented on divide_and_conquer/binary_exponentiation.cpp
> +    }
```suggestion
    }
    std::cout << "All tests have successfully passed!\n";
```

2021-10-30 01:44 UTC, Panquesito7 commented
A question: is the same algorithm as [**this**](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/binary_exponent.cpp) algorithm?
If so, we might have to rename this to `binary_exponentiation2.cpp`.

2021-10-30 11:58 UTC, jay-tux commented
My bad. It seems that is the case.
Didn't check that directory as issue #1734 mentions it under divide and conquer.
Does this mean either of the two algorithms have to move to another directory?

2021-10-31 01:29 UTC, Panquesito7 commented
> My bad. It seems that is the case. Didn't check that directory as issue #1734 mentions it under divide and conquer. Does this mean either of the two algorithms have to move to another directory?

No, it's totally fine as-is 😄 Let us rename this file to `binary_exponentiation2.cpp`.

2021-11-01 10:07 UTC, jay-tux commented
Renamed it!

2021-11-01 14:00 UTC, Panquesito7 requested changes

2021-11-01 14:00 UTC, Panquesito7 commented on divide_and_conquer/CMakeLists.txt
> +file( GLOB APP_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} binary_exponentiation2.cpp )
```suggestion
file( GLOB APP_SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.cpp )
```

2021-11-01 14:42 UTC, Panquesito7 submitted a review, later dismissed
Awesome work! You've done amazing work, and it's been your
first contribution here! We hope you keep contributing! 😄👍🎉

After this PR is merged, you can ask for the
contributor role in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 🚀

2021-11-01 14:44 UTC, amino19 approved these changes

2021-11-01 15:04 UTC, ayaankhan98 approved these changes

2021-11-01 15:06 UTC, ayaankhan98 reviewed
Code looks good but windows CI is failing.

2021-11-01 15:21 UTC, Panquesito7 commented
Hmm, no idea why it's failing. Any ideas?

2021-11-03 18:44 UTC, Panquesito7 requested changes
Okay, I found the issue here Okay, I found the error here https://github.com/TheAlgorithms/C-Plus-Plus/runs/4096578335?check_suite_focus=true#step:4:250 could you please fix it? Let us know if you need any help! Thanks. 🙂

2021-11-08 13:41 UTC, jay-tux commented
> Okay, I found the issue here Okay, I found the error here https://github.com/TheAlgorithms/C-Plus-Plus/runs/4096578335?check_suite_focus=true#step:4:250 could you please fix it? Let us know if you need any help! Thanks. slightly_smiling_face

I don't thing that's the issue. It points to a warning but it actually compiles to an executable afterwards, so that couldn't be the issue.

2021-11-08 18:30 UTC, Panquesito7 commented
> > Okay, I found the issue here Okay, I found the error here https://github.com/TheAlgorithms/C-Plus-Plus/runs/4096578335?check_suite_focus=true#step:4:250 could you please fix it? Let us know if you need any help! Thanks. slightly_smiling_face
> 
> I don't thing that's the issue. It points to a warning but it actually compiles to an executable afterwards, so that couldn't be the issue.

It is more of a warning, not an error, I think. But there could be a loss of data there, so please try to investigate. 🙂

2023-03-29 20:15 UTC, micwoj92 commented
This branch has conflicts that must be resolved.

2023-05-07 00:10 UTC, closed without merging