fix: rewrite prime numbers using linear sieve
TheAlgorithms/C-Plus-Plus pull request #1810
Opened 2021-10-29 03:31 UTC by nella17

#### Description of Change

Rewrite math/prime_numbers.cpp using linear sieve.

#### Checklist

- [x] Added description of change
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: made change in math/prime_numbers.cpp

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1810"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-10-29 23:00 UTC, Panquesito7 approved these changes

2021-10-30 06:46 UTC, amino19 approved these changes

2021-10-30 09:15 UTC, ayaankhan98 requested changes
```
test.cpp: In function ‘std::vector<int> primes(int)’:
test.cpp:15:26: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
   15 |     for (size_t i = 2; i <= max; i++) {
      |                        ~~^~~~~~
test.cpp:20:19: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
   20 |             if (k > max)
      |                 ~~^~~~~
cc1plus: all warnings being treated as errors
```

2021-10-31 03:47 UTC, Panquesito7 approved these changes
LGTM 🚀 Please review again, @ayaankhan98.

2021-10-31 10:12 UTC, amino19 approved these changes
Looks good!

2021-10-31 16:17 UTC, ayaankhan98 approved these changes

2021-10-31 18:56 UTC, mishraabhinn approved these changes

2021-10-31 23:47 UTC, merged