feat : Implemented Inverse Fast Fourier Transform
TheAlgorithms/C-Plus-Plus pull request #1834
Opened 2021-11-02 20:10 UTC by ameyachawlaggsipu

Slightly different from fast Fourier transform
Just the om variable declared in line 40 is divided by n
and swapping the testing inputs with testing outputs .

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-11-02 23:26 UTC, Panquesito7 requested changes
Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/ameyachawlaggsipu/C-Plus-Plus/actions

2021-11-02 23:26 UTC, Panquesito7 commented on numerical_methods/Inverse_fast_fourier_transform.cpp
> + * @brief [An  inverse fast Fourier transform
```suggestion
 * @brief [An inverse fast Fourier transform
```

2021-11-02 23:26 UTC, Panquesito7 commented on numerical_methods/Inverse_fast_fourier_transform.cpp
> +              //  with 2 defined test cases
```suggestion
    test();  //  run self-test implementations
             //  with 2 defined test cases

```

2021-11-02 23:26 UTC, Panquesito7 commented on numerical_methods/Inverse_fast_fourier_transform.cpp
> +}
```suggestion
}

```

2021-11-03 17:48 UTC, Panquesito7 commented on numerical_methods/inverse_fast_fourier_transform.cpp
> +
```suggestion
```

2021-11-03 18:00 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-11-03 18:54 UTC, amino19 approved these changes

2021-11-03 19:02 UTC, ameyachawlaggsipu commented
Thank You
@ayaankhan98 
@Panquesito7

2021-11-03 19:16 UTC, merged