feat : Implemented Babylonian Method
TheAlgorithms/C-Plus-Plus pull request #1837
Opened 2021-11-04 09:26 UTC by ameyachawlaggsipu

Babylonian method is used to calculate  square roots .

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-11-04 16:18 UTC, Panquesito7 requested changes
Awesome work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/ameyachawlaggsipu/C-Plus-Plus/actions

2021-11-04 16:18 UTC, Panquesito7 commented on numerical_methods/babylonian_method.cpp
> +#include <iostream> /// for IO operations
```suggestion
#include <iostream>  /// for IO operations
```

2021-11-04 19:23 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2021-11-07 13:02 UTC, ayaankhan98 approved these changes

2021-11-07 16:36 UTC, merged