feat: add binary_insertion_sort
TheAlgorithms/C-Plus-Plus pull request #1850
Opened 2021-12-04 07:01 UTC by Siddhartha-Padhy

#### Description of Change
Sorting using Insertion sort algorithm with binary search.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Binary Insertion Sort

2021-12-05 15:46 UTC, Panquesito7 requested changes
Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Siddhartha-Padhy/C-Plus-Plus/actions

For any queries, comments, or questions, feel free to ask in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 🙂

2021-12-05 15:46 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +#include <vector>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2021-12-05 15:46 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +void test() {
```suggestion
static void test() {
```

2021-12-05 15:46 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +int binary_search(std::vector<T> &arr,T val,int low,int high)
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

2021-12-06 18:23 UTC, Siddhartha-Padhy commented
All requested changes done!

2021-12-06 20:03 UTC, Panquesito7 requested changes
Almost there! 😄

2021-12-06 20:03 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +        return (val > arr[low]) ? (low + 1) : low;
```suggestion
    if (high <= low) {
        return (val > arr[low]) ? (low + 1) : low;
    }
```

2021-12-06 20:03 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +        return mid+1;
```suggestion
    if(arr[mid]>val) {
        return binary_search(arr,val,low,mid-1);
    }
    else if(arr[mid]<val) {
        return binary_search(arr,val,mid+1,high);
    }
    else {
        return mid+1;
    }
```

2021-12-06 20:03 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +    std::cout << "Test 1... ";
```suggestion
    std::cout << "1st test... ";
```

2021-12-06 20:03 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +    std::cout << "Test 2... ";
```suggestion
    std::cout << "2nd test... ";
```

2021-12-06 20:03 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +    std::cout << "Test 3... ";
```suggestion
    std::cout << "3rd test... ";
```

2021-12-06 20:03 UTC, Panquesito7 commented on sorting/binary_insertion_sort.cpp
> +    std::cout << "Test 4... ";
```suggestion
    std::cout << "4th test... ";
```

2021-12-07 13:30 UTC, Siddhartha-Padhy commented
Done!

2021-12-09 17:31 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-11 18:31 UTC, mishraabhinn approved these changes

2022-01-11 18:39 UTC, merged