feat: Reworked binary_search.cpp
TheAlgorithms/C-Plus-Plus pull request #1854
Opened 2021-12-16 11:29 UTC by Lazeeez

#### Description of Change

The original binary_search.cpp was pretty blatant with no documentation, did some rework on it and added some testcases to check the algorithm.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Did some rework on the original binary_search.cpp

2021-12-16 13:46 UTC, Lazeeez commented
@Panquesito7 Can you please review this PR.

2021-12-16 16:54 UTC, Panquesito7 requested changes
Great work! 😄👍

2021-12-16 16:54 UTC, Panquesito7 commented on search/binary_search.cpp
> + *algorithm](https://en.wikipedia.org/wiki/Binary_search_algorithm)
```suggestion
 * algorithm](https://en.wikipedia.org/wiki/Binary_search_algorithm)
```

2021-12-16 16:54 UTC, Panquesito7 commented on search/binary_search.cpp
> + * Average time complexity	    O(log n)
```suggestion
 * Average time complexity      O(log n)
```

2021-12-16 16:54 UTC, Panquesito7 commented on search/binary_search.cpp
> + * @returns @param int index of val in vector arr
```suggestion
 * @returns integer index of `val` in vector `arr`
```

2021-12-16 16:54 UTC, Panquesito7 commented on search/binary_search.cpp
> +static void test1() {
Let's make this only `void` and create a static `tests` function, which will run all tests. 😄
```suggestion
void test1() {
```

2021-12-16 16:54 UTC, Panquesito7 commented on search/binary_search.cpp
> +}
```suggestion
}
/*******************************************************************************
 * @brief Self-test implementations
 * @returns void
 *******************************************************************************/
static void tests() {
    test1();
    test2();
    test3();
}
```

2021-12-16 16:54 UTC, Panquesito7 commented on search/binary_search.cpp
> +    test3();  // run self-test implementation #3
```suggestion
    tests();  // run self-test implementations
```

2021-12-16 19:00 UTC, Lazeeez commented
@Panquesito7 Thanks for the suggestions and corrections. 😄

2021-12-17 19:20 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-04 10:52 UTC, Qannaf approved these changes

2022-01-07 21:44 UTC, merged