feat: Reworked interpolation_search.cpp
TheAlgorithms/C-Plus-Plus pull request #1855
Opened 2021-12-18 07:02 UTC by Lazeeez

#### Description of Change

The original `interpolation_search.cpp` was pretty blatant with little to no documentation, did some rework on it and added a testcase to check the algorithm.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Did some rework on the original `interpolation_search.cpp`

2021-12-18 07:13 UTC, Lazeeez commented
@Panquesito7 Can you please review this PR, thanks!

2021-12-19 02:10 UTC, Panquesito7 requested changes
Great work! 🚀
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Lazeeez/C-Plus-Plus/actions

2021-12-19 02:10 UTC, Panquesito7 commented on search/interpolation_search.cpp
> + * @brief [interpolation search
```suggestion
 * @brief [Interpolation search
```

2021-12-19 02:10 UTC, Panquesito7 commented on search/interpolation_search.cpp
> + * @brief interpolation search searching algorihm
```suggestion
 * @brief Functions for the [Interpolation Search](https://en.wikipedia.org/wiki/interpolation_search) algorithm implementation
```

2021-12-19 02:10 UTC, Panquesito7 commented on search/interpolation_search.cpp
> + * @brief The main function which implements binary search
```suggestion
 * @brief The main function which implements interpolation search
```

2021-12-19 02:10 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +void tests() {
```suggestion
static void tests() {
```

2021-12-19 02:10 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    tests();  // Condition of target found
```suggestion
    tests();  // run self-test implementations
```

2021-12-19 09:03 UTC, Lazeeez commented
> Great work! 🚀 Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Lazeeez/C-Plus-Plus/actions

The Github actions are already enabled for this entire repository.

2021-12-19 09:12 UTC, Lazeeez commented
@Panquesito7 check now.

2021-12-20 01:51 UTC, Panquesito7 requested changes
Almost there! 😄

2021-12-20 01:51 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    // testcase
```suggestion
    // 1st test
```

2021-12-20 01:51 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    std::cout << "Testcase : ";
```suggestion
    std::cout << "1st test: ";
```

2021-12-23 03:08 UTC, Panquesito7 requested changes

2021-12-23 03:08 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    // testcase
```suggestion
    // 1st test
```

2021-12-23 03:08 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    std::cout << "Testcase : ";
```suggestion
    std::cout << "1st test: ";
```

2021-12-23 03:08 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    std::cout << "Passed!";
```suggestion
    std::cout << "Passed!\n";
```

2021-12-24 00:56 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    std::cout << "Passed!";
Let's add a new line here. It'll look better in the terminal. 😃
```suggestion
    std::cout << "Passed!\n";
```

2021-12-25 01:47 UTC, Panquesito7 commented on search/interpolation_search.cpp
> +    std::cout << "Testcase : ";
```suggestion
    std::cout << "Testcase: ";
```

2021-12-25 01:49 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-01 15:02 UTC, Qannaf approved these changes

2022-01-01 15:44 UTC, ayaankhan98 approved these changes
LGTM

2022-01-02 03:29 UTC, Panquesito7 approved these changes

2022-01-02 03:42 UTC, merged