Add: Recursive tree traversal techniques
TheAlgorithms/C-Plus-Plus pull request #1856
Opened 2021-12-23 14:33 UTC by Lazeeez

#### Description of Change

All Tree traversal techniques (inorder, postorder, preorder) with recursive functions.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Added tree traversal implementations with recursive functions.

2021-12-23 14:44 UTC, Lazeeez commented
@Panquesito7 can you please review this PR, thanks.

2021-12-23 18:21 UTC, Panquesito7 requested changes
Great work! 😄👍

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + * @brief Searching algorithms
```suggestion
 * @namespace others
 * @brief Other algorithms
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +    * @brief Functions for the revursive tree traversal techniques.
```suggestion
    * @brief Functions for the Recursive version of Inorder, Preorder, and Postorder [Traversal of the Tree](https://en.wikipedia.org/wiki/Tree_traversal) algorithm implementation
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + * @brief Self-test implementation #1
```suggestion
 * @brief 1st test-case
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +static void test1(){
```suggestion
void test1(){
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + * @brief Self-test implementation #2
```suggestion
 * @brief 2nd test-case
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +static void test2(){
```suggestion
void test2(){
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + * @brief Self-test implementation #3
```suggestion
 * @brief 3rd test-case
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +static void test3(){
```suggestion
void test3(){
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +
```suggestion

/**
 * @brief Self-test implementations
 * @returns void
 */
static void tests() {
    std::cout << "1st test-case" << std::endl;
    test1();  // run 1st test-case
    std::cout << "2nd test-case" << std::endl;
    test2();  // run 2nd test-case
    std::cout << "3rd test-case" << std::endl;
    test3();  // run 3rd test-case
}
```

2021-12-23 18:21 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +    test3();                                    // run self-test implementations #3
```suggestion
    tests();  // run self-test implementations
```

2021-12-26 01:53 UTC, Panquesito7 reviewed
Hey there! I saw some of my suggestions/comments are not implemented yet. Would you like to explain why you didn't accept them and what are your thoughts on this? Thank you! 😃

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *referred to as reverse preorder traversal.
```suggestion
 * subtree. If we visit the right subtree before visiting the left subtree, it is
 * referred to as reverse preorder traversal.
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *referred to as reverse inorder traversal.
```suggestion
 * subtree. If we visit the right subtree before visiting the left subtree, it is
 * referred to as reverse inorder traversal.
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *referred to as reverse postorder traversal.
```suggestion
 * subtree. If we visit the right subtree before visiting the left subtree, it is
 * referred to as reverse postorder traversal.
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + * the Tree] (https://en.wikipedia.org/wiki/Tree_traversal)
```suggestion
 * the Tree](https://en.wikipedia.org/wiki/Tree_traversal)
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + * @brief Functions for the revursive tree traversal techniques.
```suggestion
 * @brief Functions for the [Recursive Traversal of
 * the Tree](https://en.wikipedia.org/wiki/Tree_traversal) implementation
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *traversal of a tree.
```suggestion
 * traversal of a tree.
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *traversal of a tree.
```suggestion
 * traversal of a tree.
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *functions associated with the binary tree
```suggestion
 * functions associated with the binary tree
```

2021-12-26 01:53 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> + *traversal of a tree.
```suggestion
 * traversal of a tree.
```

2021-12-26 03:34 UTC, Lazeeez commented
> Hey there! I saw some of my suggestions/comments are not implemented yet. Would you like to explain why you didn't accept them and what are your thoughts on this? Thank you! 😃
> 

I'm sorry, I was a bit busy with the Christmas, committed then just now, please check, thanks.

2021-12-27 01:50 UTC, Panquesito7 commented
> > Hey there! I saw some of my suggestions/comments are not implemented yet. Would you like to explain why you didn't accept them and what are your thoughts on this? Thank you! 😃
> 
> I'm sorry, I was a bit busy with the Christmas, committed then just now, please check, thanks.

No worries! I hope you had great holidays with your family! :D

2022-01-01 15:05 UTC, Qannaf submitted a review, later dismissed

2022-01-03 05:14 UTC, Lazeeez commented
@Panquesito7 can you check what's the conflict with the branch, thanks.

2022-01-03 16:23 UTC, Panquesito7 commented
> @Panquesito7 can you check what's the conflict with the branch, thanks.

The pull bot tried updating your branch to the latest version which caused conflicts and as well removed all the changes you made 😅 that's why it's always best to use another branch for that. You can do that. :)

2022-01-04 08:49 UTC, Lazeeez commented
> > @Panquesito7 can you check what's the conflict with the branch, thanks.
> 
> The pull bot tried updating your branch to the latest version which caused conflicts and as well removed all the changes you made 😅 that's why it's always best to use another branch for that. You can do that. :)

oh 😅

2022-01-04 09:05 UTC, Lazeeez commented
I'll create a new PR with a different branch.

2022-01-04 09:05 UTC, closed without merging