added set_kth_bit.cpp
TheAlgorithms/C-Plus-Plus pull request #1859
Opened 2021-12-31 17:43 UTC by aman2000raj

#### Description of Change

Given a number N and a value K. From the right, set the Kth bit in the binary representation of N. The position of Least Significant Bit(or last bit) is 0, the second last bit is 1 and so on.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:  added an algorithm which set the kth bit from right of a given Number.

2021-12-31 19:28 UTC, Panquesito7 requested changes
Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/aman2000raj/C-Plus-Plus/actions

2021-12-31 19:28 UTC, Panquesito7 commented on bit_manipulation/set_kth_bit.cpp
> +
```suggestion
```

2021-12-31 19:28 UTC, Panquesito7 commented on bit_manipulation/set_kth_bit.cpp
> +namespace Set_kth_bit {
```suggestion
namespace set_kth_bit {
```

2021-12-31 19:28 UTC, Panquesito7 commented on bit_manipulation/set_kth_bit.cpp
> +static void test() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
static void test() {
```

2021-12-31 19:28 UTC, Panquesito7 commented on bit_manipulation/set_kth_bit.cpp
> +}  // namespace Set_kth_bit
```suggestion
}  // namespace set_kth_bit
```

2022-01-01 14:26 UTC, Qannaf approved these changes

2022-01-01 16:46 UTC, closed without merging