Add approximate_pi.cpp file
TheAlgorithms/C-Plus-Plus pull request #1860
Opened 2021-12-31 23:20 UTC by Qannaf

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2021-12-31 23:23 UTC, Qannaf commented
This function  approximate pi using the given points

2022-01-01 00:38 UTC, Qannaf reviewed
Review

2022-01-02 03:04 UTC, Panquesito7 requested changes

2022-01-02 03:04 UTC, Panquesito7 commented on math/approximate_pi.cpp
> + * @brief Implementation to  calculate an estimate of the number π (Pi).
Provide a Wikipedia link in Markdown format (if available/possible).
If there's no Wikipedia link, add another web source for algorithm explanation. 🙂

2022-01-02 03:04 UTC, Panquesito7 commented on math/approximate_pi.cpp
> +#include <iostream>  /// for std::cout
```suggestion
#include <iostream>  /// for IO operations
```

2022-01-02 03:04 UTC, Panquesito7 commented on math/approximate_pi.cpp
> +#include <stdlib.h>  /// for rand
```suggestion
#include <cstdlib>  /// for rand
```

2022-01-02 03:04 UTC, Panquesito7 commented on math/approximate_pi.cpp
> +#include <vector>    /// for vector
```suggestion
#include <vector>    /// for std::vector
```

2022-01-02 08:04 UTC, Qannaf commented on math/approximate_pi.cpp
> + * @brief Implementation to  calculate an estimate of the number π (Pi).
* https://en.wikipedia.org/wiki/File:Pi_30K.gif

2022-01-02 08:09 UTC, Qannaf commented on math/approximate_pi.cpp
> + * @brief Implementation to  calculate an estimate of the number π (Pi).
```suggestion
 * @brief Implementation to  calculate an estimate of the number π (Pi).
 * https://en.wikipedia.org/wiki/File:Pi_30K.gif
```

2022-01-02 08:15 UTC, Qannaf reviewed
commit Review changes

2022-01-12 01:09 UTC, Panquesito7 requested changes
Almost there! 😃

2022-01-12 01:09 UTC, Panquesito7 commented on math/approximate_pi.cpp
> + * https://en.wikipedia.org/wiki/File:Pi_30K.gif
```suggestion
 * @brief Implementation to calculate an estimate of the [number π (Pi)](https://en.wikipedia.org/wiki/File:Pi_30K.gif).
```

2022-01-12 01:09 UTC, Panquesito7 commented on math/approximate_pi.cpp
> +#include <cstdlib>  /// for rand
```suggestion
#include <cstdlib>  /// for std::rand
```

2022-01-12 01:09 UTC, Panquesito7 commented on math/approximate_pi.cpp
> + */
```suggestion
```

2022-01-12 01:09 UTC, Panquesito7 commented on math/approximate_pi.cpp
> +
```suggestion
```

2022-01-12 01:09 UTC, Panquesito7 commented on math/approximate_pi.cpp
> +
Please add self-test cases so we can verify your program works properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference**). Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

2022-01-19 15:29 UTC, merged