Added toggle_bits_given_range.cpp
TheAlgorithms/C-Plus-Plus pull request #1861
Opened 2022-01-01 05:07 UTC by anishclw

#### Description of Change

Given a non-negative number n and two values l and r. The problem is to toggle the bits in the range l to r in the binary representation of n, i.e, to toggle bits from the rightmost lth bit to the rightmost rth bit. A toggle operation flips a bit 0 to 1 and a bit 1 to 0.
Constraint: 1 <= l <= r <= number of bits in the binary representation of n.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Added an algorithm for which the bits in a given range l to r of a number n will be toggled and then the new number will be returned.

2022-01-01 14:25 UTC, Qannaf approved these changes

2022-01-02 02:49 UTC, Panquesito7 requested changes
Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/anishclw/C-Plus-Plus/actions

2022-01-02 02:49 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> + * @brief Implementation to [toggle bits in a given range]
```suggestion
 * @brief Implementation to [Toggle Bits in a given Range]
```

2022-01-02 02:49 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> + * @brief Functions for the [toggle bits](https://www.geeksforgeeks.org/toggle-bits-given-range/)
```suggestion
 * @brief Functions for the [Toggle Bits](https://www.geeksforgeeks.org/toggle-bits-given-range/)
```

2022-01-02 02:49 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> +    std ::int64_t r) {  // int64_t is preferred over int so that
```suggestion
    std::int64_t n,
    std::int64_t l,
    std::int64_t r) {  // int64_t is preferred over int so that
```

2022-01-02 02:49 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> +static void test() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
static void test() {
```

2022-01-02 08:18 UTC, Qannaf approved these changes

2022-01-03 03:59 UTC, Panquesito7 requested changes
Almost there!

2022-01-03 03:59 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> +operation flips a bit 0 to 1 and a bit 1 to 0.
```suggestion
 * to toggle the bits in the range l to r in the binary representation of n, i.e,
 * to toggle bits from the rightmost lth bit to the rightmost rth bit. A toggle
 * operation flips a bit 0 to 1 and a bit 1 to 0.
```

2022-01-03 03:59 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> +            The bits in the range 2 to 3 in the binary
```suggestion
 *            Output : 23
 *            (17)10 = (10001)2
 *            (23)10 = (10111)2
 *           The bits in the range 2 to 3 in the binary
```

2022-01-05 04:54 UTC, anishclw commented
@Panquesito7 Sir is there any further changes required?

2022-01-12 16:47 UTC, Panquesito7 commented on bit_manipulation/toggle_bits_given_range.cpp
> +    while (l <= r) {
Do you think using a `for` loop be good here?

2022-03-29 00:10 UTC, closed without merging