Added count_bits_flip.cpp
TheAlgorithms/C-Plus-Plus pull request #1862
Opened 2022-01-01 06:31 UTC by yashrajyash

#### Description of Change

Code to count number of bits to be flipped to convert A to B

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:  Added an algorithm which returns the count of number of bits to be flipped of an a number A to form the number B

2022-01-01 14:23 UTC, Qannaf approved these changes

2022-01-02 18:22 UTC, yashrajyash commented
@Panquesito7 Please review my PR

2022-01-03 03:46 UTC, Panquesito7 requested changes
Great work! 😄👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/yashrajyash/C-Plus-Plus/actions

2022-01-03 03:46 UTC, Panquesito7 commented on bit_manipulation/count_bits_flip.cpp
> +    std ::int64_t B) {  // int64_t is preferred over int so that
```suggestion
    std::int64_t A,
    std::int64_t B) {  // int64_t is preferred over int so that
```

2022-01-04 16:11 UTC, yashrajyash commented
> Great work! 😄👍 Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/yashrajyash/C-Plus-Plus/actions

Sir, I've enabled GitHub Actions

2022-01-04 18:17 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-11 18:29 UTC, mishraabhinn approved these changes

2022-01-11 18:51 UTC, merged