added set_kth_bit.cpp
TheAlgorithms/C-Plus-Plus pull request #1863
Opened 2022-01-01 17:13 UTC by aman2000raj

#### Description of Change

Given a number N and a value K. From the right, set the Kth bit in the binary representation of N. The position of Least Significant Bit(or last bit) is 0, the second last bit is 1 and so on.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:  Added an algorithm which set kth bit of a given number.

2022-01-01 19:14 UTC, Qannaf approved these changes

2022-01-04 16:03 UTC, aman2000raj commented
@Panquesito7 please review my PR.

2022-01-04 16:03 UTC, aman2000raj commented
@Panquesito7 please review my PR.

2022-01-04 18:19 UTC, Panquesito7 requested changes

2022-01-04 18:19 UTC, Panquesito7 commented on bit_manipulation/set_kth_bit.cpp
> + *the second last bit is 1 and so on. in it.
```suggestion
 * Given a number N and a value K. From the right, set the Kth bit in the binary
 * representation of N. The position of Least Significant Bit(or last bit) is 0,
 * the second last bit is 1 and so on. in it.
```

2022-01-16 02:22 UTC, Panquesito7 reviewed
It's just to address this, and you're done! 🎉

2022-01-16 14:25 UTC, Panquesito7 approved these changes
Awesome work! You've done amazing work, and it's been your
first contribution here! We hope you keep contributing! 😄👍🎉

After this PR is merged, you can ask for the
contributor role in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 🚀

2022-01-16 15:57 UTC, mishraabhinn approved these changes

2022-01-16 15:57 UTC, merged