feat: add Recursive tree traversal techniques
TheAlgorithms/C-Plus-Plus pull request #1865
Opened 2022-01-04 09:10 UTC by Lazeeez

#### Description of Change

All Tree traversal techniques (inorder, postorder, preorder) with recursive functions.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Added tree traversal implementations with recursive functions.

2022-01-04 09:15 UTC, Lazeeez commented
@Panquesito7 can you check the PR now, thanks.

2022-01-04 10:53 UTC, Qannaf approved these changes

2022-01-04 17:14 UTC, Panquesito7 requested changes
Almost there! 😄

2022-01-04 17:14 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +
```suggestion
```

2022-01-04 17:14 UTC, Panquesito7 commented on others/recursive_tree_traversal.cpp
> +    tests();
```suggestion
    tests();  // run self-test implementations
```

2022-01-04 18:53 UTC, Lazeeez commented
@Panquesito7 changes done.

2022-01-05 17:14 UTC, Panquesito7 commented
> @Panquesito7 changes done.

Hey there! Hmm, I don't see any new commits 👀 I think you forgot to push or something, not sure. 😅

2022-01-06 18:34 UTC, Lazeeez commented
@Panquesito7 check now, had to manually do all the changes.

2022-01-09 01:26 UTC, Panquesito7 submitted a review, later dismissed
LGTM 🚀 Thank you for your contribution! 😄👍

2022-01-11 18:27 UTC, mishraabhinn requested changes
I feel this makes it cleaner to read. If you like this @Lazeeez @Panquesito7  we can change it as suggested thanks.

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> +/******************************************************************************
```suggestion
/**

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> +/******************************************************************************
```suggestion
/**
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @namespace interpolation_search
 * @brief Functions for the Recursive version of Inorder, Preorder, and
 * Postorder [Traversal of the
 * Tree](https://en.wikipedia.org/wiki/Tree_traversal) algorithm implementation
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief The structure to hold Nodes of the tree.
 * @param data Value that will be stored in the node.
 * @param left follow up left subtree.
 * @param right follow up right subtree.
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief BT used to make the entire structure of the binary tree and the
 * functions associated with the binary tree
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief will allocate the memory for a node and, along the data and return the
 * node.
 * @param data value that a particular node will contain.
 * @return pointer to the newly created node with assigned data.
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief inorder() function that will perform the inorder traversal
 * recursively, and return the resultant vector that contain the inorder
 * traversal of a tree.
 * @param root head/root node of a tree
 * @return result that is containing the inorder traversal of a tree
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief preorder function that will perform the preorder traversal
 * recursively, and return the resultant vector that contain the preorder
 * traversal of a tree.
 * @param root head/root node of a tree
 * @return result that is containing the preorder traversal of a tree
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief postorder function that will perform the postorder traversal
 * recursively, and return the result vector that contain the postorder
 * traversal of a tree.
 * @param root head/root node of a tree
 * @return result that is containing the postorder traversal of a tree
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief 1st test-case
 * @returns void
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief 2nd test-case
 * @returns void
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2022-01-11 18:27 UTC, mishraabhinn commented on others/recursive_tree_traversal.cpp
> + *******************************************************************************/
```suggestion
/**
 * @brief 3rd test-case
 * @returns void
 */
```

2022-01-11 21:11 UTC, Lazeeez commented
@mishraabhinn changes made, will keep it in mind next time, thanks.

2022-01-11 21:21 UTC, mishraabhinn approved these changes

2022-01-12 01:00 UTC, Panquesito7 approved these changes

2022-01-12 01:00 UTC, merged