This code use to calculate the middle element of the linked list
TheAlgorithms/C-Plus-Plus pull request #1867
Opened 2022-01-06 20:06 UTC by Vikash-8090-Yadav

#### Description of Change

issue No:  #1866 

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-01-09 16:11 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, the documentation is not up to our [**standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md). Please update the file accordingly. **Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6).** 😃

2022-01-09 16:11 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @file MiddleEle_SingLL.cpp
```suggestion
 * @file
```

2022-01-09 16:11 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +}
```suggestion
}

```

2022-01-10 16:37 UTC, Panquesito7 requested changes
Could you please fix [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/runs/4764269775?check_suite_focus=true) warnings? Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6)! 😃

2022-01-10 16:55 UTC, Vikash-8090-Yadav commented
idk why this clang tidy is showing error btw in my ide (sublime text ) the codes work's completely fine ..
Correct if am missing something sir ..
thank u 😅

2022-01-10 17:37 UTC, Panquesito7 commented
> idk why this clang tidy is showing error btw in my ide (sublime text ) the codes work's completely fine .. Correct if am missing something sir .. thank u 😅

Yeah, it works fine, but there are some errors that should be fixed.

![image](https://user-images.githubusercontent.com/51391473/148812225-39b90a89-8191-41f3-9bd9-5e6937b5e7ab.png)

2022-01-11 17:49 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + #include <iostream>
```suggestion
#include <iostream>   /// for IO operations
```

2022-01-11 17:49 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +    int data;
Please add a one-line description of what the variable is for (**see the example below**).

```c++
int64_t data = 0;       ///< The value/key of the node.
```

2022-01-11 17:51 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +
```suggestion
```

2022-01-11 17:51 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +
```suggestion
```

2022-01-11 18:27 UTC, Panquesito7 requested changes
For how to document your code properly, you can see the [**typical structure of a program**](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference. That'll help you make your code well-documented and understandable. You can also read the whole contributing guidelines; it'll help as well. 😃

2022-01-11 18:27 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + #include <iostream> // for I/O operations
```suggestion
 #include <iostream>  /// for I/O operations
```

2022-01-11 18:27 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +    node*next;          //  pointer pointing to the next node adress.
```suggestion
    int data;            ///< The value / key of the node . 
    node*next;           ///<  pointer pointing to the next node adress.
```

2022-01-11 18:27 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +void midpoint(int len,node*head){
Missing parameters documentation.

2022-01-11 18:27 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +void print(node*head){
Missing parameters documentation.

2022-01-11 18:27 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +int length(node*head){
Missing parameters documentation.

2022-01-13 09:35 UTC, Vikash-8090-Yadav commented
remainder !!

2022-01-13 18:22 UTC, Panquesito7 requested changes
Great work! 😄👍

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + #include <iostream> // for I/O operations
```suggestion
#include <iostream>  /// for I/O operations
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @param data that always initialize to the node data every time
This doesn't count as a parameter as classes can't have parameters. You can document the variables inside the classes, though. 🙂

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * A Node class containing a value and pointer to another link
```suggestion
 * @brief A Node class containing a value and pointer to another link
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +    int data;            ///< The value / key of the node
```suggestion
    int data = 0;            ///< The value / key of the node 
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @returns 'void'
```suggestion
 * @returns void
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * function use to calculate the mid element of the linked list.
```suggestion
 * @brief Function use to calculate the mid element of the linked list
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @param head stored the first node address of the linkedlist .
```suggestion
 * @param len length of the linked list
 * @param head stores the first node address of the LinkedList
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * function takes the head node and traverse the l.l
```suggestion
 * @brief function takes the head node and traverses the l.l
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * and print the data .
```suggestion
 * and prints the data
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @param head stored the first node address of the linkedlist .
```suggestion
 * @param head stores the first node address of the LinkedList
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @returns 'void'
```suggestion
 * @returns void
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * list .
```suggestion
 * @brief Utility function to calculate the length of the linked list
```

2022-01-13 18:22 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> + * @returns len that is the length of the linked list.
```suggestion
 * @param head stores the first node address of the LinkedList
 * @returns the length of the linked list
```

2022-01-16 16:23 UTC, Vikash-8090-Yadav commented
Remainder.

2022-01-25 16:30 UTC, Panquesito7 requested changes

2022-01-25 16:30 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +
Please add self-test cases so we can verify your program works properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference**). Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 😃

2022-01-25 19:44 UTC, Panquesito7 requested changes
Almost there! 😄

2022-01-25 19:44 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +#include <iostream> /// for I/O operations
```suggestion
#include <cassert>     /// for assert
#include <iostream>    /// for I/O operations
```

2022-01-25 19:44 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +    std::cout<<"All tests have sucessfully passed!"<<std::endl;
```suggestion
    std::cout << "All tests have sucessfully passed!" << std::endl;
```

2022-01-25 19:44 UTC, Panquesito7 commented on data_structures/MIddleElement_S.ll.cpp
> +	test();  //run self-test implementations
```suggestion
    test();  // run self-test implementations
```

2022-04-16 00:09 UTC, closed without merging