Added length of longest substring alg
TheAlgorithms/C-Plus-Plus pull request #1877
Opened 2022-01-24 23:06 UTC by krhartley

#### Description of Change
Added length of longest substring algorithm.

#### Checklist
- [X] Added description of change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [X] Added tests and example, test must pass
- [X] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

2022-01-26 15:24 UTC, Qannaf requested changes

2022-01-26 15:24 UTC, Qannaf commented on strings/length_longest_substr.cpp
> +                if (counts[input.substr(j, 1)] == NULL) {
```suggestion
                if (counts[input.substr(j, 1)] == 0) {
```

2022-01-26 15:29 UTC, Panquesito7 requested changes

2022-01-26 15:29 UTC, Panquesito7 commented on strings/length_longest_substr.cpp
> +}
Missing an endline. Without this endline, it could cause problems with some IDEs and configurations.
```suggestion
}

```

2022-01-27 15:15 UTC, Panquesito7 requested changes
Almost there! 😄

2022-01-27 15:15 UTC, Panquesito7 commented on strings/length_longest_substr.cpp
> + * @brief Length of longest substring (without repeating characters)
Provide a Wikipedia link in Markdown format (if available/possible).
If there's no Wikipedia link, add another web source for algorithm explanation. 🙂

2022-01-27 15:15 UTC, Panquesito7 commented on strings/length_longest_substr.cpp
> + * @author [Katherine Hartley] (https://github.com/krhartley)
```suggestion
 * @author [Katherine Hartley](https://github.com/krhartley)
```

2022-01-27 15:15 UTC, Panquesito7 commented on strings/length_longest_substr.cpp
> +namespace longest_substr_length {
```suggestion
/**
 * @namespace longest_substr_length
 * @brief Functions for the Length of longest substring (without
 * repeating characters) algorithm implementation
 */
namespace longest_substr_length {
```

2022-03-07 00:08 UTC, closed without merging