feat: add valid_parentheses.cpp
TheAlgorithms/C-Plus-Plus pull request #1896
Opened 2022-01-30 04:15 UTC by tuan-dang-0

#### Description of Change

Added stack implementation for a solution to valid parentheses in "others"

#### Checklist

- [x ] Added description of change
- [x ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x ] Added tests and example, test must pass
- [ x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x ] Relevant documentation/comments is changed or added
- [x ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x ] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Added valid_parentheses.cpp to "others"

2022-01-30 18:14 UTC, Panquesito7 requested changes
Great work! 🚀

2022-01-30 18:14 UTC, Panquesito7 commented on .gitignore
> +/.vs
Please revert the changes in this file. Thank you.

2022-01-30 18:14 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> + * @brief other algorithms
```suggestion
 * @brief Other algorithms
```

2022-01-30 18:14 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> + * (https://leetcode.com/problems/valid-parentheses/)
```suggestion
 * @brief [Stack implementation to check Valid Parentheses in string](https://leetcode.com/problems/valid-parentheses/)
```

2022-01-30 18:14 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> + * @brief Functions for implementation
```suggestion
 * @brief Functions for the [Check Valid Parentheses in string](https://leetcode.com/problems/valid-parentheses/) implementation
```

2022-01-30 18:14 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> +        return false;
```suggestion
    if (!stk.empty()) {
        return false;
    }
```

2022-01-30 18:14 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-01-30 18:40 UTC, tuan-dang-0 commented
Hey! just added the changes you requested, thank you.

2022-02-01 12:53 UTC, Panquesito7 requested changes

2022-02-01 12:53 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> +   (https://leetcode.com/problems/valid-parentheses/)
```suggestion
 * (https://leetcode.com/problems/valid-parentheses/)
```

2022-02-01 12:53 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> +   (https://leetcode.com/problems/valid-parentheses/)
```suggestion
 * (https://leetcode.com/problems/valid-parentheses/) algorithm implementation
```

2022-02-01 12:53 UTC, Panquesito7 commented on others/valid_parentheses.cpp
> +    std::cout << "All test cases passed!" << std::endl;
```suggestion
    std::cout << "All test cases have successfully passed!" << std::endl;
```

2022-04-20 00:10 UTC, closed without merging