feat: add perimeter.cpp
TheAlgorithms/C-Plus-Plus pull request #1897
Opened 2022-01-30 05:18 UTC by OGscorpion

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-01-30 05:26 UTC, OGscorpion commented
Hi, this is my first contribution to an open source project. Please let me know if I made any mistakes.. Thanks!

2022-01-30 07:05 UTC, Panquesito7 requested changes

2022-01-30 07:05 UTC, Panquesito7 commented on math/perimeter.cpp
> +#include <cmath>
Double `cmath`. 😅
```suggestion
```

2022-02-01 13:48 UTC, Panquesito7 submitted a review, later dismissed
LGTM 🚀 Thank you for your contribution! 😄👍

2022-02-01 14:38 UTC, OGscorpion commented
Thank your for approving my work

2022-02-01 14:52 UTC, ayaankhan98 commented on math/perimeter.cpp
> + * All shapes have a formula to get the perimeter of any given shape.
```suggestion
 * All shapes have a formula for their perimeter.
```

2022-02-01 15:51 UTC, OGscorpion commented on math/perimeter.cpp
> + * @details The  of a shape is the amount of 2D space it takes up.
thanks for pointing out

2022-02-02 04:31 UTC, ayaankhan98 approved these changes

2022-02-02 05:30 UTC, Panquesito7 approved these changes

2022-02-02 05:31 UTC, mishraabhinn approved these changes

2022-02-02 05:32 UTC, merged