feat: add binary_to_decimal.cpp
TheAlgorithms/C-Plus-Plus pull request #1908
Opened 2022-01-30 21:30 UTC by vishwakrishnan02

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
This is an algorithm to convert a binary string to decimal format.

2022-01-30 23:27 UTC, Panquesito7 requested changes
Great work! Thank you. 🎉
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/vishwakrishnan02/C-Plus-Plus/actions

2022-01-30 23:27 UTC, Panquesito7 commented on others/binary_to_decimal.cpp
> +#include <algorithm>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2022-01-30 23:27 UTC, Panquesito7 commented on others/binary_to_decimal.cpp
> +    test(); //Runs all the self-implemented test cases.
```suggestion
    test();  // run self-test implementations
```

2022-01-30 23:27 UTC, Panquesito7 commented on others/binary_to_decimal.cpp
> +int main()
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main()
```

2022-01-30 23:27 UTC, Panquesito7 commented on others/binary_to_decimal.cpp
> +static void test() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns 0 on exit
 */
static void test() {
```

2022-01-31 00:03 UTC, vishwakrishnan02 reviewed
All changes have been made!

2022-04-11 00:09 UTC, closed without merging