feat: add binary exponentiationn algorithm, class divide and conquer
TheAlgorithms/C-Plus-Plus pull request #1924
Opened 2022-01-31 02:43 UTC by TSChiles

#### Description of Change
Added binary exponentiation algorithm for divide and conquer algorithm

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Addition of Binary Exponentiation Algorithm

2022-01-31 04:06 UTC, Panquesito7 requested changes
Great work! 🚀
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/TSChiles/C-Plus-Plus/actions

2022-01-31 04:06 UTC, Panquesito7 commented on divide_and_conquer/binary_exponentiation.cpp
> + * @brief Implementation of Binary Exponentiation
Provide a Wikipedia link in Markdown format (if available/possible).
If there's no Wikipedia link, add another web source for algorithm explanation. 🙂

2022-01-31 04:06 UTC, Panquesito7 commented on divide_and_conquer/binary_exponentiation.cpp
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-01-31 04:06 UTC, Panquesito7 commented on divide_and_conquer/binary_exponentiation.cpp
> +    long long expo(long long param1, long long param2) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). **Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6).** 🙂

2022-02-15 18:17 UTC, CarlosZoft requested changes

2022-02-15 18:17 UTC, CarlosZoft commented on divide_and_conquer/binary_exponentiation.cpp
> +            return sol*sol;
redundant "else", my suggestion is that you just return the result

2022-02-15 18:17 UTC, CarlosZoft commented on divide_and_conquer/binary_exponentiation.cpp
> +        if(param2%2){
In both cases you return sol². I suggest you create a variable that stores this and follow the flow:

Example :
```
    long long sun = expo(param1, param2/2);
    //if odd, multiply by base again
    long long squaredSol = sun * sun;
    if(param2%2){
        return squaredSol * param1;
    }
   return squaredSol ;

```
just one suggestion  #goodpratices :)

2022-03-26 00:08 UTC, closed without merging