feat: Added binary to octal conversion
TheAlgorithms/C-Plus-Plus pull request #1934
Opened 2022-02-02 02:52 UTC by peterlucchino

#### Description of Change
Added a function which converts binary strings to octal strings

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
This is my first open source github contribution, any feedback would be appreciated. 
If any part of this doesn't work or is incorrect feel free to tell me what I did wrong or could have done better

2022-02-02 13:28 UTC, Panquesito7 requested changes
Hey there! Thanks for submitting a PR! :smile: Please remove all the other files and keep the `others/binary_to_octal.cpp` file. Let us know if you need any help. Thanks.

2022-02-02 14:18 UTC, peterlucchino commented
Should I just submit a new pull request? I'm not sure how to remove files from this one

2022-02-03 16:17 UTC, Qannaf commented on others/binary_to_octal.cpp
> +
```suggestion
void test()
{
 assert(binary_to_octal("111101") == "75");
    assert(binary_to_octal("111101101110100010110011011") == "755642633");
    assert(binary_to_octal("1") == "1");
    assert(binary_to_octal("10") == "2");
    assert(binary_to_octal("1000101010") == "1052");
}
```

2022-02-03 16:18 UTC, Qannaf commented on others/binary_to_octal.cpp
> +    assert(binary_to_octal("111101101110100010110011011") == "755642633");
test();

2022-02-03 16:19 UTC, Qannaf commented on others/binary_to_octal.cpp
> +    assert(binary_to_octal("1000101010") == "1052");
test();

2022-02-13 18:58 UTC, CarlosZoft commented
@peterlucchino 
if you decide to create a new pull request, close the current pull request and submit it with the requested changes.

2022-03-23 00:09 UTC, closed without merging