feat : add modular_inverse_simple
TheAlgorithms/C-Plus-Plus pull request #1937
Opened 2022-02-15 17:36 UTC by CarlosZoft

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

this is a simple implementation made during a college course - discrete mathematics

2022-02-15 18:23 UTC, Panquesito7 requested changes
Great work! 🚀

2022-02-15 18:23 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> +#include <iostream>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2022-02-15 18:23 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> +int imod(int x, int y) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). **Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6).** 🙂

2022-02-15 18:23 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> +    test();  // run tests implementations
```suggestion
    test();  // run self-test implementations
    return 0;
```

2022-02-27 00:44 UTC, tjgurwara99 commented on math/modular_inverse_simple.cpp
> +uint64_t imod(uint64_t x, uint64_t y) {  // positive integer expected
What happens when a negative number is provided in the arguments - I don't think you've considered a fail safe here.

2022-02-27 00:48 UTC, tjgurwara99 submitted a review, later dismissed
LGTM

2022-04-24 16:05 UTC, CarlosZoft commented
@poyea can you review this pr?

2022-04-24 16:08 UTC, poyea commented on math/modular_inverse_simple.cpp
> +uint64_t imod(uint64_t x, uint64_t y) {  // positive integer expected
std::uint64_t is defined in header <cstdint>?

2022-04-24 16:15 UTC, poyea commented on math/modular_inverse_simple.cpp
> +uint64_t imod(uint64_t x, uint64_t y) {  // positive integer expected
```suggestion
uint64_t imod(uint64_t x, uint64_t y) { 
```

2022-04-24 16:15 UTC, poyea commented on math/modular_inverse_simple.cpp
> +    } while (aux % x);  // while module aux % x is different of zero
```suggestion
    } while (aux % x);  // while module aux % x is non-zero
```

2022-04-24 16:22 UTC, poyea commented on math/modular_inverse_simple.cpp
> + * @brief simple implementation of adaption modular multiplicative inverse
```suggestion
 * @brief simple implementation of modular multiplicative inverse
```

2022-04-24 16:22 UTC, poyea commented on math/modular_inverse_simple.cpp
> + * this algorithm calculate the modular inverse iteratively
```suggestion
 * this algorithm calculates the modular inverse iteratively
```

2022-04-24 16:23 UTC, poyea commented on math/modular_inverse_simple.cpp
> + * algorithm
```suggestion
```

2022-04-24 16:28 UTC, poyea commented on math/modular_inverse_simple.cpp
> + *  Responsible for calculating the modular inverse from x % y
Perhaps
```suggestion
 *  Responsible for calculating the modular inverse of x with respect to y
```

2022-04-24 16:29 UTC, CarlosZoft commented on math/modular_inverse_simple.cpp
> + *  Responsible for calculating the modular inverse from x % y
better, is more descritive

2022-04-24 16:52 UTC, poyea commented
@Panquesito7 we need your approval on this

2022-04-24 19:03 UTC, poyea submitted a review, later dismissed

2022-04-24 19:06 UTC, poyea commented on math/modular_inverse_simple.cpp
> + * this algorithm calculates the modular inverse iteratively
```suggestion
 * this algorithm calculates the modular inverse x^-1 mod y iteratively
```

2022-04-24 19:06 UTC, poyea commented on math/modular_inverse_simple.cpp
> + *    Responsible for calculating the modular inverse of x with respect to y
```suggestion
 *    Responsible for calculating the modular inverse of x with respect to y, x^{-1} mod y
```

2022-04-24 19:36 UTC, poyea submitted a review, later dismissed
Thank you for your pull request!🤩

2022-05-25 19:12 UTC, CarlosZoft commented
:(

2022-05-25 19:15 UTC, poyea commented
@CarlosZoft You need approval from @Panquesito7

2022-06-09 14:56 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> + * @brief simple implementation of modular multiplicative inverse
```suggestion
 * @brief Simple implementation of [modular multiplicative inverse](https://en.wikipedia.org/wiki/Modular_multiplicative_inverse)
```

2022-06-09 14:56 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> + * https://en.wikipedia.org/wiki/Modular_multiplicative_inverse
```suggestion
```

2022-06-09 14:56 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> +    test();  // run  self-test implementations
```suggestion
    test();  // run self-test implementations
```

2022-06-09 15:10 UTC, Panquesito7 commented on math/modular_inverse_simple.cpp
> + * https://en.wikipedia.org/wiki/Modular_multiplicative_inverse
```suggestion
```

2022-06-09 15:27 UTC, merged