feat: sat collision algorithm for convex polygons and circles
TheAlgorithms/C-Plus-Plus pull request #1958
Opened 2022-07-16 16:35 UTC by WeRiano

Added collision detection algorithm for 2D shapes (polygons and circles) that uses [SAT](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem)

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-07-17 11:50 UTC, WeRiano commented
linked to [#1955](https://github.com/TheAlgorithms/C-Plus-Plus/issues/1955)

2022-09-05 04:04 UTC, Panquesito7 requested changes
Amazing work! 🚀
P.S.: Sorry for the delayed response.

2022-09-05 04:04 UTC, Panquesito7 commented on geometry/sat_collision.cpp
> +/******************************************************************************/
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.

```suggestion
/******************************************************************************/

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-09-05 04:04 UTC, Panquesito7 commented on geometry/sat_collision.h
> +namespace collision {
```suggestion
/**
 * @namespace geometry
 * @brief Geometry-related algorithms
 */
namespace geometry {
/**
 * @namespace collision
 * @brief Functions for the [Hyperplane Separation Theorem]
* (https://en.wikipedia.org/wiki/Hyperplane_separation_theorem) algorithm implementation
*/
namespace collision {
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-05 04:04 UTC, Panquesito7 commented on geometry/sat_collision.h
> +}}
```suggestion
}  // namespace collision
}  // namespace geometry

```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inelegant

2022-10-14 00:17 UTC, closed without merging