added connected_components_using_bfs by explainig a question
TheAlgorithms/C-Plus-Plus pull request #2000
Opened 2022-09-26 19:48 UTC by ritik-369

added an algorithm for finding connected components using bfs in graph section by solving a question of hackerearth
link provided in file

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-09-26 21:24 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, the documentation is not up to our [**standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md). Please update the file accordingly. **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord/).** 😃

2022-09-26 21:24 UTC, Panquesito7 commented on graph/connected_components_with_bfs.cpp
> +int main()
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main()
```

2022-09-26 21:24 UTC, Panquesito7 commented on graph/connected_components_with_bfs.cpp
> +
```suggestion
```

2022-09-27 01:47 UTC, ritik-369 commented
Thanks for Suggesting

On Tue, 27 Sep, 2022, 2:54 am David Leal, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey there! Thank you for submitting a PR! 😄 Sadly, the documentation is
> not up to our *standards*
> <https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md>. Please
> update the file accordingly. *Let us know if you need any help here or on
> our Discord server <https://the-algorithms.com/discord/>.* 😃
> ------------------------------
>
> In graph/connected_components_with_bfs.cpp
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/2000#discussion_r980476671>
> :
>
> > +#include <algorithm>
>
> +#include <cassert>
>
> +#include <iostream>
>
> +#include <vector>
>
> +#include <queue>
>
>
> Please add a one-line description of what the library/header is for (*see
> the example below*).
>
> #include <iostream>    /// for IO operations
>
> #include <cassert>    /// for assert
>
> ------------------------------
>
> In graph/connected_components_with_bfs.cpp
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/2000#discussion_r980478344>
> :
>
> > + *    component      component        component
>
> + * </pre>
>
> + *
>
> + */
>
> +
>
> +
>
> +//                  WE WILL LEARN CALCULATING NO. OF CONNECTED COMPONENTS IN GRAPH USING BFS BY SOLVING A HACKEREARTH QUESTION
>
> +//                  LINK=   https://www.hackerearth.com/problem/algorithm/connected-components-in-a-graph/
>
> +
>
> +#include <algorithm>
>
> +#include <cassert>
>
> +#include <iostream>
>
> +#include <vector>
>
> +#include <queue>
>
> +
>
> +using namespace std;      // using namespace std so that we have not to write std:: again and again
>
>
> Do not use using namespace std;.
> This will cause the CI to fail and we won't be able to merge your program.
> ------------------------------
>
> In graph/connected_components_with_bfs.cpp
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/2000#discussion_r980517132>
> :
>
> > +      while(!q.empty())             // running bfs loop
>
> +      {
>
> +         cur=q.front();            // extracting data of front node from queue
>
> +         q.pop();                  // removing front node
>
> +         for(auto child:adj[cur]) if(!vis[child])    //{child} is child of current node which is processing under bfs and check if child is not visited
>
> +         {
>
> +            q.push(child);               // pushing non visited node in queue
>
> +            vis[child]=1;                // marking it as visited
>
> +         }
>
> +      }
>
> +   }
>
> +   return components;                   // returning components in graph
>
> +}
>
> +
>
> +
>
> +int main()
>
>
> ⬇️ Suggested change
>
> -int main()
>
> +/**
>
> + * @brief Main function
>
> + * @returns 0 on exit
>
> + */
>
> +int main()
>
>
> ------------------------------
>
> In graph/connected_components_with_bfs.cpp
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/2000#discussion_r980517222>
> :
>
> > +
>
> +
>
>
> ⬇️ Suggested change
>
> -
>
> -
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheAlgorithms/C-Plus-Plus/pull/2000#pullrequestreview-1120870044>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWK56TWQPK54HBOBM4ARMQ3WAIICTANCNFSM6AAAAAAQWDVWUE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-27 03:10 UTC, ritik-369 commented
I updated file

2022-09-27 14:39 UTC, ritik-369 commented
why it is not merged?

2022-09-27 18:44 UTC, ritik-369 commented
can i add more algorithms?

2022-09-27 19:20 UTC, ritik-369 commented
please can you help me in contribution, i am new to open source i can't understand what are these checks and why it shows merging is blocked

2022-09-28 02:35 UTC, closed without merging