Added inorder.cpp
TheAlgorithms/C-Plus-Plus pull request #2025
Opened 2022-10-01 11:25 UTC by Chaitanya134

#### Description of Change
Implemented inorder tree traversal

#### Checklist

- [x ] Added description of change
- [ x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ x] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ x] Relevant documentation/comments is changed or added
- [ x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-02 14:31 UTC, Chaitanya134 commented
Hey, @mishraabhinn Can you please review this pr for hacktoberfest?

2022-10-13 19:24 UTC, Chaitanya134 commented
@Panquesito7 Can you please review this?

2022-12-02 20:40 UTC, Panquesito7 requested changes

2022-12-02 20:40 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +using namespace std;
This is discouraged. Please strictly use `std::` for each member instead. You can use `using std::cout;`, `using std::cin;`, and so on for all `std::` members.

2022-12-02 20:40 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +
Please add self-test cases so we can verify your program works properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference**). Let us know if you need any help here or on our [**Discord server**](https://the-algorithms.com/discord). 😃

2023-04-26 16:37 UTC, Panquesito7 requested changes

2023-04-26 16:37 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +class Node {
```suggestion
/**
 * @namespace
 * @brief Data structures
 */
namespace data_structures {
class Node {
```

2023-04-26 16:37 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +    BinaryTree tree;    // create a tree
```suggestion
    data_structures::BinaryTree tree;    // create a tree
```

2023-04-26 16:37 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +    BinaryTree tree;    // create a tree
```suggestion
    data_structures::BinaryTree tree;    // create a tree
```

2023-04-26 16:37 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +    Node *root = NULL;  // root node
```suggestion
    data_structures::Node *root = nullptr;  // root node
```

2023-05-05 23:45 UTC, Chaitanya134 commented on data_structures/inorder.cpp
> +class Node {
Can you suggest the correct way to write a class description?

2023-05-12 19:07 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +class Node {
You can use something similar to this, or anything else you'd like; it doesn't have to be long. 🙂

```cpp
/**
 * @brief Class that includes the required functions
 * to make the code work properly.
 */
```

2023-05-16 05:10 UTC, Chaitanya134 commented on data_structures/inorder.cpp
> +class Node {
Okay got it. My recent commit has class description in it.

2023-05-27 01:05 UTC, Panquesito7 requested changes

2023-05-27 01:05 UTC, Panquesito7 commented on data_structures/inorder.cpp
> + * @brief [Inorder Tree Traveral](https://www.javatpoint.com/inorder-traversal)
Please add a detailed description (you can take as a reference any source link, such as Wikipedia or the current one).

2023-05-27 01:05 UTC, Panquesito7 commented on data_structures/inorder.cpp
> +* @brief [Self-tests for inorder tree traversal]
There's no need for the brackets. That's usually used only for Markdown links.
```suggestion
* @brief Self-tests for inorder tree traversal
```

2023-07-05 00:12 UTC, closed without merging