updated version of stack linked list
TheAlgorithms/C-Plus-Plus pull request #2036
Opened 2022-10-01 17:02 UTC by anxkhn

updated version of stack linked list with proper formatting and fixed print statements.

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-01 17:34 UTC, mishraabhinn approved these changes

2023-04-22 15:19 UTC, realstealthninja requested changes

2023-04-22 15:19 UTC, realstealthninja commented on data_structures/stack_using_linked_list.cpp
>  #include <iostream>
```suggestion
#include <iostream> /// for I/O operations 
```

2023-04-22 15:19 UTC, realstealthninja commented on data_structures/stack_using_linked_list.cpp
> +            break;
please use tests

2023-04-22 15:19 UTC, realstealthninja commented on data_structures/stack_using_linked_list.cpp
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2024-08-29 13:35 UTC, realstealthninja commented
closing due to no response from author, please comment if you'd like this to be re opened

2024-08-29 13:35 UTC, closed without merging