add updated linked list
TheAlgorithms/C-Plus-Plus pull request #2039
Opened 2022-10-01 20:52 UTC by NasreenParween

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-01 21:26 UTC, mishraabhinn reviewed
Plz make one pr per file 
Contributing guidelines

2022-10-02 14:51 UTC, NasreenParween commented
@mishraabhinn Added the required changes

2022-10-03 05:37 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord).** 🙂

2022-10-05 22:12 UTC, DxLRate commented
how can I contribute?

2022-10-07 18:49 UTC, mishraabhinn commented
> how can I contribute?

[Contributing Guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)

2022-10-07 18:54 UTC, mishraabhinn commented
@Panquesito7 and @NasreenParween I really feel this is already being implemented. I wish to close this pr. Thanks for your contribution.  Please, join discord and gitter to remain more and more connected to the algorithms. https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/data_structures/linked_list.cpp

2022-11-28 04:35 UTC, Panquesito7 commented
> @Panquesito7 and @NasreenParween I really feel this is already being implemented. I wish to close this pr. Thanks for your contribution. Please, join discord and gitter to remain more and more connected to the algorithms. https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/data_structures/linked_list.cpp

Hmm, I'm not sure if we should keep it; after all, it's another implementation and I think we should accept it as long as it follows our contributing guidelines, of course. What do you think? 🙂
CC: @tjgurwara99.

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +    node<t>  *createnewnode(t val){
Add empty line and function description.

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +    void createnewlist(node<t> *newnode){
Add empty line and function description.

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +    // Function to insert a node at the end of the linked list.
Add empty line

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> + return;
Indentation

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> + {
while loop can be better

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +// Function to insert a after the node the linked list.
Add empty line

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +    void addbefore(node<t> *newnode){
Add description. Use camelCase for function names

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +    t deletespecific(t i){
Add function description.

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +            int c;
Initialize variables with default values. Multiple places found.

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +
Remove empty line and add before description

2022-11-28 04:56 UTC, krishnacx commented on data_structures/singly_linked_list2.cpp
> +        for(temp=start;temp!=NULL;temp=temp->next){
Use while

2022-12-08 15:00 UTC, tjgurwara99 requested changes
Once you have moved it into the desired namespace, I would review this again properly.

2022-12-08 15:00 UTC, tjgurwara99 commented on data_structures/singly_linked_list2.cpp
> +using namespace std;
You've used this but I suggest moving your implementation inside a separate `namespace` under the `data_structures` namespace. For reference, take a look [here](https://github.com/TheAlgorithms/C-Plus-Plus/blob/1371b5390abc98ab127c5a9057cbeff6e2afbbfb/data_structures/linked_list.cpp#L21-L31).

2022-12-08 15:02 UTC, tjgurwara99 commented
> Hmm, I'm not sure if we should keep it; after all, it's another implementation and I think we should accept it as long as it follows our contributing guidelines, of course. What do you think? 🙂
> CC: @tjgurwara99.

I'm a bit confused, by different implementation do you mean that the nitty gritty details are different? I don't think there is much difference to it than the one we already have if you're considering the difference in logic but if its just the implementation then I guess we can accept it.

2023-03-28 00:11 UTC, closed without merging