add find_single_number
TheAlgorithms/C-Plus-Plus pull request #2061
Opened 2022-10-02 11:44 UTC by literalEval

#### Description of Change

Added the question "Find non repeating number in an array of repeating numbers"

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-02 12:53 UTC, mishraabhinn requested changes
Nice work @literalEval. Thanks for contributing.  The pr code LGTM! Can we please rethink the name of the file? After reading the name of file I can not understand the purpose.

2022-10-02 13:08 UTC, literalEval commented
@mishraabhinn can you please suggest a better name ? 😅

2022-10-03 05:32 UTC, literalEval commented
Hey @mishraabhinn can you please merge this PR ?

2022-10-03 05:52 UTC, Panquesito7 requested changes
Great work! 🚀

2022-10-03 05:52 UTC, Panquesito7 commented on bit_manipulation/find_non_repeating_number.cpp
> +int find_single_number(std::vector<int>& nums) {
You're not modifying `nums`, but you're accessing it. Using `const` will make the program faster and better.
```suggestion
int find_single_number(const std::vector<int>& nums) {
```

2022-10-03 05:52 UTC, Panquesito7 commented on bit_manipulation/find_non_repeating_number.cpp
> + * @namespace setKthBit
```suggestion
 * @namespace find_single_number
```

2022-10-03 05:52 UTC, Panquesito7 commented on bit_manipulation/find_non_repeating_number.cpp
> +int find_single_number(std::vector<int>& nums) {
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). **Let us know if you need any help here or on our [Discord server](https://discord.gg/c7MnfGFGa6).** 🙂

2022-10-03 08:09 UTC, literalEval commented
@Panquesito7  please review again

2022-10-04 17:48 UTC, Panquesito7 commented on .vscode/settings.json
> -{
Please add this file back as it originally was.

2022-10-05 12:10 UTC, mishraabhinn approved these changes
Approved. Nice work @literalEval. Please join discord and gitter for staying more connected.

2022-10-05 14:55 UTC, literalEval commented
Done. Please merge this PR now. It has been hanging for a while now.

2022-10-05 15:53 UTC, mishraabhinn commented
Waiting for another approval.

2022-10-05 16:24 UTC, Panquesito7 requested changes

2022-10-05 16:24 UTC, Panquesito7 commented on .vscode/settings.json
> +}
```suggestion
}

```

2022-10-06 02:45 UTC, literalEval commented
@Panquesito7 Done. Hope it is finally good now 🫠

2022-10-07 18:48 UTC, mishraabhinn submitted a review, later dismissed

2022-10-10 12:56 UTC, literalEval commented
@Panquesito7

2022-11-28 05:03 UTC, Panquesito7 approved these changes
Awesome work! Thank you so much. 🚀

2022-11-28 05:11 UTC, merged