Secant Method Algorithm for Numerical Methods
TheAlgorithms/C-Plus-Plus pull request #2108
Opened 2022-10-04 21:06 UTC by fkkarakurt

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-05 21:10 UTC, Panquesito7 approved these changes
Great work! 🚀

2022-10-05 21:10 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +#include <iostream>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2022-10-05 21:10 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +/** Main Function */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2022-10-05 21:10 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +    } while (1);
```suggestion
    } while (1);
    return 0;
```

2022-10-05 21:10 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +double f(double x) { return x * x * x * x - 29.0; } // The Function f(x)
Please add documentation with detailed/brief description, parameters description, etc. etc..
Check our [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). You can see an example of the same here:
```c++
/**
 * Utility function to print matrix
 * @tparam n number of matrix size
 * @param board matrix where numbers are saved
 */
template <size_t n>
void printSolution(const std::array<std::array<int, n>, n> &board) {
    std::cout << "\n";
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            std::cout << "" << board[i][j] << " ";
        }
        std::cout << "\n";
    }
}
```

2022-10-07 20:11 UTC, fkkarakurt commented
I edited it a bit more and added annotations.

Have a nice day!

2022-12-02 21:18 UTC, Panquesito7 requested changes
Great work! 🚀

2022-12-02 21:18 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +#include <iostream> /// for IO operations
```suggestion
#include <cmath>    /// for built-in mathematical functions
#include <iomanip>  /// to identify the manipulator and `setprecision`
#include <iostream>  /// for IO operations
```

2022-12-02 21:18 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +    * @brief Information required for the secant method
Seems like the code above could be separated as a function with this documentation, IMO.

2022-12-02 21:18 UTC, Panquesito7 commented on numerical_methods/secant_method.cpp
> +
Please add self-test cases so we can verify your program works properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference**). Let us know if you need any help here or on our [**Discord server**](https://the-algorithms.com/discord). 😃

2023-02-28 00:10 UTC, closed without merging