Added area of Trapezoid.
TheAlgorithms/C-Plus-Plus pull request #2118
Opened 2022-10-05 05:58 UTC by devesh-0419

A quadrilateral with at least one pair of parallel sides is called a trapezoid.

[trapezoid](https://en.wikipedia.org/wiki/Trapezoid)

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-06 22:20 UTC, Panquesito7 submitted a review, later dismissed
Looks good. Thanks! 🎉

2022-10-06 22:21 UTC, Panquesito7 requested changes
Please fix the [`clang-tidy`](https://github.com/TheAlgorithms/C-Plus-Plus/actions/runs/3200854359/jobs/5228233552) warnings. Let us know if you need any help. 🙂

2022-10-07 06:17 UTC, devesh-0419 commented
Thanks, I am fixing the code

2022-10-07 07:47 UTC, devesh-0419 commented
please review my code. Fixed the bug that was mentioned earlier

2022-11-28 02:37 UTC, Panquesito7 commented on math/area.cpp
> + * @param base1 is the length of one of the parallel side of the trapezium
You may want to describe the `T` param as well.
```suggestion
 * @tparam <description>
 * @param base1 is the length of one of the parallel side of the trapezium
```

2023-02-05 12:53 UTC, krishnacx commented on math/area.cpp
> + * @param height is the length between both parallel side
can be reworded to "between parallel sides"

2023-02-19 00:12 UTC, closed without merging