Added program to swap two numbers using bitwise
TheAlgorithms/C-Plus-Plus pull request #2132
Opened 2022-10-05 11:51 UTC by PuneetTri

Detailed program to swap two numbers using bitwise operators. Also provided detailed proof of how the swapping happens. This program would be great for beginners to understand how we can use the bitwise operator to swap two numbers, as well as understand how the XOR operator works in general.

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-09 13:53 UTC, mishraabhinn reviewed
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them carefully and follow them. Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord). 🙂

2022-10-22 10:12 UTC, mishraabhinn requested changes

2022-10-22 10:12 UTC, mishraabhinn commented on bit_manipulation/swapping_two_numbers.cpp
> +#include<cassert> // For testcases check
```suggestion
#include<cassert> // For assert
```

2022-10-24 07:49 UTC, mishraabhinn reviewed
Thanks for the continuous changes with comments and for bearing with us. Good work. Approved.

2022-10-24 07:50 UTC, mishraabhinn approved these changes

2022-12-30 05:59 UTC, Panquesito7 requested changes
Good work! 👍
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/PuneetTri/C-Plus-Plus/actions

2022-12-30 05:59 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> + * More about it: https://betterexplained.com/articles/swap-two-variables-using-xor
Markdown link formatting should be used here.
```suggestion
 * @brief [Swap two numbers using Bitwise Operator](https://betterexplained.com/articles/swap-two-variables-using-xor) implementation
```

2022-12-30 05:59 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +bool bitwiseSwap(int a, int b) {
Functions should be documented explaining the use of its parameters, a brief description, and what it returns.

2022-12-30 05:59 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +static void test() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
static void test() {
```

2022-12-30 05:59 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +int main() {
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2023-01-13 17:11 UTC, Panquesito7 requested changes

2023-01-13 17:11 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +#include<cassert> // For assert
```suggestion
#include <iostream>  /// for IO operations
#include <cassert>  /// for assert
```

2023-01-13 17:11 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +bool bitwiseSwap(int a, int b) {
```suggestion
/**
 * @brief Bit Manipulation algorithms
 * @namespace
 */
namespace bit_manipulation {
bool bitwiseSwap(int a, int b) {
```

2023-01-13 17:11 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +}
```suggestion
}
}  // namespace bit_manipulation
```

2023-01-13 17:11 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +    assert(bitwiseSwap(7,7) == true); // TC #5
```suggestion
    assert(bit_manipulation::bitwiseSwap(2,3) == true); // TC #1
    std::cout << "Test-case: #2" << std::endl;
    assert(bit_manipulation::bitwiseSwap(0,53) == true); // TC #2
    std::cout << "Test-case: #3" << std::endl;
    assert(bit_manipulation::bitwiseSwap(622,733) == true); // TC #3
    std::cout << "Test-case: #4" << std::endl;
    assert(bit_manipulation::bitwiseSwap(-8246,-9357) == true); // TC #4
    std::cout << "Test-case: #5" << std::endl;
    assert(bit_manipulation::bitwiseSwap(7,7) == true); // TC #5
```

2023-02-19 05:23 UTC, krishnacx commented on bit_manipulation/swapping_two_numbers.cpp
> +    } else {
else condition may not be required.

2023-02-19 05:23 UTC, krishnacx commented on bit_manipulation/swapping_two_numbers.cpp
> +    assert(bitwiseSwap(7,7) == true); // TC #5
Any negative test cases ?

2023-02-27 22:56 UTC, Panquesito7 requested changes

2023-02-27 22:56 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +    test(); // Run multiple testcases to test our algorithm
```suggestion
    test(); // Run multiple testcases to test our algorithm
    return 0;
```

2023-02-27 22:56 UTC, Panquesito7 commented on bit_manipulation/swapping_two_numbers.cpp
> +bool bitwiseSwap(int a, int b) {
Still missing function documentation.

2023-03-07 00:11 UTC, closed without merging