feat: added Boyer Moore Algorithm
TheAlgorithms/C-Plus-Plus pull request #2133
Opened 2022-10-05 13:14 UTC by Tapesh-1308

I have added Boyer Moore String Pattern Searching Algorithm in the strings directory.
#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-05 17:45 UTC, Panquesito7 requested changes
Great work! 🚀
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/Tapesh-1308/C-Plus-Plus/actions

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> +using namespace std;
Do not use `using namespace std;`. Use `using std::cin`, `using std::cout`, etc. for each function.

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> +#define BAD 256
```suggestion
constexpr int BAD 256;
```

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> +#include <string>  // use this for MS Visual C++
```suggestion
#include <string>  /// use this for MS Visual C++
```

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> + * print where pattern found
```suggestion
 * @returns void
```

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> + * Boyer Moore algorithm to find a pattern in a text
```suggestion
 * @brief Boyer Moore algorithm to find a pattern in a text.
 * It will print where the pattern has been found.
```

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> +}
Missing an endline. Without this endline, there could be issues with some IDEs and configurations.
```suggestion
}

```

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> +/* Main Function */
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
```

2022-10-05 17:45 UTC, Panquesito7 commented on strings/boyer_moore_algorithm.cpp
> +
Please add self-test cases so we can verify your program works properly (**see the [typical structure of a program](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) as a reference**). Let us know if you need any help here or on our [**Discord server**](https://the-algorithms.com/discord). 😃

2022-10-07 13:02 UTC, Tapesh-1308 reviewed
Made all required changes, please review it

2022-10-09 14:10 UTC, mishraabhinn requested changes

2022-10-09 14:10 UTC, mishraabhinn commented on strings/boyer_moore_algorithm.cpp
> +#include <iostream>
comment the use

2022-10-09 17:14 UTC, mishraabhinn requested changes
I really want you to rename the variable name as such seeing the code I can get what it is doing not like I have to dry run to understand. Everyone can write code. But we should focus on writing clean and maintainable code.

2022-10-09 17:14 UTC, mishraabhinn commented on strings/boyer_moore_algorithm.cpp
> +void fillBadChar(int badChar[], int m, std::string pat) {
rename variable m and pat. It is not clear what is used for.

2022-10-09 17:14 UTC, mishraabhinn commented on strings/boyer_moore_algorithm.cpp
> +    for (int i = 0; i < BAD; i++) badChar[i] = -1;
rename variable i

2022-10-09 17:14 UTC, mishraabhinn commented on strings/boyer_moore_algorithm.cpp
> +    for (int i = 0; i < m; i++) badChar[(int)pat[i]] = i;
rename variable i

2022-10-09 17:14 UTC, mishraabhinn commented on strings/boyer_moore_algorithm.cpp
> +    int m = pat.length();
Please rename n, m I really can not infer what it's used for. Name according to the use.

2022-10-09 17:14 UTC, mishraabhinn commented on strings/boyer_moore_algorithm.cpp
> +    return ans;
Please rename the variable names. I can not infer what they are used for.

2023-02-18 00:10 UTC, closed without merging