Aryan Perfect Number
TheAlgorithms/C-Plus-Plus pull request #2147
Opened 2022-10-06 08:20 UTC by Stolen-king

Thanks for reading my pull request.
Here i have added a c++ program under math-directory section for finding out the PERFECT NUMBER.
I will be highly obliged if you kindly accept my pull request ,as this is my first pulll request and i ensure you that this program will definitely add more value to yours repository.
Thank you.

2022-10-06 08:23 UTC, Stolen-king commented
Thanks you for reading my pull request.
I will be honoured if you kindly merge my pull request as it contain a good code which will definitely add more value to your repository.

2022-11-27 16:57 UTC, Panquesito7 requested changes

2022-11-27 16:57 UTC, Panquesito7 commented on math/perfect_number.cpp
> +using namespace std;
These are discouraged. Please use each header/library you need and strictly use `std::`.

2022-11-27 16:57 UTC, Panquesito7 commented on math/perfect_number.cpp
> +int main() {
Separate the code into documented functions and structures if needed as well as add self-test cases using `assert` (requires the `cassert` library/header).

2023-02-01 00:11 UTC, closed without merging