Xor Of Sum Of All Pairs.cpp
TheAlgorithms/C-Plus-Plus pull request #2151
Opened 2022-10-06 13:54 UTC by souravchandra1910

Added Xor Of Sum Of All Pairs in cpp

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-10-06 19:33 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord).** 🙂

2022-10-07 05:26 UTC, souravchandra1910 commented
I have made the changes

2022-10-07 13:39 UTC, souravchandra1910 commented
Please see through

2022-11-28 04:33 UTC, Panquesito7 requested changes
1. Please rename the file accordingly to match snake_case.
2. Explain the use of the algorithm in sections and the correct use of `*`. For example:

```c++
/**
 * @file
 * @brief Implementation of the [<algorithm>](<Wikipedia link or source for algorithm explanation>)
 *
 * @details
 * <Detailed description of the algorithm>
 * <Space complexity and other technical stuff>
 *
 * @author [<name>](<GitHub link)
 */
```

3. Put the functions into namespaces (except for `main` and the tests).
4. Other details can be found at our [**contributing guidelines**](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).

If you need any help, let us know here or on our [**Discord server**](https://the-algorithms.com/discord)! 🙂

2022-11-28 04:33 UTC, Panquesito7 commented on bit_manipulation/Xor Of Sum Of All Pairs.cpp
> +using namespace std;
These are discouraged. Please use each header/library you need and strictly use `std::`.

2022-11-28 04:33 UTC, Panquesito7 commented on bit_manipulation/Xor Of Sum Of All Pairs.cpp
> +  int xor_sum(vector<int> &v1)
Functions should be documented explaining the use of its parameters, a brief description, and what it returns.

2022-11-28 04:33 UTC, Panquesito7 commented on bit_manipulation/Xor Of Sum Of All Pairs.cpp
> +  if (cnt == 5)
Test cases should be made using `assert` (requires adding the `cassert` library/header).

2023-01-30 00:09 UTC, closed without merging