Added vertex cover
TheAlgorithms/C-Plus-Plus pull request #2154
Opened 2022-10-06 15:37 UTC by Rajat379

Added a new file which covers the vertex cover of a graph.

#### Checklist

- [ x] Added description of change
- [ x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ x] Added tests and example, test must pass
- [ x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ x] Relevant documentation/comments is changed or added
- [ x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x ] I acknowledge that all my contributions will be made under the project's license.

2022-10-06 17:22 UTC, Panquesito7 requested changes
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord).** 🙂

2022-10-07 09:44 UTC, Rajat379 commented
@Panquesito7 Kindly have a look now, updated the file.

2022-11-28 04:26 UTC, Panquesito7 requested changes

2022-11-28 04:26 UTC, Panquesito7 commented on graph/vertex_cover.cpp
> +Graph::Graph(int V) {
Functions should be documented explaining the use of its parameters, a brief description, and what it returns.

2022-11-28 04:26 UTC, Panquesito7 commented on graph/vertex_cover.cpp
> +#include <list>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2022-11-28 04:26 UTC, Panquesito7 commented on graph/vertex_cover.cpp
> +  Implementation of a vertex cover in a graph.
Please describe how the algorithm works, a Wikipedia or any other source for algorithm explanation, what the algorithm does, etc..

2023-01-28 00:09 UTC, closed without merging