Hangman Game in C++
TheAlgorithms/C-Plus-Plus pull request #2169
Opened 2022-10-07 09:25 UTC by Chandra0804

#### Description of Change

#### Checklist

- [x ] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Relevant documentation/comments is changed or added
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-01-06 22:29 UTC, Panquesito7 requested changes
Feel free to add the game in a new folder named `games`. 🙂

2023-01-06 22:29 UTC, Panquesito7 commented on others/Hangman_game/Hangman.cpp
> +#include <string.h>
```suggestion
#include <cstring>
```

2023-01-06 22:29 UTC, Panquesito7 commented on others/Hangman_game/Hangman.cpp
> +#include <time.h>
```suggestion
#include <ctime>
```

2023-01-06 22:29 UTC, Panquesito7 commented on others/Hangman_game/Hangman.cpp
> +using namespace std;
This is discouraged. Please strictly use `std::` for each of its members.

2023-01-06 22:29 UTC, Panquesito7 commented on others/Hangman_game/Hangman.cpp
> +void print_string(char b[], int k, int len)
Functions should be documented explaining the use of its parameters, a brief description, and what it returns.

2023-02-07 06:04 UTC, krishnacx commented on DIRECTORY.md
> +  * Hangman Game
This is not required

2023-02-07 06:04 UTC, krishnacx commented on DIRECTORY.md
> +    * [Hangman](https://github.com/TheAlgorithms/C-Plus-Plus/blob/HEAD/others/Hangman_game/Hangman.cpp)
Follow the alphabetical order

2023-02-07 06:04 UTC, krishnacx commented on others/Hangman_game/Hangman.cpp
> +#include <time.h>
Add header comments

2023-02-16 00:10 UTC, closed without merging