Add double linear search
TheAlgorithms/C-Plus-Plus pull request #2249
Opened 2022-10-13 22:50 UTC by Markaeus

#### Description of Change
Added the cpp implementation of the double linear search based on the python variation with tests included.

#### Checklist
- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

2022-12-28 00:22 UTC, Panquesito7 requested changes

2022-12-28 00:22 UTC, Panquesito7 commented on search/double_linear_search.cpp
> +#include <iostream>
Please describe how the algorithm works, a Wikipedia or any other source for algorithm explanation, what the algorithm does, etc..

2022-12-28 00:22 UTC, Panquesito7 commented on search/double_linear_search.cpp
> +#include <cassert>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2022-12-28 00:22 UTC, Panquesito7 commented on search/double_linear_search.cpp
> +int double_linear_search(std::vector<int> list, int search_item) {
Functions should be documented explaining the use of its parameters, a brief description, and what it returns.

2022-12-28 00:22 UTC, Panquesito7 commented on search/double_linear_search.cpp
> +    std::cout << "Expected value" << expected << " in search for " << number
Functions should always include `assert` checks to make sure it works 100% as excepted (requires the `cassert` library).

2022-12-28 00:22 UTC, Panquesito7 commented on search/double_linear_search.cpp
> +void test(std::vector<int> list, int number, int expected) {
Best not to include parameters and include those in the `main` function.
```suggestion
static void test(std::vector<int> list, int number, int expected) {
```

2022-12-28 00:22 UTC, Panquesito7 commented on search/double_linear_search.cpp
> +int main() {
```suggestion
/**
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
```

2023-01-30 10:29 UTC, krishnacx commented on others/stairs_pattern.cpp
>      std::cout << "Enter number of pair - ";
pairs ?

2023-02-07 00:58 UTC, closed without merging