Updated discord links closes  #2274
TheAlgorithms/C-Plus-Plus pull request #2280
Opened 2022-10-17 07:38 UTC by zafar-hussain

#### Description of Change

#### Checklist

- [x] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

with reference to issue  #2274 "[OTHER] Update Discord links #2274", discord links (x4) were updated to https://the-algorithms.com/discord/

2022-10-17 07:42 UTC, zafar-hussain commented
@reviewers

please, if you can add "hacktoberfest-accepted" label, if this PR is fulfilled

cheers

2022-10-18 06:45 UTC, zafar-hussain commented
@Panquesito7

Please if you can check and advice on this PR

cheers

2022-10-21 19:25 UTC, Panquesito7 requested changes

2022-10-21 19:25 UTC, Panquesito7 commented on strings/naive_pattern_search.cpp
> +// # Part of Cosmos by OpenGenus Foundation
Please make a separate PR for this change. Thank you. 🙂

2022-10-21 19:25 UTC, Panquesito7 commented on strings/test_naive_pattern_search.cpp
> +/**
Same here.

2022-11-03 12:53 UTC, closed without merging