Strassen's Matrix Multiplication
TheAlgorithms/C-Plus-Plus pull request #2413
Opened 2022-12-29 05:53 UTC by AshishYUO

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2022-12-29 06:33 UTC, Panquesito7 requested changes
Great work! 🚀 Will check the code later on.

2022-12-29 06:33 UTC, Panquesito7 commented on divide_and_conquer/strassen_matrix_multiplication.cpp
> +#include <vector>
Please add a one-line description of what the library/header is for (**see the example below**).

```c++
#include <iostream>    /// for IO operations
#include <cassert>    /// for assert
```

2022-12-29 06:33 UTC, Panquesito7 commented on divide_and_conquer/strassen_matrix_multiplication.cpp
> +#include <cassert>
Please describe how the algorithm works, a Wikipedia or any other source for algorithm explanation, what the algorithm does, etc..

2022-12-29 06:33 UTC, Panquesito7 commented on divide_and_conquer/strassen_matrix_multiplication.cpp
> +void test() {
```suggestion
/**
 * @brief Self-test implementations
 * @returns void
 */
static void test() {
```

2022-12-29 06:33 UTC, Panquesito7 commented on divide_and_conquer/strassen_matrix_multiplication.cpp
> +    test();
```suggestion
 * @brief Main function
 * @returns 0 on exit
 */
int main() {
    test();  // run self-test implementations
```

2023-01-01 10:29 UTC, AshishYUO commented
@Panquesito7 The changes are done. Let me know if it needs more corrections.

2023-01-13 17:38 UTC, Panquesito7 approved these changes
Very good work. Thanks! 🚀
The only thing I saw is that it takes quite a long time to compile (used the Gitpod ready-to-code service). Is this normal?

![image](https://user-images.githubusercontent.com/51391473/212384028-36261d47-f061-4312-a96d-00ac38334b33.png)

If so, you might want to add a note for that in the code or in a print statement.

2023-01-13 18:16 UTC, AshishYUO commented
I usually test the code with optimize flags. I never thought this would actually run that much slow without the flags.
I have reduced the size of the matrix at the moment, it'll now take at most 4-5 seconds.

2023-01-18 18:24 UTC, tjgurwara99 approved these changes

2023-01-24 20:02 UTC, Panquesito7 approved these changes
Much better on time! Thanks. 🚀

2023-01-24 20:03 UTC, merged