fix:Fit `Binominal calculate.cpp` to guidelines
TheAlgorithms/C-Plus-Plus pull request #2464
Opened 2023-05-17 11:47 UTC by ewd00010

#### Description of Change
FIX: altered the structure of if else if statements to have guard clauses first before main functionality, added brackets to make calculation steps more clear (Following BODMAS), updated namespaces used in file, removed unneeded user input code

CHORE: Added explanations and other documentation

#### Checklist
- [x] Added description of change
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: still no clangd working for me, file may need checked 
I'm pretty sure I could do a recursive version of this code, should I make one and add it as a function to this file?

2023-05-18 11:14 UTC, ewd00010 commented
maybe we should change the file name to just be `binominal_coefficient.cpp` aswell

2023-05-23 12:06 UTC, realstealthninja commented on math/binomial_calculate.cpp
> + * coefficients are notated] (n; k) is the number of ways of picking k unordered
```suggestion
 * binomial coefficient \f$ \binom{n}{k} \f$ is the number of ways of picking \f$k\f$ unordered
```

2023-05-23 12:22 UTC, realstealthninja commented on math/binomial_calculate.cpp
> + * outcomes from n possibilities, also known as a combination or combinatorial
```suggestion
 * outcomes from \f$n\f$ possibilities, also known as a combination or combinatorial
```

2023-05-23 12:25 UTC, realstealthninja commented on math/binomial_calculate.cpp
> + * number. The symbols [ _ representing subscript ] _nC_k and (n; k) are used to
```suggestion
 * number. The symbols \f$ _nC_k \f$ and \f$ \binom{n}{k} \f$ are used to
```

2023-05-23 12:25 UTC, realstealthninja commented on math/binomial_calculate.cpp
> + * denote a binomial coefficient, and are sometimes read as "n choose k." (n; k)
```suggestion
 * denote a binomial coefficient, and are sometimes read as "n choose k." \f$ \binom{n}{k} \f$
```

2023-05-23 12:28 UTC, realstealthninja commented on math/binomial_calculate.cpp
> + * @note An identity of the binomial coefficient is (n; n-k) This is explained
```suggestion
 * @note An identity of the binomial coefficient is \f$ \binom{n}{n-k} \f$ This is explained
```

2023-05-30 14:13 UTC, ewd00010 commented on math/binomial_calculate.cpp
> -namespace binomial {
reverted

2023-05-31 03:51 UTC, Panquesito7 requested changes

2023-05-31 03:51 UTC, Panquesito7 commented on math/binomial_calculate.cpp
> -namespace math {
Please add the `math` namespace back.

2023-06-05 09:18 UTC, alexpantyukhin approved these changes

2023-06-08 04:26 UTC, Panquesito7 requested changes

2023-06-08 04:26 UTC, Panquesito7 commented on math/binomial_calculate.cpp
> +namespace math { namespace binomial {
Please add the `math` namespace documentation back.

2023-07-05 11:34 UTC, realstealthninja requested changes

2023-07-05 11:34 UTC, realstealthninja commented on math/binomial_calculate.cpp
> +namespace math { namespace binomial {
this needs to be documented as well

2023-07-05 11:34 UTC, realstealthninja commented on math/binomial_calculate.cpp
> +namespace math { namespace binomial {
```suggestion
namespace math { 
namespace binomial {
```

2023-08-13 00:09 UTC, closed without merging