fix:fit `check_amicable_pair.cpp` to guidelines
TheAlgorithms/C-Plus-Plus pull request #2465
Opened 2023-05-18 11:56 UTC by ewd00010

#### Description of Change
FIX:  initlized sum to 1 instead of adding it before return
CHORE: cleaned documentation aswell as adding new documentation, namespace math added

#### Checklist
- [x] Added description of change
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: could use clang-tidy check like my previous pull requests

2023-05-23 11:48 UTC, realstealthninja requested changes

2023-05-23 11:48 UTC, realstealthninja commented on math/check_amicable_pair.cpp
> +#include <iostream>  // for cout
```suggestion
#include <cassert>   /// for assert
#include <iostream>  /// for cout
```

2023-05-27 01:15 UTC, realstealthninja approved these changes
Thank you for your pr. We greatly appreciate your help here. Now the maintainers will review your pr! ❤️

2023-05-30 03:48 UTC, Panquesito7 requested changes

2023-05-30 03:48 UTC, Panquesito7 commented on math/check_amicable_pair.cpp
> +void tests() {
```suggestion
static void tests() {
```

2023-05-30 03:48 UTC, Panquesito7 commented on math/check_amicable_pair.cpp
> +    std::cout << "all tests have passed" << std::endl;
```suggestion
    std::cout << "All tests have successfully passed!" << std::endl;
```

2023-05-31 04:22 UTC, Panquesito7 commented on math/check_amicable_pair.cpp
> +#include <iostream>  /// for cout
```suggestion
#include <iostream>  /// for IO operations
```

2023-06-19 04:37 UTC, realstealthninja submitted a review, later dismissed
LGTM! great work

2023-06-21 02:13 UTC, Panquesito7 submitted a review, later dismissed
Awesome. Thanks! 🚀

2023-06-22 00:48 UTC, realstealthninja submitted a review, later dismissed
Great work

2023-06-23 20:06 UTC, Panquesito7 approved these changes

2023-06-23 20:06 UTC, merged