Feat: Added Shoelace algorithm
TheAlgorithms/C-Plus-Plus pull request #2472
Opened 2023-05-28 06:30 UTC by Renjian-buchai

#### Description of Change

Feat: Added shoelace algorithm 

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-05-28 13:52 UTC, realstealthninja requested changes

2023-05-28 13:52 UTC, realstealthninja commented on math/iterative_factorial.cpp
> + * @author [Renjian-buchai](https://github.com/Renjian-buchai)
bit of a nit pick but would you mind moving the author tag to the bottom as is tradition

2023-05-28 13:52 UTC, realstealthninja commented on math/iterative_factorial.cpp
> +    }
please add a print statement saying all tests have passed;
```suggestion
    }
    std::cout << ""all tests have passed\n"
```

2023-05-28 13:52 UTC, realstealthninja commented on math/shoelace_algorithm.cpp
> + * = 0.5 | (\x1, \y1) (\x2, \y2) ... (\xn, \yn) (\x1, \y1) |
i think you need to add \f$ for \x1 to be recognized.

2023-05-28 13:52 UTC, realstealthninja commented on math/shoelace_algorithm.cpp
> +
```suggestion
/**
 * @namespace
 * @brief Mathematical algorithms
 */
```

2023-05-28 13:52 UTC, realstealthninja commented on math/shoelace_algorithm.cpp
> +}
```suggestion
}

```

2023-05-28 13:52 UTC, realstealthninja commented on math/shoelace_algorithm.cpp
> +    assert(math::shoelace(case4) == 28.5);
```suggestion
    assert(math::shoelace(case4) == 28.5);
    std::cout << "all tests have passed"
```

2023-05-28 13:52 UTC, realstealthninja commented on math/shoelace_algorithm.cpp
> +    // Cross multiplies \xn and \x1
i dont think documentation tags work in comments

2023-05-30 02:24 UTC, realstealthninja requested changes

2023-05-30 02:24 UTC, realstealthninja commented on math/iterative_factorial.cpp
> + * 5! = 5 * 4 * 3 * 2 * 1
Could you turn this into a LaTex formating

2023-06-09 15:57 UTC, Panquesito7 requested changes
Please create separate PRs for each file.
This will make it easier to review one as best as possible. 🙂

2023-07-25 00:11 UTC, closed without merging