Next higher number with same set bits implemented
TheAlgorithms/C-Plus-Plus pull request #2484
Opened 2023-06-12 16:44 UTC by Kunal766

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-06-13 19:32 UTC, Panquesito7 requested changes

2023-06-13 19:32 UTC, Panquesito7 commented on bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
> + It contains two logic 1 bits. The next higher number with two logic 1 bits is 17 (100012).
```suggestion
 * It contains two logic 1 bits. The next higher number with two logic 1 bits is 17 (100012).
```

2023-06-13 19:32 UTC, Panquesito7 commented on bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
> + * @param x is the number who's next number will be calculated
```suggestion
 * @brief The main function implements checking the next number
 * @param x the number that will be calculated
```

2023-06-13 19:32 UTC, Panquesito7 commented on bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
> +int next_higher_number(int x)
Consider using `uint64_t` for non-negative values (or their appropriate size: `uint32_t`, `uint16_t`, `uint8_t`) or `int64_t` for negative values. Check other parts of the code ([reference](https://en.cppreference.com/w/cpp/types/integer)). **Let us know if you need any help here or on our [Discord server](https://the-algorithms.com/discord).** 🙂

2023-06-13 19:32 UTC, Panquesito7 commented on bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
> +    std::cout << "All test cases successfully passed!" << std::endl;
```suggestion

    std::cout << "All test cases have successfully passed!" << std::endl;
```

2023-06-15 18:32 UTC, Panquesito7 approved these changes
Amazing. Thanks! 🚀

2023-06-16 07:53 UTC, realstealthninja requested changes
bit of it a nit pick, but thank you so much for your contribution!

2023-06-16 21:13 UTC, Panquesito7 commented on bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
> +  uint64_t rightOne;
We should probably use `snake_case`. I'll create a discussion in the repository. 👍

2023-06-19 04:05 UTC, realstealthninja approved these changes
LGTM

2023-06-21 02:16 UTC, Panquesito7 commented on bit_manipulation/next_higher_number_with_same_number_of_set_bits.cpp
> +  uint64_t rightOne;
What should we do about this? Should we keep it as-is or?

2023-06-23 19:43 UTC, Panquesito7 approved these changes

2023-06-23 19:45 UTC, merged