Typo Fix
TheAlgorithms/C-Plus-Plus pull request #2490
Opened 2023-06-21 09:54 UTC by mmvergara

2023-06-22 00:46 UTC, realstealthninja commented
Please do follow the pull request description given to you as it makes it easier for us to review

2023-06-22 00:47 UTC, realstealthninja submitted a review, later dismissed
Nice spotting the typo!

2023-06-23 20:01 UTC, Panquesito7 approved these changes
Cool! Thanks. 🎉

2023-06-23 20:03 UTC, Panquesito7 requested changes
Looks like the whole file will need updating to our guidelines, as the CI is complaining about it.
Would you like to work on this, @mmvergara, or create an issue for the same?

2023-06-24 02:53 UTC, mmvergara commented
> Looks like the whole file will need updating to our guidelines, as the CI is complaining about it. Would you like to work on this, @mmvergara, or create an issue for the same?

i'd like to work on it but sorry i don't really know how CI works, im kinda new to github. i might ruin something.

2023-06-24 05:01 UTC, realstealthninja commented
> > Looks like the whole file will need updating to our guidelines, as the CI is complaining about it. Would you like to work on this, @mmvergara, or create an issue for the same?
> 
> i'd like to work on it but sorry i don't really know how CI works, im kinda new to github. i might ruin something.

no no he is asking you to fix the whole file and make it look better.
ie documenting code

2023-06-25 00:00 UTC, mmvergara commented
What  did i just do lol, sorry i really don't know how the flow in these PR's work 💀

2023-06-25 04:06 UTC, realstealthninja commented
you merged your pr with the main branch! i.e update your pull request so its up to date

2023-06-25 04:14 UTC, realstealthninja requested changes
when we mean `fix` the algorithm we mean is document and comment on the algorithm 
make it neat and understandable. 
try reading the contribution guidelines

2023-06-25 04:14 UTC, realstealthninja commented on greedy_algorithms/dijkstra.cpp
>      // Constructs a graph with V vertices and E edges
```suggestion
    /**
     * @brief Constructs a graph
     * @param V number of vertices of the graph
     */
```

2023-06-25 04:14 UTC, realstealthninja commented on greedy_algorithms/dijkstra.cpp
> +    // Adds an edge to the graph
```suggestion
    /** 
     * @brief Adds an edge to the graph
     * @param src the graph the edge should be added to
     * @param dst the position where the edge should be added to
     * @param weight the weight of the edge that should be added
     * @returns void
     */
```

2023-07-19 14:28 UTC, mmvergara commented
> 1. Please use `climits` instead of `limits.h`.
> 2. Do not use `using namespace std`. Use `using <function>` (such as `std::cout`) or directly their namespace name.
> 3. Make sure to provide documentation and explanation of the algorithm, author, links, and **self-test implementations**.
> 
> If you need any help with this, let us know! 🙂

aight yeah. can someone actually finish this PR for me, sorry i'm not so used to github or C++ or this algorithm (yet).

2023-07-20 06:40 UTC, Panquesito7 commented
I'll work on this in the next few days. Thank you for contributing. 🙂

2023-07-20 06:40 UTC, closed without merging