updated implementation with vectors and added test
TheAlgorithms/C-Plus-Plus pull request #2511
Opened 2023-07-23 10:59 UTC by codingspace1

#### Description of Change

-Replaced the 2d arrays with vectors
-Added tests
-Created the function which returns true or false based on the sparsity of the matrix

#### Checklist

- [Yes ] Added description of change
- [Yes ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ Yes] Added tests and example, test must pass
- [yes ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ Yes] Relevant documentation/comments is changed or added
- [ Yes] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [Yes ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [Yes ] I acknowledge that all my contributions will be made under the project's license.

Notes: 
New implementation with vectors and added test

2023-07-23 13:21 UTC, realstealthninja requested changes
Thank you for contributing, just a few corrections here and there!

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +/*
please follow contribution guidelines in documenting the code

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +}
```suggestion
}

```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +    tests();
```suggestion
    tests(); // run self-test implementations
```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +int main()
please document the main function according to the contribution guidelines

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +using namespace std;
```suggestion
```
please do not do using namespace std;
instead use std::

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +    }
```suggestion
   return !(zero_counter > (vect.size() * vect[0].size()) * 0.5
```
this could just return the result of the condition

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +#include<vector>
```suggestion
#include<vector> /// for std::vector
```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +#include<iostream>
```suggestion
#include<iostream> /// for I/O operations
```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +#include<cassert>
```suggestion
#include<cassert> /// for assert
```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +bool is_sparse_matrix(vector<vector<int>> vect)
```suggestion
bool is_sparse_matrix(std::vector<std::vector<int>> vect)
```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +        cout<<endl;
```suggestion
        cout<< "\n";
```
should use \n instead of endl

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +
```suggestion
/**
 * @brief self-test implementation
 * @return void
 */
```

2023-07-23 13:21 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +
```suggestion

/**
 * @brief Main function
 * @return 0 on successful exit
 */
```

2023-07-24 06:18 UTC, madhavgaba commented on others/sparse_matrix_with_vectors.cpp
> +        for(int j = 0; j<vect[i].size(); j++)
indent

2023-07-24 06:18 UTC, madhavgaba commented on others/sparse_matrix_with_vectors.cpp
> +    return (zero_counter>(vect.size() * vect[0].size())* 0.5); //return 1 if zero values are more than non zero values
maybe add a linter locally

2023-07-24 06:51 UTC, codingspace1 commented on others/sparse_matrix_with_vectors.cpp
> +    return (zero_counter>(vect.size() * vect[0].size())* 0.5); //return 1 if zero values are more than non zero values
will do

2023-07-24 06:51 UTC, codingspace1 commented on others/sparse_matrix_with_vectors.cpp
> +        for(int j = 0; j<vect[i].size(); j++)
updated

2023-07-24 15:53 UTC, codingspace1 commented
Please review the updated changes

2023-08-03 14:14 UTC, realstealthninja requested changes

2023-08-03 14:14 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> + * @returns zero if matrix is not sparse
```suggestion
 * @returns 0 if matrix is not sparse
```

2023-08-03 14:14 UTC, realstealthninja commented on others/sparse_matrix_with_vectors.cpp
> +    test3();  // run self-test implementation #3
should consolidate these tests into a single test
i.e
```c++
tests() {
   some_specific_case();
   some_other_case();
}
```
and in main
```cpp
tests() // run self-test implementations
```
also adding a different function for each case which are not that unique seems a bit redundant dont you think?

2023-09-10 00:09 UTC, closed without merging