feat: add Carmichael generator
TheAlgorithms/C-Plus-Plus pull request #2526
Opened 2023-08-24 21:23 UTC by imengus

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-08-25 15:10 UTC, realstealthninja requested changes

2023-08-25 15:10 UTC, realstealthninja commented on math/carmichael.cpp
> +}
```suggestion
}

```

2023-08-25 15:10 UTC, realstealthninja commented on math/carmichael.cpp
> +
```suggestion
```

2023-08-25 15:10 UTC, realstealthninja commented
Thank you so much for contributing! :heart:

2023-08-25 15:13 UTC, imengus commented on math/carmichael.cpp
> +using namespace std;
I think I have enough functions that prefixing each with std:: would decrease the readability. Are you suggesting that I replace that line with `using std::name` only?

2023-08-25 20:50 UTC, imengus commented on math/carmichael.cpp
> +using namespace std;
Sorry to admit it but this is my first C/C++ program! 

I misunderstood initially, but trying to prefix each function with std I had the following kind of error for each function: `namespace "std" has no member "__gmpz_clear". I had written std::mpz_* as part of the imports without knowing this error would arise.

When I simply omit `using namespace std;` without changing the code (so without prefixes) the code runs normally. The online examples of gmp code I saw also didn't include this line, so would prefixing still be necessary?

2023-08-29 09:40 UTC, realstealthninja requested changes

2023-08-29 09:40 UTC, realstealthninja commented on math/carmichael.cpp
> +using namespace std;
its not necessary.  It is necessary for any function from the standard library i.e cout.
in your case if it works without prefixing then its fine! just omit using namespace std;
its bad practice to do using namespace std hence my initial comment.

2023-08-29 09:40 UTC, realstealthninja commented on math/carmichael.cpp
> +using namespace std;
```suggestion
```

2023-08-29 09:40 UTC, realstealthninja commented on math/carmichael.cpp
> +    assert(isCarmichael(n, a, output) == false);
```suggestion
    assert(isCarmichael(n, a, output) == false);
    
    std::cout << "All tests have passed successfully";
```

2023-08-29 09:40 UTC, realstealthninja commented on math/carmichael.cpp
> +    tests();
```suggestion
    tests(); // run self-implemented tests
```

2023-10-07 00:09 UTC, closed without merging