[feat/docs/test]: add centroid graph algorithm
TheAlgorithms/C-Plus-Plus pull request #2527
Opened 2023-08-25 15:28 UTC by flo456123

#### Description of Change

This change adds a new "centroid" graph algorithm. I do not think this algorithm is widely known, but it is used to find the centers of a tree. This can be useful because the center provides a good place to root a tree in a balanced manner.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-08-29 09:46 UTC, realstealthninja requested changes

2023-08-29 09:46 UTC, realstealthninja commented on graph/centroid.cpp
> +}
```suggestion
}

```

2023-08-29 09:46 UTC, realstealthninja commented on graph/centroid.cpp
> +    f2();
```suggestion
    tests(); // run self-implemented tests
```

2023-08-29 09:46 UTC, realstealthninja commented on graph/centroid.cpp
> +
could you compress all the functions to this function  since i don think they are that much different from each other apart from size

2023-08-29 09:46 UTC, realstealthninja commented on graph/centroid.cpp
> +
also add tests when tree has zero  or a negative value

2023-08-29 09:46 UTC, realstealthninja commented on graph/centroid.cpp
> +bool valid_centers(const int size) {
document this function please

2023-08-31 00:34 UTC, flo456123 commented on graph/centroid.cpp
> +
i implemented this test as just an empty tree containing only zero, should i make a more detailed tree or is this acceptable?

2023-10-31 15:33 UTC, floington500 commented
will this ever get merged

2024-01-29 14:39 UTC, realstealthninja approved these changes
@Panquesito7  could you have a look thanks!

2024-02-06 00:10 UTC, closed without merging

2024-02-06 02:21 UTC, floington500 commented
its almost been half a year since i opened this 😭