Fix, Docs, Test: Fibonacci_fast (Renamed to Fibonacci_iterative)
TheAlgorithms/C-Plus-Plus pull request #2614
Opened 2023-10-09 15:04 UTC by Renjian-buchai

#### Description of Change

The original algorithm does not calculate the nth fibonacci number, but rather the next fibonacci number after storing it in a static variable. Thus, I abstracted the looping part out of the code that you have to write upon application, into the function itself.

The function also does not calculate the nth fibonacci number, but rather the (n+1)th fibonacci number.

The "Test" in main does not really test anything, rather demonstrates what it does. Added actual unit tests with test cases.

The file brief did not explain what it actually does properly.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Fixed bugs, added documentation, and unit tests for Fibonacci_fast (Renamed to Fibonacci_iterative to better reflect what it actually does). 

For #2456.

2023-10-09 15:05 UTC, Renjian-buchai commented
I genuinely don't know what the original author was trying to do here, tbh.

2023-10-15 06:22 UTC, realstealthninja requested changes

2023-10-15 06:22 UTC, realstealthninja commented on math/fibonacci_iterative.cpp
> +    test();
```suggestion
    test(); // run self-test implementations
```

2023-11-15 14:02 UTC, realstealthninja approved these changes
LGTM

2024-03-17 06:17 UTC, realstealthninja commented
@Panquesito7  could we get this merged?

2024-03-17 06:18 UTC, realstealthninja approved these changes

2024-05-03 14:45 UTC, closed without merging