PriorityQueue
TheAlgorithms/C-Plus-Plus pull request #2630
Opened 2023-10-15 14:57 UTC by AbhirajBose

#### Description of Change

This is a pull request regarding the Implementation of Priority Queue using Linked List.In this file I have made a code regarding the Priority Queue.Priority Queue is a type of Data Structure which uses the concept of LinkedList to arrange the data in order of priority as instructed by the user.
Contributors guide: https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md
-->

#### Checklist

- [1]Implementation of Priority Queue using Linked List 
- [ ] priorityqueue.cpp(https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [3 ] Added tests and example, test passed
- [4] Added documentation and the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [5] Relevant documentation/comments is changed or added
- [6] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [7] Searched previous suggestions before making a new one.
- [8] I acknowledge that all my contributions will be made under the project's license.

Notes:

2023-10-15 14:58 UTC, AbhirajBose commented
@Panquesito7 ans @realstealthninja Please check my PR and if possible merge it.

2023-10-16 16:11 UTC, NitishPal2013 commented
@AbhirajBose your PR message has numbers instead of checks in the checkbox. kindly read the markdown down syntax for the adding the checkbox.

Great work by the way but need some more work on this. These are some suggestions:

1) You have not added any test cases. Please add the test cases.
2) Do add the docs about your code. It will help other fellow developers to understand it.
3) Do read the contribution guidelines for the correct format of code and the PR.

2023-10-17 05:51 UTC, AbhirajBose commented
@NitishPal2013 Please check it out once now

2023-10-17 07:41 UTC, NitishPal2013 commented
@AbhirajBose , it still does not follow the [contribution guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/6376bf46aff52a1944d4efcd5ae884b39119cd34/CONTRIBUTING.md). ping me in the discord community general server if you have any problem in understanding it. My discord username nitish_pal .

2023-10-18 01:07 UTC, MogomotsiFM requested changes
- Add a function to retrieve one item from the priority queue for possible processing: that is, int PQ::front()
- Almost all your comments are not necessary because your code is easy to follow,
- I would rename the function PQ::remove to PQ::clear. That is what the std library names functions that erase all the contents of a container.
- If you are familiar with std::shared_ptr and std::make_shared use them instead of raw pointers. Otherwise, keep the raw pointers.

2023-10-27 15:44 UTC, AbhirajBose commented
@MogomotsiFM Please check my PR now

2023-10-27 16:13 UTC, NitishPal2013 reviewed
@AbhirajBose do read the suggestions from @MogomotsiFM again. You are on the right way but still need some work.
Remove the unnecessary comments and kindly follow the Doxygen format to document your code.

2023-10-27 16:13 UTC, NitishPal2013 commented on data_structures/priority_queue.cpp
> +};
Define your structure above from it. 
One more thing whenever we write code, we try that our code must be self explanatory by choosing appropriate variable name and flow of code, which is fine with your code. So, the comments you have added are not necessary here. This is same thing which @MogomotsiFM was highlighting in the suggestions.

2023-10-27 16:13 UTC, NitishPal2013 commented on data_structures/priority_queue.cpp
> +};
Describe the same above from it.

2023-10-27 16:13 UTC, NitishPal2013 commented on data_structures/priority_queue.cpp
> +        delete temp;          // deleting the temporary variable
All the comments are not unnecessary. You should remove them.

2023-10-27 16:55 UTC, AbhirajBose commented
@NitishPal2013 Please check it now

2023-10-27 18:06 UTC, MogomotsiFM approved these changes
Looks good to me. 

I hope you think that the code is cleaner and not cluttered without comments.

2023-10-27 18:08 UTC, AbhirajBose commented
@MogomotsiFM Yes,it is.If possible,please merge my PR.

2023-12-13 00:10 UTC, closed without merging