Rework on Stack Array Data Structure
TheAlgorithms/C-Plus-Plus pull request #2683
Opened 2024-03-18 02:15 UTC by TruongNhanNguyen

- The `Stack` class is placed within the `data_structures` namespace
- The destructor is added to the Stack class to ensure memory deallocation
- Comments are added to the member functions to describe their purpose
- The self-test function is provided, which demonstrates the usage of the Stack class

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-03-19 01:53 UTC, TruongNhanNguyen commented
Please take a look on this PR @realstealthninja, @Panquesito7

2024-04-19 00:42 UTC, TruongNhanNguyen commented
Could you have a look on this PR @realstealthninja

2024-04-28 10:01 UTC, mrmagic2020 approved these changes
Both maintainers of this repo are rather busy these days, so I'll do a quick review. 
Very solid rework and documentation. Have you considered adding methods like `empty()` and `full()`? They might help client code to handle these cases before operations like `pop()` and `push()`.
Overall I think this is merge-worthy. Up to the maintainers to make further decision :)

2024-04-30 22:30 UTC, mrmagic2020 commented
> Can you add **don't-close** label for this PR, @mrmagic2020?

Sorry man, I don't have write access to this repo... you still need to wait for the maintainers

2024-04-30 22:31 UTC, mrmagic2020 approved these changes

2024-08-26 00:54 UTC, realstealthninja requested changes
Very lovely contribution. Other than some technical assumptions being wrong. This is a great implementation. I would recommend using TOS instead of stack index. The bottom is unnecessary imo since stack follows lifo principle

2024-08-26 00:54 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +            throw std::out_of_range("Stack is empty");
```suggestion
            throw std::out_of_range("Stack underflow");
```

2024-08-26 00:54 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +
Add tests for overflow and underflow

2024-08-26 00:54 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +        }
```suggestion
    void push(T element) {
        if (full()) {
            throw std::out_of_range("Stack overflow");
        } else {
            stack[stackIndex++] = element;
        }
```

2024-08-26 00:54 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    Stack(int size) : stackSize(size), stackIndex(0) { stack = new T[size]; }
```suggestion
    Stack(int size) : stackSize(size), stackIndex(-1) { stack = new T[size]; }
```
TOS should be -1 at the start

2024-08-26 00:54 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    bool empty() const { return stackIndex == 0; }
```suggestion
    bool empty() const { return stackIndex == -1; }
```

2024-08-26 00:54 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    assert(stack.push(10) == true);
Since we are not returning true any use this as a guide

```suggestion
    stack.push(10);
    assert(stack.topmost() == 10);
```

2024-08-31 02:29 UTC, TruongNhanNguyen commented
Thanks, @realstealthninja. Can you have a look?

2024-08-31 02:43 UTC, realstealthninja requested changes

2024-08-31 02:43 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    assert(stack.empty() == true);
```suggestion
    assert(stack.empty());
```
assert checks for booleans so this should work by default

2024-08-31 02:43 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    assert(stack.full() == false);
```suggestion
    assert(!stack.full());
```

2024-08-31 02:43 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    assert(stack.empty() == true);
```suggestion
    assert(stack.empty());
```

2024-08-31 02:43 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    assert(stack.full() == true);
```suggestion
    assert(stack.full());
```

2024-08-31 02:43 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +    assert(stack.full() == false);
```suggestion
    assert(!stack.full());
```

2024-08-31 02:52 UTC, TruongNhanNguyen commented
Thanks for the quick fixes.

2024-08-31 02:52 UTC, realstealthninja commented
@TruongNhanNguyen could you delete the stack.hpp file from that directory as well? thanks.

2024-08-31 03:32 UTC, realstealthninja commented
On second thought revert that, we can do that in another pr. Sorry for the confusion. The stack.hpp problem seems out of the scope of this pr

2024-08-31 03:56 UTC, realstealthninja requested changes

2024-08-31 03:56 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +#include <stdexcept>
```suggestion
#include <cassert> /// For std::assert
#include <iostream> /// For std::cout
#include <memory> /// For std::unique_ptr
#include <stdexcept> /// For std::out_of_range
```

2024-08-31 03:57 UTC, realstealthninja submitted a review, later dismissed

2024-08-31 03:57 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +namespace data_structures {
```suggestion
/**
 * @namespace
 * @brief data_structures
 */
namespace data_structures {
```

2024-08-31 04:03 UTC, realstealthninja approved these changes
Thank you for your contribution! :heart:

2024-08-31 04:04 UTC, TruongNhanNguyen commented
Thanks for kindly reviews, and quick responses. This PR existed for a long time, so I am delighted to see it merged.

2024-08-31 07:01 UTC, realstealthninja reviewed
Commit this the most recent push must be done by you

2024-08-31 07:01 UTC, realstealthninja commented on data_structures/stack_using_array.cpp
> +     *
```suggestion
```

2024-08-31 07:07 UTC, TruongNhanNguyen commented on data_structures/stack_using_array.cpp
> +     *
What do you mean by this nit?

2024-08-31 09:33 UTC, realstealthninja approved these changes

2024-09-01 04:37 UTC, realstealthninja commented
Merging this! thanks for your contribution :heart:

2024-09-01 04:37 UTC, merged