Added Iterative Quick Sort
TheAlgorithms/C-Plus-Plus pull request #2684
Opened 2024-03-21 19:59 UTC by sebe324

#### Description of Change
I've added an implementation of iterative quick sort.
It uses the stack instead of recursion.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-04-21 19:21 UTC, sebe324 commented
can someone check this pr out? @realstealthninja

2024-08-21 02:20 UTC, realstealthninja requested changes
Clean documentation. Well written too! Thank you for this contribution ♥️

2024-08-21 02:20 UTC, realstealthninja commented on sorting/quick_sort_iterative.cpp
> + * @author Sebe324 (https://github.com/sebe324)
```suggestion
 * @author [Sebe324](https://github.com/sebe324)
```
For hyperlinking purposes

2024-08-21 02:20 UTC, realstealthninja commented on sorting/quick_sort_iterative.cpp
> +#include <cassert> //for assert
```suggestion
#include <iostream> /// for std::cout
#include <vector> /// for std::vector
#include <stack> /// for std::stack
#include <algorithm> ///for std::is_sorted
#include <cassert> /// for assert
```

2024-08-21 02:21 UTC, realstealthninja approved these changes

2024-08-21 02:21 UTC, realstealthninja commented on sorting/quick_sort_iterative.cpp
> +    tests();
```suggestion
    tests(); // run self test implementation
```

2024-08-21 02:22 UTC, realstealthninja submitted a review, later dismissed

2024-08-31 02:49 UTC, realstealthninja commented on sorting/quick_sort_iterative.cpp
> +#include <algorithm> ///for std::is_sorted
```suggestion
#include <algorithm> /// for std::is_sorted
```

2024-09-01 04:40 UTC, realstealthninja requested changes

2024-09-01 04:40 UTC, realstealthninja commented on sorting/quick_sort_iterative.cpp
> +
```suggestion


/**
 * @namespace sorting
 * @brief Sorting algorithms
 */
namespace sorting {
```
should be inside sorting namespace

2024-09-01 04:40 UTC, realstealthninja commented on sorting/quick_sort_iterative.cpp
> +
```suggestion

} // namespace sorting
```

2024-09-02 23:43 UTC, realstealthninja commented
Tests failing! The issue is the functions youre using inside test is not the namespaced one

Fix is prefixing the function calls with
```cpp
   sorting::function_name()
```

2024-09-03 06:37 UTC, sebe324 commented
Oh I forgot, I'll fix it later today.

2024-09-04 23:44 UTC, realstealthninja approved these changes
Looks good

2024-09-04 23:44 UTC, merged