Update odd_even_sort.cpp
TheAlgorithms/C-Plus-Plus pull request #2737
Opened 2024-09-24 07:16 UTC by khushbooshakya

Updated the odd even sort code with comments and simplified it to its most basic form.

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-09-24 07:18 UTC, khushbooshakya commented
Updated the odd even sort code with comments and simplified it to its most basic form.

2024-09-25 01:28 UTC, realstealthninja requested changes

2024-09-25 01:28 UTC, realstealthninja commented on sorting/odd_even_sort.cpp
> -/* C++ implementation Odd Even Sort */
There should be a header comment check other files or the contribution guidelines

2024-09-25 01:28 UTC, realstealthninja commented on sorting/odd_even_sort.cpp
>  #include <iostream>
Headers should be documented

2024-11-10 00:14 UTC, closed without merging