Update binary_insertion_sort.cpp
TheAlgorithms/C-Plus-Plus pull request #2738
Opened 2024-09-24 07:26 UTC by khushbooshakya

Improved Commenting Explanation:
General Overview:

Detailed explanation of each function and its purpose. Clearly indicates what each parameter is and how the function works. Algorithm Details:

The purpose of binary search and how it helps improve the performance of insertion sort is explained. Describes how each element is inserted in the correct place by shifting larger elements to the right. Test Function:

Comments explain what each test case is doing, what type of data is being sorted, and how the program verifies if the sorting is successful. This should help anyone reading the code to understand not only how the code works but also why each part is necessary.

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-09-24 07:27 UTC, khushbooshakya commented
Improved Commenting Explanation:
General Overview:

Detailed explanation of each function and its purpose.
Clearly indicates what each parameter is and how the function works.
Algorithm Details:

The purpose of binary search and how it helps improve the performance of insertion sort is explained.
Describes how each element is inserted in the correct place by shifting larger elements to the right.
Test Function:

Comments explain what each test case is doing, what type of data is being sorted, and how the program verifies if the sorting is successful.
This should help anyone reading the code to understand not only how the code works but also why each part is necessary.

2024-09-26 12:46 UTC, realstealthninja requested changes

2024-09-26 12:46 UTC, realstealthninja commented on sorting/binary_insertion_sort.cpp
> - * becomes
this was an unnecessary deletion. This is the format we use for documenting files

2024-09-26 12:46 UTC, realstealthninja commented on sorting/binary_insertion_sort.cpp
> + * @brief Contains sorting algorithms
why are we plagiarizing already documented namespaces

2024-09-26 12:46 UTC, realstealthninja commented on sorting/binary_insertion_sort.cpp
> + * \brief Binary search function to find the correct position for an element.
replace \'s with @'s

2024-09-26 12:46 UTC, realstealthninja commented on sorting/binary_insertion_sort.cpp
> -    test();  // run self-test implementations
please do not modify this comment

2024-11-09 00:13 UTC, closed without merging