Update bitonic_sort.cpp
TheAlgorithms/C-Plus-Plus pull request #2739
Opened 2024-09-24 07:35 UTC by khushbooshakya

Updated the bitonic sort code in simplest form

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-09-24 07:36 UTC, khushbooshakya commented
Implement Bitonic Sort Algorithm in C++

- Added compAndSwap() to compare and swap elements based on sorting direction.
- Added bitonicMerge() to merge bitonic sequences into the correct order.
- Added bitonicSort() to recursively sort and merge the array.
- Main function demonstrates sorting an array in ascending order.

2024-09-26 12:41 UTC, realstealthninja requested changes

2024-09-26 12:41 UTC, realstealthninja commented on sorting/bitonic_sort.cpp
> +*/
please use the proper comment format in the contribution guidelines

2024-09-26 12:41 UTC, realstealthninja commented on sorting/bitonic_sort.cpp
>  void compAndSwap(int a[], int i, int j, int dir) {
please document functions using the format in the contribution guidelines

2024-11-09 00:13 UTC, closed without merging