feat: LFU (Least frequently used) cache
TheAlgorithms/C-Plus-Plus pull request #2757
Opened 2024-10-04 23:04 UTC by deDSeC00720

#### Description of Change
LFU Cache implementation
In a fixed size cache, when new item is added and the cache is full
The least frequently used element is evicted from the cache

If there are multiple items with the same frequency of usage,
then the least recently used item is evicted.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

added LFU Cache with tests and usage.

2024-10-04 23:45 UTC, realstealthninja requested changes
Thank you for your contribution! Let me know if this was for hacktoberfest

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +}
```suggestion
}

```

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +
```suggestion
```

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +
```suggestion
```

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +
Please add negative numbers since youre using int as the datatype

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +namespace Cache {
This namespace should also be documented

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +template <typename T>
This class should also be documented

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +class LFUCache {
This class should be documented as well

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> +    int _capacity;  // maximum capacity of the cache
```suggestion
    std::unordered_map<K, std::pair<CacheNode<K, V> *, int>>
        node_map;  ///< maps the key to the node address and frequency
    std::unordered_map<int, std::pair<CacheNode<K, V> *, CacheNode<K, V> *>>
        freq_map;  ///< maps the frequency to doubly linked list

    int minFreq;    ///< minimum frequency in the cache
    int _capacity;  ///< maximum capacity of the cache
```

2024-10-04 23:45 UTC, realstealthninja commented on others/lfu_cache.cpp
> + *
```suggestion
 *
 * @details
```

2024-10-05 07:26 UTC, deDSeC00720 commented
> Thank you for your contribution! Let me know if this was for hacktoberfest

Yes, this is for Hacktoberfest. Thank you for reviewing my contribution.

2024-10-05 10:02 UTC, realstealthninja commented
> > Thank you for your contribution! Let me know if this was for hacktoberfest
> 
> Yes, this is for Hacktoberfest. Thank you for reviewing my contribution.

youre very welcome. lets get this accepted soon :rocket:

2024-10-05 10:31 UTC, realstealthninja requested changes

2024-10-05 10:31 UTC, realstealthninja commented on others/lfu_cache.cpp
> +#include <unordered_map>  // for hash map
```suggestion
#include <iostream>       // for std::cout
#include <unordered_map>  // for std::unordered_map
```

2024-10-05 10:31 UTC, realstealthninja commented on others/lfu_cache.cpp
> + */
```suggestion
/**
 * @class
 * @brief Node for a doubly linked list with data, prev and next pointers
 * @tparam T type of the data of the node
 */
```

2024-10-05 10:31 UTC, realstealthninja commented on others/lfu_cache.cpp
> +    D_Node<T> *next;
```suggestion
    T data;           ///< data of the node
    D_Node<T> *prev;  ///< previous node in the doubly linked list
    D_Node<T> *next;  ///< next node in the doubly linked list
```

2024-10-05 10:31 UTC, realstealthninja commented on others/lfu_cache.cpp
> + */
```suggestion
/**
 * @class
 * @brief LFUCache
 * @tparam K type of the key in the LFU
 * @tparam V type of the value in the LFU
 */
```

2024-10-05 10:31 UTC, realstealthninja commented on others/lfu_cache.cpp
> + * @brief test method with 2 tests
```suggestion
 * @brief self test implementation
```

2024-10-05 10:31 UTC, realstealthninja commented on others/lfu_cache.cpp
> +    test();
```suggestion
    test(); // runs the self test implementation
```

2024-10-05 13:35 UTC, aminegh20 commented on others/lfu_cache.cpp
> +    void inc_freq(std::pair<CacheNode<K, V> *, int> &p_node) {
I wouldn't use abbreviations that way. `void increase_frequency` is clearer.

2024-10-05 16:01 UTC, realstealthninja requested changes

2024-10-05 16:01 UTC, realstealthninja commented on others/lfu_cache.cpp
> +void test() {
```suggestion
static void tests() {
```

2024-10-05 16:01 UTC, realstealthninja commented on others/lfu_cache.cpp
> +    test();  // run the self test implementation
```suggestion
    tests();  // run the self test implementation
```

2024-10-05 16:54 UTC, deDSeC00720 commented
@realstealthninja, what is the reason for making a non member function static?
And should I make test1() and test2() static as well?

2024-10-06 02:16 UTC, realstealthninja commented
> @realstealthninja, what is the reason for making a non member function static?
> And should I make test1() and test2() static as well?

Static is used to hide the function from the global namespace. 


Imo there shouldn't be 3 test function just one with comments delimiting the cases

2024-10-06 08:03 UTC, deDSeC00720 commented
> > @realstealthninja, what is the reason for making a non member function static?
> > And should I make test1() and test2() static as well?
> 
> Static is used to hide the function from the global namespace.
> 
> Imo there shouldn't be 3 test function just one with comments delimiting the cases

Got it.

2024-10-07 00:30 UTC, realstealthninja approved these changes
Lgtm

2024-10-07 13:32 UTC, merged