fix: Adding documentations, tests, and amending algorithm for gcd_of_n_numbers.cpp
TheAlgorithms/C-Plus-Plus pull request #2766
Opened 2024-10-05 10:43 UTC by hollowcrust

#### Description of Change
Possibly fix #2456
Adding documentations, tests, and amending the algorithm to align with current guidelines.

#### Checklist

- [x] Added description of change
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
The current algorithm is not accurate and also does not account for 0 in the array, especially when GCD is undefined if all elements are 0.

2024-10-05 11:28 UTC, realstealthninja commented
please unlink #2456 this does not fix the entirety of that issue. feel free to raise another issue with the name of the algorithm you intend to help update instead.

2024-10-05 11:34 UTC, realstealthninja requested changes

2024-10-05 11:34 UTC, realstealthninja commented on math/gcd_of_n_numbers.cpp
> + * i.e. gcd(a, b, c) = gcd(gcd(a, b), c)
feel free to add latex notation of the maths formula to this description

2024-10-05 11:34 UTC, realstealthninja commented on math/gcd_of_n_numbers.cpp
> +#include <cassert>  /// for assert
lint this file with clang format

2024-10-05 11:34 UTC, realstealthninja commented on math/gcd_of_n_numbers.cpp
> +    int array_6[5] = {0, 0, 0, 0, 0};
add test cases for large numbers

2024-10-05 11:34 UTC, realstealthninja commented on math/gcd_of_n_numbers.cpp
> +int gcd(int a[], size_t n) {
instead of using a fundamental array
an array from <array>
that is std::array<type>

this lets you remove the size parameter

2024-10-05 11:34 UTC, realstealthninja commented
on a side note is this for hacktober fest so i can label it as such

2024-10-05 12:02 UTC, hollowcrust commented
Hi yes this is for Hacktoberfest. Thank you :)

2024-10-06 02:26 UTC, realstealthninja requested changes
Lint this file using clang tidy

2024-10-07 00:19 UTC, realstealthninja approved these changes
Lgtm

2024-10-07 00:21 UTC, realstealthninja commented
Thank you for you're contribution. A very well written pr. I will leave this up and if there is no objections will merge in a few days. Best wishes for the rest of hacktoberfest ♥️

2024-10-07 05:30 UTC, hollowcrust commented
> Thank you for you're contribution. A very well written pr. I will leave this up and if there is no objections will merge in a few days. Best wishes for the rest of hacktoberfest ♥️

Thanks!

2024-10-07 13:26 UTC, merged