docs, test: Add documentations and tests for modular_inverse_fermat_little_theorem.cpp
TheAlgorithms/C-Plus-Plus pull request #2779
Opened 2024-10-07 07:09 UTC by hollowcrust

#### Description of Change
Reformat math/modular_inverse_fermat_little_theorem.cpp by adding namespaces, documentations, tests.

#### Checklist

- [x] Added description of change
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
For Hacktoberfest, for #2456

2024-10-07 13:20 UTC, realstealthninja requested changes

2024-10-07 13:20 UTC, realstealthninja commented on math/modular_inverse_fermat_little_theorem.cpp
> -/** Prime check in \f$O(\sqrt{m})\f$ time.
it would good if you add the latex notation aswell

2024-10-07 13:20 UTC, realstealthninja commented on math/modular_inverse_fermat_little_theorem.cpp
> + * @return 'true' if the number is prime, otherwise 'false'
```suggestion
 * @return true if the number is prime
 * @return false if the number is not prime
```

2024-10-07 13:20 UTC, realstealthninja commented on math/modular_inverse_fermat_little_theorem.cpp
> + * @brief Main function to calculate the modular inverse.
```suggestion
 * @brief calculates the modular inverse.
```

2024-10-07 21:30 UTC, TIKTOK-ux commented on math/modular_inverse_fermat_little_theorem.cpp
> + * @brief Main function to calculate the modular inverse.
` yarn add  artificialintelligence && yarn install`

2024-10-09 04:27 UTC, hollowcrust commented
@realstealthninja Hi can you help me review please?

2024-10-11 04:02 UTC, realstealthninja requested changes

2024-10-11 04:02 UTC, realstealthninja commented on math/modular_inverse_fermat_little_theorem.cpp
> + * algorithm works in logarithmic time.
the latex notation should also be there

2024-10-12 07:59 UTC, realstealthninja approved these changes
LGTM

2024-10-21 13:21 UTC, merged