Updated circular_queue_using_array.cpp
TheAlgorithms/C-Plus-Plus pull request #2812
Opened 2024-10-11 03:42 UTC by Bucke200

The current code is more efficient and more structured than the previous one, both in terms of readability and performance. I removed some unnecessary checks and added more documentation

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-10-11 04:17 UTC, realstealthninja requested changes

2024-10-11 04:17 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
>  int main() {
main function should not have any code except for a call to tests

2024-10-11 04:17 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
add tests

2024-10-11 04:17 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
> +int count = 0;       // Keeps track of the number of elements in the queue
queue should be a class not a set of functions

2024-10-11 04:17 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
>  using namespace std;
using namespace std is bad practice and hence should be removed from the repository

2024-10-11 04:17 UTC, realstealthninja commented
Please check the checkboxes in your pr.

2024-10-11 04:19 UTC, Bucke200 commented
ok working on it

2024-10-11 04:57 UTC, Bucke200 commented
@realstealthninja please check again and let me know if anything needs to be addressed

2024-10-12 08:15 UTC, realstealthninja requested changes

2024-10-12 08:15 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
> +    int queue[MAX_SIZE]; ///< Array to store the queue elements
should use std::array

2024-10-12 08:15 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
> +    static const int MAX_SIZE = 10; ///< The maximum number of elements the queue can hold
```suggestion
    static const size_t MAX_SIZE = 10; ///< The maximum number of elements the queue can hold
```

2024-10-12 08:15 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
> +    Queue();
implementation and declaration should not be separated. please combine them

2024-10-12 08:16 UTC, realstealthninja requested changes

2024-10-12 08:16 UTC, realstealthninja commented on operations_on_datastructures/circular_queue_using_array.cpp
> +class Queue {
this class could be generic and store all types of elements

2024-12-09 00:15 UTC, closed without merging