Feature :Added playfair cipher
TheAlgorithms/C-Plus-Plus pull request #2813
Opened 2024-10-11 07:51 UTC by JaydityaDhaka

#### Description of Change

This pull request adds the implementation of the Playfair Cipher algorithm. The Playfair cipher is a digraph substitution cipher, which encrypts pairs of letters from the plaintext using a 5x5 grid. It provides both encryption and decryption functions, handling edge cases such as repeated letters and handling of the 'j' character by replacing it with 'i'.

Key Features:

- Implementation of the encryption and decryption methods.
- A utility to clean input strings by removing non-alphabet characters and converting the text to lowercase.
- Generation of the Playfair 5x5 grid based on a provided key.
- Supports formatted digraphs and insertion of 'x' for repeated characters and padding.

#### Checklist

[x] Added description of change
[x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
[x] Added tests and example, test must pass
[x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
[x] Relevant documentation/comments is changed or added
[x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
[x] Search previous suggestions before making a new one, as yours may be a duplicate.
[x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
This pull request includes a detailed file header using Doxygen-style comments, an example of usage with both encryption and decryption of sample text, and test cases to ensure the correctness of the algorithm.

2024-10-14 21:45 UTC, JaydityaDhaka commented
are there any additional requirments for this PR?

2024-10-15 13:05 UTC, realstealthninja requested changes

2024-10-15 13:05 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> +#include <vector>
document headers please

2024-10-15 13:05 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> + * \brief Algorithms for encryption and decryption
use @ tags instead of \ tags

2024-10-18 16:21 UTC, JaydityaDhaka commented
Have put in all the necessary changes

2024-10-19 09:46 UTC, realstealthninja requested changes

2024-10-19 09:46 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> + * The Playfair cipher is a digraph substitution cipher, meaning that it encrypts pairs of letters (digraphs)
lint your file using clang tidy please, Thanks!

2024-10-19 09:46 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> +    std::cout << " , Encrypted text (key = OLDTAVERN): " << encrypted2;
instead of outputing your result check them against the orignal

2024-10-19 09:46 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> +    std::cout << " , Decrypted text: " << decrypted1 << std::endl;
```suggestion
   assert(text1 == decrypted1);

```

2024-10-19 09:46 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> +    std::cout << " , Decrypted text: " << decrypted2 << std::endl;
```suggestion
    assert(text2 == decrypted2)

```

2024-10-23 14:06 UTC, realstealthninja commented on ciphers/playfair_cipher.cpp
> + * The Playfair cipher is a digraph substitution cipher, meaning that it encrypts pairs of letters (digraphs)
file does not seem linted!

2024-10-23 14:06 UTC, realstealthninja requested changes
file is still not linted

2024-12-26 00:13 UTC, closed without merging