Create Quickselect for Finding the k-th Smallest Element.cpp
TheAlgorithms/C-Plus-Plus pull request #2820
Opened 2024-10-12 09:53 UTC by dev-priyanshu15

#### Description of Change

#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes:

2024-10-12 09:53 UTC, dev-priyanshu15 commented
dont forget to add hactoberfest label

2024-10-19 09:53 UTC, realstealthninja requested changes

2024-10-23 14:09 UTC, realstealthninja requested changes

2024-10-23 14:09 UTC, realstealthninja commented on search/Quickselect for Finding the k-th Smallest Element.cpp
> +#include <iostream>
please address this.

2024-12-15 00:16 UTC, closed without merging