Create adaptive_merge_sort.cpp
TheAlgorithms/C-Plus-Plus pull request #2826
Opened 2024-10-12 21:07 UTC by anant-jain01

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Adaptive merge sort code

2024-10-13 15:11 UTC, anant-jain01 commented
@Panquesito7 @realstealthninja please do the needful

2024-10-15 13:14 UTC, realstealthninja requested changes

2024-10-15 13:14 UTC, realstealthninja commented on sorting/adaptive_merge_sort.cpp
> +#include <cassert>
document headers please

2024-10-15 13:14 UTC, realstealthninja commented on sorting/adaptive_merge_sort.cpp
> +    std::vector<int> expectedIntegers = {1, 4, 6, 9, 12, 23, 54, 78, 231};
add test case for negative numbers

2024-10-15 14:09 UTC, anant-jain01 commented
@realstealthninja @Panquesito7 please recheck and approve under hacktoberfest tag...

2024-10-21 13:11 UTC, realstealthninja requested changes

2024-12-15 00:16 UTC, closed without merging