feat:Added Implementation of Split_Largest_Array_Sum Algorithm
TheAlgorithms/C-Plus-Plus pull request #2832
Opened 2024-10-13 22:49 UTC by ARYPROGRAMMER

#### Description of Change

Added the Solution to LeetCode (Medium-DP) Question "Split Largest Sum Array"

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: Uses O(n) efficient approach to handle all test cases

2024-10-21 13:16 UTC, realstealthninja requested changes

2024-10-21 13:16 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +#include <iostream>
document headers using https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md

2024-10-21 13:16 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +        int dp[1003][53];
use array from stl

2024-10-21 13:16 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +
redundant variables

2024-10-21 13:16 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +    std::cout << "The minimum largest sum of the split is : " << ans << std::endl;
```suggestion
```
no code inside main function please

2024-10-21 13:30 UTC, ARYPROGRAMMER reviewed
tried to solve all changes, waiting for re-review

2024-10-31 05:23 UTC, realstealthninja requested changes

2024-10-31 05:23 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +        int dp[1003][53];
Should use std::array

2024-10-31 05:23 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +
File should be linted using clang tidy/ format

2024-10-31 05:23 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +namespace dynamic_programming {
Namespaces should be documented

2024-10-31 05:23 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +#include <iostream>
Headers should be documented

2024-10-31 05:23 UTC, realstealthninja commented on dynamic_programming/split_array_largest_sum.cpp
> +    handleUserIO();
No user inputs please, would make it untestable

2024-10-31 06:33 UTC, ARYPROGRAMMER reviewed
@realstealthninja please review and verify changes

2024-12-15 00:16 UTC, closed without merging