docs, test, fix: Fit Fast_Power to contributing guidelines and fix bug
TheAlgorithms/C-Plus-Plus pull request #2888
Opened 2024-10-30 10:26 UTC by endorphin-naixu

Fit Fast_Power to contributing guidelines.
Return NAN when the base is 0 and the exponent is non-positive
I noticed that the original test program used "==" to test the result, and when the exponent is negative, it is obviously unreasonable to use "==" to compare two floating-point numbers, so I introduced a value "epsilon = 1e-8" as the error range.
Delete the useless output from the original test code and keep only the output of "All tests have successfully passed!".

#### Description of Change

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Fix issue #2456

2024-10-31 05:29 UTC, realstealthninja requested changes

2024-10-31 05:29 UTC, realstealthninja commented on math/fast_power.cpp
> + * @author
I think you can find the author from commits to this file

2024-10-31 05:29 UTC, realstealthninja commented on math/fast_power.cpp
> + * @see
seems unnecessary

2024-10-31 05:29 UTC, realstealthninja commented on math/fast_power.cpp
> +
```suggestion
```

2024-11-21 02:55 UTC, endorphin-naixu commented
Please take a look @realstealthninja

2024-12-05 02:26 UTC, endorphin-naixu commented
cc @realstealthninja

2025-01-12 00:14 UTC, closed without merging